/**
 * OpenRouter Cost Tracking Utility
 *
 * Auto-generated by ManageMe. Extracts usage metadata from OpenRouter
 * responses and logs to the api_calls database table.
 */

import { SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";

// OpenRouter response type
export interface OpenRouterResponse {
  id?: string;
  choices: Array<{
    message: {
      content: string;
      images?: Array<{ image_url?: { url: string } }>;
    };
  }>;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
  model?: string;
  provider?: string;
}

// Cost data extracted from response
export interface CostData {
  model: string;
  provider: string | null;
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  estimated_cost_usd: number;
}

// Pricing table (per 1K tokens)
// Updated periodically based on OpenRouter pricing
const MODEL_PRICING: Record<string, { input: number; output: number }> = {
  // Anthropic
  "anthropic/claude-3.5-sonnet": { input: 0.003, output: 0.015 },
  "anthropic/claude-3-sonnet": { input: 0.003, output: 0.015 },
  "anthropic/claude-3-haiku": { input: 0.00025, output: 0.00125 },
  "anthropic/claude-3-opus": { input: 0.015, output: 0.075 },
  // OpenAI
  "openai/gpt-4o": { input: 0.005, output: 0.015 },
  "openai/gpt-4o-mini": { input: 0.00015, output: 0.0006 },
  "openai/gpt-4-turbo": { input: 0.01, output: 0.03 },
  "openai/gpt-4": { input: 0.03, output: 0.06 },
  "openai/gpt-3.5-turbo": { input: 0.0005, output: 0.0015 },
  // Google
  "google/gemini-pro": { input: 0.00025, output: 0.0005 },
  "google/gemini-pro-1.5": { input: 0.00125, output: 0.005 },
  // Meta (free tier)
  "meta-llama/llama-3.1-8b-instruct:free": { input: 0, output: 0 },
  // Default fallback
  "default": { input: 0.001, output: 0.002 },
};

/**
 * Calculate estimated cost from token usage
 */
function calculateCost(
  model: string | undefined,
  usage: { prompt_tokens: number; completion_tokens: number }
): number {
  const pricing = MODEL_PRICING[model || ""] || MODEL_PRICING["default"];
  return (
    (usage.prompt_tokens * pricing.input +
      usage.completion_tokens * pricing.output) /
    1000
  );
}

/**
 * Extract cost data from OpenRouter API response
 */
export function extractCostData(response: OpenRouterResponse): CostData {
  const usage = response.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 };
  const model = response.model || "unknown";

  return {
    model,
    provider: response.provider || null,
    prompt_tokens: usage.prompt_tokens,
    completion_tokens: usage.completion_tokens,
    total_tokens: usage.total_tokens,
    estimated_cost_usd: calculateCost(model, usage),
  };
}

/**
 * Log an API call to the database
 */
export async function logApiCall(
  supabase: SupabaseClient,
  params: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
    costData: CostData;
    success?: boolean;
    error_message?: string;
  }
): Promise<void> {
  try {
    const { error } = await supabase.from("api_calls").insert({
      group_id: params.group_id || null,
      user_id: params.user_id || null,
      function_name: params.function_name,
      mode: params.mode || null,
      model: params.costData.model,
      provider: params.costData.provider,
      prompt_tokens: params.costData.prompt_tokens,
      completion_tokens: params.costData.completion_tokens,
      total_tokens: params.costData.total_tokens,
      estimated_cost_usd: params.costData.estimated_cost_usd,
      success: params.success ?? true,
      error_message: params.error_message || null,
    });

    if (error) {
      console.warn("Failed to log API call:", error.message);
    }
  } catch (err) {
    console.warn("Failed to log API call:", err);
  }
}

/**
 * Convenience function to extract and log in one call
 */
export async function trackApiCall(
  supabase: SupabaseClient,
  response: OpenRouterResponse,
  params: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
  }
): Promise<CostData> {
  const costData = extractCostData(response);

  await logApiCall(supabase, {
    ...params,
    costData,
    success: true,
  });

  return costData;
}

/**
 * Log a failed API call (for error tracking)
 */
export async function trackApiError(
  supabase: SupabaseClient,
  params: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
    model?: string;
    error_message: string;
  }
): Promise<void> {
  await logApiCall(supabase, {
    ...params,
    costData: {
      model: params.model || "unknown",
      provider: null,
      prompt_tokens: 0,
      completion_tokens: 0,
      total_tokens: 0,
      estimated_cost_usd: 0,
    },
    success: false,
    error_message: params.error_message,
  });
}
