/**
 * OpenRouter Cost Tracking Utility (Webhook Version)
 *
 * Auto-generated by ManageMe. POSTs cost data to ManageMe webhook.
 */

// OpenRouter response type
export interface OpenRouterResponse {
  id?: string;
  choices: Array<{
    message: {
      content: string;
      images?: Array<{ image_url?: { url: string } }>;
    };
  }>;
  usage?: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
  };
  model?: string;
  provider?: string;
}

// Cost data extracted from response
export interface CostData {
  model: string;
  provider: string | null;
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  estimated_cost_usd: number;
}

// Configuration
const PROJECT_NAME = "ml_companion";
const MANAGEME_WEBHOOK_URL = Deno.env.get("MANAGEME_WEBHOOK_URL") ||
  "http://localhost:3000/api/costs/log";

// Pricing table (per 1K tokens)
const MODEL_PRICING: Record<string, { input: number; output: number }> = {
  // Anthropic
  "anthropic/claude-3.5-sonnet": { input: 0.003, output: 0.015 },
  "anthropic/claude-3-sonnet": { input: 0.003, output: 0.015 },
  "anthropic/claude-3-haiku": { input: 0.00025, output: 0.00125 },
  "anthropic/claude-3-opus": { input: 0.015, output: 0.075 },
  // OpenAI
  "openai/gpt-4o": { input: 0.005, output: 0.015 },
  "openai/gpt-4o-mini": { input: 0.00015, output: 0.0006 },
  "openai/gpt-4-turbo": { input: 0.01, output: 0.03 },
  "openai/gpt-4": { input: 0.03, output: 0.06 },
  "openai/gpt-3.5-turbo": { input: 0.0005, output: 0.0015 },
  // Google
  "google/gemini-pro": { input: 0.00025, output: 0.0005 },
  "google/gemini-pro-1.5": { input: 0.00125, output: 0.005 },
  // xAI
  "x-ai/grok-4.1-fast": { input: 0.003, output: 0.015 },
  // Meta (free tier)
  "meta-llama/llama-3.1-8b-instruct:free": { input: 0, output: 0 },
  // Default fallback
  "default": { input: 0.001, output: 0.002 },
};

/**
 * Calculate estimated cost from token usage
 */
function calculateCost(
  model: string | undefined,
  usage: { prompt_tokens: number; completion_tokens: number }
): number {
  const pricing = MODEL_PRICING[model || ""] || MODEL_PRICING["default"];
  return (
    (usage.prompt_tokens * pricing.input +
      usage.completion_tokens * pricing.output) /
    1000
  );
}

/**
 * Extract cost data from OpenRouter API response
 */
export function extractCostData(response: OpenRouterResponse): CostData {
  const usage = response.usage || { prompt_tokens: 0, completion_tokens: 0, total_tokens: 0 };
  const model = response.model || "unknown";

  return {
    model,
    provider: response.provider || null,
    prompt_tokens: usage.prompt_tokens,
    completion_tokens: usage.completion_tokens,
    total_tokens: usage.total_tokens,
    estimated_cost_usd: calculateCost(model, usage),
  };
}

/**
 * Post cost data to ManageMe webhook
 */
async function postToWebhook(entry: Record<string, unknown>): Promise<boolean> {
  try {
    const response = await fetch(MANAGEME_WEBHOOK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(entry),
    });
    return response.status === 201;
  } catch (err) {
    console.warn("[cost-tracker] Webhook POST failed:", err);
    return false;
  }
}

/**
 * Track an API call by posting to ManageMe webhook
 *
 * Accepts optional first argument for backward compatibility with
 * existing code that passes Supabase client (now ignored).
 */
export async function trackApiCall(
  // First arg can be supabase client (ignored) or response
  firstArg: unknown,
  // Second arg can be response or params
  secondArg: OpenRouterResponse | {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
  },
  // Third arg is params if first arg was supabase
  thirdArg?: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
  }
): Promise<CostData> {
  // Handle both signatures:
  // trackApiCall(supabase, response, params) - old signature
  // trackApiCall(response, params) - new signature
  let response: OpenRouterResponse;
  let params: { group_id?: string; user_id?: string; function_name: string; mode?: string };

  if (thirdArg) {
    // Old signature: trackApiCall(supabase, response, params)
    response = secondArg as OpenRouterResponse;
    params = thirdArg;
  } else {
    // New signature: trackApiCall(response, params)
    response = firstArg as OpenRouterResponse;
    params = secondArg as typeof params;
  }

  const costData = extractCostData(response);

  const entry = {
    project: PROJECT_NAME,
    timestamp: new Date().toISOString(),
    function_name: params.function_name,
    mode: params.mode || null,
    model: costData.model,
    provider: costData.provider,
    prompt_tokens: costData.prompt_tokens,
    completion_tokens: costData.completion_tokens,
    total_tokens: costData.total_tokens,
    cost: costData.estimated_cost_usd,
    // Include group/user for context (ManageMe can use or ignore)
    metadata: {
      group_id: params.group_id,
      user_id: params.user_id,
    },
  };

  // Wait for webhook to complete (edge functions may terminate early otherwise)
  await postToWebhook(entry);

  return costData;
}

/**
 * Track a failed API call
 */
export async function trackApiError(
  params: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
    model?: string;
    error_message: string;
  }
): Promise<void> {
  const entry = {
    project: PROJECT_NAME,
    timestamp: new Date().toISOString(),
    function_name: params.function_name,
    mode: params.mode || null,
    model: params.model || "unknown",
    prompt_tokens: 0,
    completion_tokens: 0,
    total_tokens: 0,
    cost: 0,
    success: false,
    error_message: params.error_message,
    metadata: {
      group_id: params.group_id,
      user_id: params.user_id,
    },
  };

  postToWebhook(entry).catch(() => {});
}

// Legacy function signature compatibility (supabase client no longer needed)
export async function logApiCall(
  _supabase: unknown,
  params: {
    group_id?: string;
    user_id?: string;
    function_name: string;
    mode?: string;
    costData: CostData;
    success?: boolean;
    error_message?: string;
  }
): Promise<void> {
  const entry = {
    project: PROJECT_NAME,
    timestamp: new Date().toISOString(),
    function_name: params.function_name,
    mode: params.mode || null,
    model: params.costData.model,
    provider: params.costData.provider,
    prompt_tokens: params.costData.prompt_tokens,
    completion_tokens: params.costData.completion_tokens,
    total_tokens: params.costData.total_tokens,
    cost: params.costData.estimated_cost_usd,
    success: params.success ?? true,
    error_message: params.error_message || null,
    metadata: {
      group_id: params.group_id,
      user_id: params.user_id,
    },
  };

  await postToWebhook(entry);
}
