-- Part 2
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Sex on Fire', 'Kings of Leon', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Last One to Die', 'Rancid', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ruby Soho', 'Rancid', 1995, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Time Bomb', 'Rancid', 1995, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Prayer of the Refugee', 'Rise Against', 2006, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Re-Education (Through Labor)', 'Rise Against', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Savior', 'Rise Against', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Sweetness & Light', 'Lush', 1990, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Down', 'Blink-182', 2003, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Feeling This', 'Blink-182', 2003, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Rock Show', 'Blink-182', 2001, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('100,000 Years (Live)', 'Kiss', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Deuce (Live)', 'Kiss', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Parasite (Live)', 'Kiss', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pork and Beans', 'Weezer', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Undone - The Sweater Song', 'Weezer', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Out Here All Night', 'Damone', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('(Funky) Sex Farm', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(Listen to the) Flower People (Reggae Stylee)', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('America', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Big Bottom', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cups and Cakes', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gimme Some Money', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heavy Duty', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hell Hole', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rock ''n'' Roll Creation', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stonehenge', 'Spinal Tap', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Clint Eastwood', 'Gorillaz', 2001, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Feel Good Inc.', 'Gorillaz', 2005, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Re-Hash', 'Gorillaz', 2001, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Piece of My Heart', 'Janis Joplin', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chest Fever (Live)', 'The Band', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('White Rabbit', 'Jefferson Airplane', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Magic Bus (Live at Leeds)', 'The Who', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Rain', 'Blind Melon', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('There''s No Other Way', 'Blur', 1991, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I''m Shipping Up to Boston', 'Dropkick Murphys', 2005, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Inside Out', 'Eve 6', 1998, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Predict a Riot', 'Kaiser Chiefs', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('All My Life', 'Foo Fighters', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I''ll Stick Around', 'Foo Fighters', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Lonely as You', 'Foo Fighters', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Mony Mony', 'Billy Idol', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rebel Yell', 'Billy Idol', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Stop', 'Fleetwood Mac', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('World Turning', 'Fleetwood Mac', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('She''s a Genius', 'Jet', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Won''t Back Down', 'Tom Petty', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Runnin'' Down a Dream', 'Tom Petty', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bat Country', 'Avenged Sevenfold', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Town Called Malice', 'The Jam', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Going Underground', 'The Jam', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Supersonic (Live)', 'Oasis', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Guerrilla Radio', 'Rage Against the Machine', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('And She Was', 'Talking Heads', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Crosseyed and Painless', 'Talking Heads', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Girlfriend Is Better', 'Talking Heads', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Once in a Lifetime', 'Talking Heads', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Take Me to the River', 'Talking Heads', 1978, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Science Genius Girl', 'Freezepop', 2000, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Re: Your Brains', 'Jonathan Coulton', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Origin of Species', 'MC Frontalot', 2007, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Opening Band', 'Paul and Storm', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Kryptonite', '3 Doors Down', 2000, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gasoline', 'Audioslave', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('ABC', 'The Jackson 5', 1970, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('666', 'Anvil', 1982, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Metal on Metal', 'Anvil', 1982, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This is Thirteen', 'Anvil', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pick Me Up', 'Dinosaur Jr.', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Wagon', 'Dinosaur Jr.', 1991, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hand Me Down World', 'The Guess Who', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Time', 'The Guess Who', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock Your Socks', 'Tenacious D', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tribute', 'Tenacious D', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gonna See My Friend', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Got Some', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('The Fixer', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Johnny Guitar', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Just Breathe', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Amongst the Waves', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Unthought Known', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Supersonic', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Speed of Sound', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Force of Nature', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('The End', 'Pearl Jam', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('A Looking in View', 'Alice in Chains', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Check My Brain', 'Alice in Chains', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('No Excuses', 'Alice in Chains', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Rooster', 'Alice in Chains', 1992, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Would?', 'Alice in Chains', 1992, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('I Will Not Bow', 'Breaking Benjamin', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('So Cold', 'Breaking Benjamin', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Diary of Jane', 'Breaking Benjamin', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('U Suck', 'Just Kait', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Dude', 'Kula Shaker', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Knight on the Town', 'Kula Shaker', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Many Shades of Black', 'The Raconteurs', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Salute Your Solution', 'The Raconteurs', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Steady, As She Goes', 'The Raconteurs', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Dance Epidemic', 'Electric Six', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gay Bar', 'Electric Six', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Like You', 'Electric Six', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Head Over Feet', 'Alanis Morissette', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ironic', 'Alanis Morissette', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Handlebars', 'Flobots', 2008, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('(We Are) The Road Crew ''08', 'Motörhead', 1980, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('More Than Meets the Eye', 'Testament', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Show Me the Way', 'Black Tide', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('What''s My Age Again?', 'Blink-182', 1999, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Satch Boogie', 'Joe Satriani', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Surfing with the Alien', 'Joe Satriani', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Icarus - Borne on Wings of Steel (Live)', 'Kansas', 1978, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Point of Know Return (Live)', 'Kansas', 1978, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Andres', 'L7', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Another One Bites the Dust', 'Queen', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crazy Little Thing Called Love', 'Queen', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('One Vision', 'Queen', 1986, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fat Bottomed Girls', 'Queen', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Want It All', 'Queen', 1989, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Want to Break Free (RB2 Version)', 'Queen', 1984, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Somebody to Love (RB2 Version)', 'Queen', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tie Your Mother Down', 'Queen', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Under Pressure', 'Queen', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dragula', 'Rob Zombie', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Rob Zombie', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Superbeast', 'Rob Zombie', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('White Unicorn', 'Wolfmother', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('New Moon Rising', 'Wolfmother', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pilgrim', 'Wolfmother', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sundial', 'Wolfmother', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock Me', 'Liz Phair', 2003, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Best of Me', 'Morningwood', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sugarbaby', 'Morningwood', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Best of You', 'Foo Fighters', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Pretender', 'Foo Fighters', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wheels', 'Foo Fighters', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Word Forward', 'Foo Fighters', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('About a Girl', 'Nirvana', 1989, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Blew', 'Nirvana', 1989, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('School', 'Nirvana', 1989, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Fake Friends', 'Joan Jett & The Blackhearts', 1983, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('A Day Like This', 'SpongeBob SquarePants', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Employee of the Month', 'SpongeBob SquarePants', 2006, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Ridin'' the Hook', 'SpongeBob SquarePants', 2006, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Dead Leaves and the Dirty Ground', 'The White Stripes', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Girl, You Have No Faith in Medicine', 'The White Stripes', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Icky Thump', 'The White Stripes', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Smash It Up (Part II)', 'The Damned', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Club Foot', 'Kasabian', 2004, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Thieves', 'AFI', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('End Transmission', 'AFI', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Love Like Winter', 'AFI', 2006, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Medicate', 'AFI', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('The Leaving Song Pt. II', 'AFI', 2003, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Walk Like An Egyptian', 'The Bangles', 1986, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('New Fang', 'Them Crooked Vultures', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Thing About You (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('American Girl (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Even the Losers (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Here Comes My Girl (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mary Jane''s Last Dance (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Refugee (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Miss Independent', 'Kelly Clarkson', 2003, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Who Knew', 'P!nk', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Our Lips Are Sealed', 'Go-Go''s', 1981, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come As You Are (Live from MTV Unplugged)', 'Nirvana', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Lithium (Live at Reading)', 'Nirvana', 1991, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('(You Can Still) Rock in America', 'Night Ranger', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Tell Me You Love Me', 'Night Ranger', 1982, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You''re Gonna Hear From Me', 'Night Ranger', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Duality', 'Slipknot', 2004, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Psychosocial', 'Slipknot', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sulfur', 'Slipknot', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Am a Rock', 'Simon & Garfunkel', 1966, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Sounds of Silence', 'Simon & Garfunkel', 1966, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dreaming of Love', 'Lights Resolve', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Christian''s Inferno', 'Green Day', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Last of the American Girls', 'Green Day', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('¡Viva la Gloria!', 'Green Day', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Kings and Queens', '30 Seconds to Mars', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('This Is War', '30 Seconds to Mars', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Gives You Hell', 'All-American Rejects', 2008, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('(If You''re Wondering If I Want You To) I Want You To', 'Weezer', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Beverly Hills', 'Weezer', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Let It All Hang Out', 'Weezer', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Build a Bridge', 'Limp Bizkit', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('A Lot Like Me', 'The Offspring', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ocean Avenue', 'Yellowcard', 2003, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Any Man of Mine', 'Shania Twain', 1995, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Cry Lonely', 'Cross Canadian Ragweed', 2007, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Good Time', 'Alan Jackson', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('I Told You So', 'Keith Urban', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('She''s Country', 'Jason Aldean', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('The Gambler', 'Kenny Rogers', 1978, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('This One''s for the Girls', 'Martina McBride', 2003, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Band on the Run (Live)', 'Paul McCartney', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jet (Live)', 'Paul McCartney', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sing the Changes (Live)', 'Paul McCartney', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Adam''s Song', 'Blink-182', 1999, 'Punk', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('First Date', 'Blink-182', 2001, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('I Miss You', 'Blink-182', 2003, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Love My Way', 'The Psychedelic Furs', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Sister Europe', 'The Psychedelic Furs', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Rock ''n'' Roll High School', 'Ramones', 1978, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Grind', 'Alice in Chains', 1995, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Heaven Beside You', 'Alice in Chains', 1995, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Last of My Kind', 'Alice in Chains', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('We Die Young', 'Alice in Chains', 1990, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Your Decision', 'Alice in Chains', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('A Woman in Love (It''s Not Me) (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Breakdown (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Century City (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jammin'' Me (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nightwatchman (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Waiting (Live)', 'Tom Petty and the Heartbreakers', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('1901', 'Phoenix', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Lisztomania', 'Phoenix', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Blue Jeans', 'Silvertide', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hair of the Dog', 'Nazareth', 1975, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Killed by Death ''08', 'Motörhead', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Levitate', 'I Mother Earth', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Master of the Universe', 'Hawkwind', 1971, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Transmaniacon MC', 'Blue Öyster Cult', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gone', 'Montgomery Gentry', 2004, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Me and My Gang', 'Rascal Flatts', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('On the Road Again', 'Willie Nelson', 1980, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('She Thinks My Tractor''s Sexy', 'Kenny Chesney', 1999, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Swing', 'Trace Adkins', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Suds in the Bucket', 'Sara Evans', 2003, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('The Who Super Bowl S-mashup', 'The Who', 2010, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Holy Wars... The Punishment Due', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Take No Prisoners', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Five Magics', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Poison Was the Cure', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lucretia', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tornado of Souls', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dawn Patrol', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rust In Peace... Polaris', 'Megadeth', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(Sittin'' on the) Dock of the Bay (Take 2)', 'Otis Redding', 1967, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Fa-Fa-Fa-Fa-Fa (Sad Song)', 'Otis Redding', 1966, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('I''m Sick Y''all', 'Otis Redding', 1966, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('I''ve Got Dreams to Remember', 'Otis Redding', 1968, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Love Man', 'Otis Redding', 1969, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Weightless', 'All Time Low', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Fascination', 'Alphabeat', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stray Cat Strut', 'Brian Setzer', 1982, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Let Forever Be', 'The Chemical Brothers', 1998, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Heartkiller', 'HIM', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ode to Solitude', 'HIM', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wings of a Butterfly', 'HIM', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Distracted', 'KSM', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Dope Show', 'Marilyn Manson', 1998, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Just for Tonight', 'One Night Only', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Walking on the Moon', 'The Police', 1979, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Meaning of Life', 'Disturbed', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Game', 'Disturbed', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Voices', 'Disturbed', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Third Floor Story', 'The Mother Hips', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('White Falcon Fuzz', 'The Mother Hips', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Panic Switch', 'Silversun Pickups', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sort Of', 'Silversun Pickups', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Downfall', 'Trust Company', 2002, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Decent Days and Nights', 'The Futureheads', 2004, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Hounds of Love', 'The Futureheads', 2004, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Walk Away', 'James Gang', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Hockey Theme', 'Neil Peart', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Tie You Down', 'Shaimus', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fell in Love with a Girl', 'The White Stripes', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Seven Nation Army', 'The White Stripes', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Don''t Know What Love Is (You Just Do as You''re Told)', 'The White Stripes', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bad Romance', 'Lady Gaga', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Monster', 'Lady Gaga', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Poker Face', 'Lady Gaga', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Just Dance', 'Lady Gaga', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Lady Gaga''s Poker Face (South Park Version)', 'Eric Cartman', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('It''s Not My Time', '3 Doors Down', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Control', 'Mute Math', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Oh Yeah', 'The Subways', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rock & Roll Queen', 'The Subways', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Blue Spark', 'X', 1982, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Hungry Wolf', 'X', 1982, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('I Must Not Think Bad Thoughts', 'X', 1983, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Am I Crazy', 'Little Fish', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bang Bang', 'Little Fish', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Darling Dear', 'Little Fish', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Outer Space', 'Ace Frehley', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('All-American Girl', 'Carrie Underwood', 2007, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Stop and Stare', 'OneRepublic', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Up From the Skies', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spanish Castle Magic', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wait Until Tomorrow', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ain''t No Telling', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Little Wing', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('If 6 Was 9', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Got Me Floatin''', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Castles Made of Sand', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('She''s So Fine', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('One Rainy Wish', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Little Miss Lover', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Bold as Love', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Valleys of Neptune', 'Jimi Hendrix', 2010, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Feel Good Drag', 'Anberlin', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Live Life Loud', 'Hawk Nelson', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Monster', 'Skillet', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stand in the Rain', 'Superchick', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Meant to Live', 'Switchfoot', 2003, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Fire It Up', 'Thousand Foot Krutch', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Empty Walls', 'Serj Tankian', 2007, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sky Is Over', 'Serj Tankian', 2007, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('All-Star', 'Smash Mouth', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blood on My Hands', 'The Used', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Born to Quit', 'The Used', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('The Taste of Ink', 'The Used', 2002, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Guns of Summer', 'Coheed and Cambria', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Here We Are Juggernaut', 'Coheed and Cambria', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The Broken', 'Coheed and Cambria', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Peek-a-Boo', 'Siouxsie and The Banshees', 1988, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sun Hits the Sky', 'Supergrass', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('American Music', 'Violent Femmes', 1991, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Again', 'Flyleaf', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tomorrow', 'Silverchair', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Thunderbirds Are Go!', 'Busted', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Different People', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('End It on This', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Happy Now?', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey You', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sixteen', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Climb', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tragic Kingdom', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('World Go ''Round', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Can Do It', 'No Doubt', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('According to You', 'Orianthi', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dearest (I''m So Sorry)', 'Picture Me Broken', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Breaking the Law (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rapid Fire (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Metal Gods (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Grinder (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('United (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Living After Midnight (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('You Don''t Have to Be Old to Be Wise (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Rage (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Steeler (Live)', 'Judas Priest', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Beat It on Down the Line', 'The Grateful Dead', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cumberland Blues', 'The Grateful Dead', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scarlet Begonias', 'The Grateful Dead', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Throwing Stones', 'The Grateful Dead', 1987, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Touch of Grey', 'The Grateful Dead', 1987, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('U.S. Blues', 'The Grateful Dead', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Girl Like You', 'The Smithereens', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Only a Memory', 'The Smithereens', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Great Southern Trendkill', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('War Nerve', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Drag the Waters', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('10''s', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('13 Steps to Nowhere', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Suicide Note Pt. II', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Living Through Me (Hell''s Wrath)', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Floods', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Underground in America', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(Reprise) Sandblasted Skin', 'Pantera', 1996, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Alive', 'P.O.D.', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Trouble Comes Running', 'Spoon', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t You Evah', 'Spoon', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Turn My Camera On', 'Spoon', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Got Nuffin', 'Spoon', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cherry Waves', 'Deftones', 2006, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hole in the Earth', 'Deftones', 2006, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Minerva', 'Deftones', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Great Escape', 'Boys Like Girls', 2006, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Rock Ready', 'Crown of Thorns', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crazy Babies', 'Ozzy Osbourne', 1988, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Diggin'' Me Down', 'Ozzy Osbourne', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Hear You Scream', 'Ozzy Osbourne', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No More Tears', 'Ozzy Osbourne', 1991, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Soul Sucker', 'Ozzy Osbourne', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Can''t Be Tamed', 'Miley Cyrus', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('7 Things', 'Miley Cyrus', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Fly on the Wall', 'Miley Cyrus', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('See You Again', 'Miley Cyrus', 2007, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Start All Over', 'Miley Cyrus', 2007, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Burn It to the Ground', 'Nickelback', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Figured You Out', 'Nickelback', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Never Again', 'Nickelback', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Photograph', 'Nickelback', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rockstar', 'Nickelback', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Afternoon', 'Nickelback', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bad Moon Rising', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Born on the Bayou', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Down on the Corner', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fortunate Son (Original Version)', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Green River', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Heard It Through the Grapevine', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lookin'' Out My Back Door', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Proud Mary', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Run Through the Jungle', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Travelin'' Band', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Up Around the Bend', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Who''ll Stop the Rain', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Get Out', 'The Vines', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('He''s a Rocker', 'The Vines', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Orange Amber', 'The Vines', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Outtathaway', 'The Vines', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ride', 'The Vines', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Future Perfect Tense', 'Sweet Billy Pilgrim', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('New Dark Ages', 'Bad Religion', 2007, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('No Control', 'Bad Religion', 1989, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('1969', 'The Stooges', 1969, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Wanna Be Your Dog', 'The Stooges', 1969, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Fun', 'The Stooges', 1969, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Dios le Pido', 'Juanes', 2002, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fíjate Bien', 'Juanes', 2000, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gotas de Agua Dulce', 'Juanes', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('La Camisa Negra', 'Juanes', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mala Gente', 'Juanes', 2002, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Yerbatero', 'Juanes', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nightmare', 'Avenged Sevenfold', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Seize the Day', 'Avenged Sevenfold', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Scream', 'Avenged Sevenfold', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rapture', 'Blondie', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Jesus Freak', 'DC Talk', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Perfect Crime #2', 'The Decemberists', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Only Want You', 'Eagles of Death Metal', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Saturday Morning', 'EELS', 2003, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Addict', 'Family Force 5', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sturm & Drang', 'KMFDM', 2002, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bulletproof', 'La Roux', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Jesus Built My Hotrod', 'Ministry', 1992, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stigmata', 'Ministry', 1988, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Thieves', 'Ministry', 1989, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Strange Times', 'The Black Keys', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Got Mine', 'The Black Keys', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Your Touch', 'The Black Keys', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Animal', 'Neon Trees', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sins of My Youth', 'Neon Trees', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('1983', 'Neon Trees', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Asylum', 'Disturbed', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Animal', 'Disturbed', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Another Way to Die', 'Disturbed', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mountain Man', 'Crash Kings', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Seasons', 'The Veer Union', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bury Me Alive', 'We Are The Fallen', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('What Was I Thinkin''', 'Dierks Bentley', 2003, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Hell on the Heart', 'Eric Church', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Women', 'Jamey Johnson', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Would You Go With Me', 'Josh Turner', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Days Go By', 'Keith Urban', 2004, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Lookin'' for a Good Time', 'Lady Antebellum', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Rebound', 'Laura Bell Bundy', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Fancy', 'Reba McEntire', 1990, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('It Happens', 'Sugarland', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Drop It Like It''s Hot', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Ridin'' in My Chevy', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Sensual Seduction', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Snoop''s Upside Ya Head', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Tha Shiznit', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('That''s tha Homie', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Who Am I (What''s My Name)?', 'Snoop Dogg', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Stand Up and Shout', 'Dio', 1983, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nirvana', 'Juliana Hatfield', 1992, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Irish Blood, English Heart', 'Morrissey', 2004, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Straight Lines', 'Silverchair', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('This Charming Man', 'The Smiths', 1987, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Writing on the Walls', 'Underoath', 2006, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Is This Love', 'Bob Marley and the Wailers', 1978, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('No Woman, No Cry', 'Bob Marley and the Wailers', 1975, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Could You Be Loved', 'Bob Marley and the Wailers', 1980, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Three Little Birds', 'Bob Marley and the Wailers', 1977, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Buffalo Soldier', 'Bob Marley and the Wailers', 1983, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Stir It Up', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('One Love/People Get Ready', 'Bob Marley and the Wailers', 1977, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('I Shot the Sheriff', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Waiting in Vain', 'Bob Marley and the Wailers', 1977, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Redemption Song', 'Bob Marley and the Wailers', 1980, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Satisfy My Soul', 'Bob Marley and the Wailers', 1978, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Exodus', 'Bob Marley and the Wailers', 1977, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Jamming', 'Bob Marley and the Wailers', 1977, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Among The Living', 'Anthrax', 1987, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I''m the Man', 'Anthrax', 1987, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Indians', 'Anthrax', 1987, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Madhouse (Live)', 'Anthrax', 1987, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Metal Thrashing Mad (Live)', 'Anthrax', 1987, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I''m Not Okay (I Promise)', 'My Chemical Romance', 2004, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to the Black Parade', 'My Chemical Romance', 2006, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Closer to the Edge', '30 Seconds to Mars', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Coffin Nails', 'Atreyu', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Out of Line', 'Buckcherry', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Listen to the Music', 'The Doobie Brothers', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Long Train Runnin''', 'The Doobie Brothers', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Driver 8', 'R.E.M.', 1985, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('It''s the End of the World as We Know It', 'R.E.M.', 1987, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Living Well Is the Best Revenge', 'R.E.M.', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Radio Free Europe', 'R.E.M.', 1983, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Stand', 'R.E.M.', 1988, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Superman', 'R.E.M.', 1986, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('These Days', 'R.E.M.', 1986, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('What''s the Frequency, Kenneth?', 'R.E.M.', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Children of the Revolution', 'T. Rex', 1973, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Cosmic Dancer', 'T. Rex', 1971, 'Glam', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Jeepster', 'T. Rex', 1971, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Purple Haze', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Manic Depression', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Joe (Live)', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love or Confusion', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('May This Be Love', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Wind Cries Mary', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fire (Live)', 'Jimi Hendrix', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('3rd Stone from the Sun', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Foxey Lady', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Are You Experienced?', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stone Free', 'Jimi Hendrix', 2010, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Highway Chile', 'The Jimi Hendrix Experience', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Big Empty', 'Stone Temple Pilots', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Crackerman', 'Stone Temple Pilots', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Creep', 'Stone Temple Pilots', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Dead & Bloated', 'Stone Temple Pilots', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Huckleberry Crumble', 'Stone Temple Pilots', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bleed American', 'Jimmy Eat World', 2001, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Best Theory', 'Jimmy Eat World', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pain', 'Jimmy Eat World', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock Band Network Megamix 01', 'Various Artists', 2010, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Back in Black (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Dirty Deeds Done Dirt Cheap (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Fire Your Guns (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('For Those About to Rock (We Salute You) (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Heatseeker (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Hell Ain''t a Bad Place to Be (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Hells Bells (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('High Voltage (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Highway to Hell (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Jailbreak (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Let There Be Rock (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Moneytalks (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Shoot to Thrill (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('T.N.T. (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('The Jack (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Thunderstruck (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Whole Lotta Rosie (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('You Shook Me All Night Long (Live)', 'AC/DC', 1992, 'Classic Rock', false, true, false, ARRAY['Rock Band DLC']),
('Brain Stew / Jaded', 'Green Day', 1995, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Good Riddance (Time of Your Life)', 'Green Day', 1997, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Warning', 'Green Day', 2000, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Minority', 'Green Day', 2000, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Geek Stink Breath', 'Green Day', 1995, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Nice Guys Finish Last', 'Green Day', 1997, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Hitchin'' a Ride', 'Green Day', 1997, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Song of the Century', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('21st Century Breakdown', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Before the Lobotomy', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Last Night on Earth', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Peacemaker', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Murder City', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('¿Viva la Gloria? (Little Girl)', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Restless Heart Syndrome', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Horseshoes and Handgrenades', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('The Static Age', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('American Eulogy', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('See the Light', 'Green Day', 2009, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('American Idiot', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Jesus of Suburbia', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Holiday', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Boulevard of Broken Dreams', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Are We the Waiting / St. Jimmy', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Give Me Novacaine / She''s a Rebel', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Extraordinary Girl', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Letterbomb', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Wake Me Up When September Ends', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Homecoming', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Whatsername', 'Green Day', 2004, 'Rock', false, true, false, ARRAY['Rock Band DLC']),
('Burnout', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Having a Blast', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Chump', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Longview', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Welcome to Paradise', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Pulling Teeth', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Basket Case', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('She', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Sassafras Roots', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('When I Come Around', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Coming Clean', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Emenius Sleepus', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('In the End', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('F.O.D.', 'Green Day', 1994, 'Punk', false, true, false, ARRAY['Rock Band DLC']),
('Single White Female', 'Chely Wright', 1999, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Giddy On Up', 'Laura Bell Bundy', 2010, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('The Night The Lights Went Out in Georgia', 'Reba McEntire', 1991, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Party for Two (With Billy Currington)', 'Shania Twain', 2004, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Settlin''', 'Sugarland', 2006, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('That''s How Country Boys Roll', 'Billy Currington', 2008, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Awful Beautiful Life', 'Darryl Worley', 2004, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Man of Me', 'Gary Allan', 2001, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('TWANG', 'George Strait', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Ring of Fire', 'Johnny Cash', 1963, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Backwoods', 'Justin Moore', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Alright', 'Darius Rucker', 2008, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Sideways', 'Dierks Bentley', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Kiss a Girl', 'Keith Urban', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Perfect Day', 'Lady Antebellum', 2010, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Rain Is a Good Thing', 'Luke Bryan', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Mama Tried', 'Merle Haggard', 1968, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Ride', 'Trace Adkins', 2006, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Intentional Heartache', 'Dwight Yoakam', 2005, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Crazy Town', 'Jason Aldean', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('Summer Nights', 'Rascal Flatts', 2009, 'Country', false, true, false, ARRAY['Rock Band DLC']),
('A Drug Against War', 'KMFDM', 1993, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Angel Lust', 'Fake Shark – Real Zombie!', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Another California Song', 'Zack Wilson', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Arigato', 'Gandhi', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Australia', 'The Shins', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Backyard Buildyard', 'Steve and Lindley Band', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Battles and Brotherhood', '3 Inches of Blood', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Buried Cold', 'Rose of Jericho', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burn It Down', 'Five Finger Death Punch', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('California', 'The Kimberly Trip', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Can I Stay', 'Stephanie Hatfield and Hot Mess', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cease and Desist', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Children of December', 'The Slip', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Creepy Doll', 'Jonathan Coulton', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crushed Beyond Dust', 'Skeletonwitch', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Day of Mourning', 'Despised Icon', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Disengage', 'Suicide Silence', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Let Me Down (Slowly)', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dove Nets', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Drunken Lullabies (Live)', 'Flogging Molly', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('End Quote', 'Full-Source', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Fade Away', 'Of Last Resort', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Far Away from Heaven', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fight Back', 'Ron Wasserman', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('For the Love of God (Live)', 'Steve Vai', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fortune', 'Kristin Hersh', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Get the Hell Out of Here', 'Steve Vai', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Give', 'The Cold Goodnight', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Goth Girls', 'MC Frontalot', 2005, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Grumpytown', 'Speck', 2007, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('He Sleeps in a Grove', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heimdalsgate Like a Promethean Curse', 'of Montreal', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Homosuperior', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Horses in Heaven', 'Fake Shark – Real Zombie!', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('How We''d Look on Paper', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hyperbole', 'Glass Hammer', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Icarus'' Song', 'Furly', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('If Not Now When', 'Color Theory', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('If Trucks Drank Beer', 'Error 404 feat. CJ Watson', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Ikea', 'Jonathan Coulton', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('In Memories', 'Giant Target', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Inside Out', 'Nick Gallant', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('It''s Good', 'The Humans', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('It''s Not You, It''s Everyone', 'Full-Source', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Juke Joint Jezebel', 'KMFDM', 1995, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Kick Some Ass ''09', 'Stroke 9', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lady in a Blue Dress', 'Senses Fail', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lemon Juice', 'Scratching the Itch', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lilith in Libra', 'You Shriek', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Limousine', 'Stars of Boulevard', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Liquid Smog (StompBox Remix)', 'WaveGroup feat. Becca Neun', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Little Black Backpack ''09', 'Stroke 9', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Liverpool Judies', 'The Fisticuffs', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Love During Wartime', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mechanical Love', 'In This Moment', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Megatron', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mississippi Kite', 'Kristin Hersh', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Moonboy', 'The Dirty Love Band', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nancy Drew', 'Pink Flag', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('No Direction', 'Longwave', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('No Heroes', 'You Shriek', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Not My Fault', 'Ultra Saturday', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ox', 'Zack Wilson', 2010, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Paper Valentines', 'James William Roy', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Parhelia', 'Heaven Ablaze', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Persistence of Vision', 'Matter in the Medium', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Race The Hourglass', 'Audio Fiction', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Red Sky At Morn', 'Full-Source', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Requiem for a Dying Song', 'Flogging Molly', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Rip''er', 'Lead the Dead', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('River of Tuoni', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Running for the Razors', 'Fake Shark – Real Zombie!', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rx', 'Wounded Soul', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sequestered in Memphis', 'The Hold Steady', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sestri Levante', 'Fake Shark – Real Zombie!', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sick', 'Bif Naked', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Signs', 'Giant Target', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Sissyfuss', 'Surprise Me Mr. Davis', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sleep On', 'Glass Hammer', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Stand for Something', 'Skindred', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Still There', 'Bojibian', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Superhero!', 'Ultra Saturday', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Survive', 'Lacuna Coil', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tadpole Search and Rescue', 'Chaunce DeLeon and the Fountain of Choof', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Talk About', 'Dear and the Headlights', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Talk Them Down', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Teeth, Face, Outerspace', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Attitude Song', 'Steve Vai', 1984, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Buddy Disease', 'Scratching the Itch', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Complexity of Light', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The Future Soon', 'Jonathan Coulton', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Heist', 'DnA''s Evolution', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tongue Twister Typo', 'Blackmarket', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Top Back', 'Alias Unknown', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Tricky Girl', 'The Main Drag', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Turn Yourself Around', 'Nick Gallant', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('VP of Booty Reports', 'Speck', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Watch It All Go Down', 'Foreword', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Are the Best', 'C&O', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Whatever Is Wrong With You', 'Marillion', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('What''s Your Favorite Dinosaur?', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Got That', 'The Everybody', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('You''re My Everything', 'Scratching the Itch', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Bleeder', 'Alchemilla', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cali Girl', 'Ballyhoo!', 2006, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Code Monkey', 'Jonathan Coulton', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gave It Up', 'Pollyn', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Genius', 'The B.O.L.T.', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Makeup/Breakup (Original Version)', 'Super Gravity', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Minnesota', 'Voodoo Pharmacology', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Packet Flier', 'Terrorhorse', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stegosaurus Song', 'Eric Harm', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('White Heat', 'Cetan Clawson and the Soul Side', 2006, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Approach the Podium', 'Winds of Plague', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Demon Woman', 'Flight of the Conchords', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Roll Over', 'Uniform Motion', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('So Says I', 'The Shins', 2003, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Push Me', 'The Carsitters', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shiny Dark Bar', 'James William Roy', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do You Feel Like Breaking Up?', 'Mark Mallman', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mordecai', 'Between the Buried and Me', 2003, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Stick Stickly', 'Attack Attack!', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Africa', 'Quartered', 2007, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Car Windows', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Descend Into the Eternal Pits of Possession', 'The Project Hate MCMXCIX', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Life Unworthy of Life', 'Warpath', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Love and the Triumph Of', 'Broadcast', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Second Best Friend', 'The Nebraska Sailing Authority', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Most Beautiful Girl (In the Room)', 'Flight of the Conchords', 2008, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Whatever Happened to You', 'Cate Sparks', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Day to Day', 'Eulogies', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Destructive Device', 'Mindflow', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Moonshine Hollar', 'Zack Wilson', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Still Alive', 'World Minus One', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('What a Trip', 'Analogue Revolution feat. First Be', 2008, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Dirty South Rock', 'Hyro da Hero', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('One Bad Man', 'Midnight Riders', 2009, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Battle Royale', 'The Word Alive', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Elements', 'Texas in July', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('My New Favorite Disaster', 'megaphone', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nothing There', 'Oliver Pride', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rise', 'Solarcade', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Mob Goes Wild', 'Clutch', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You''re A Wolf', 'Sea Wolf', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('50,000 Unstoppable Watts', 'Clutch', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dragonfly (Symbion Project Remix)', 'Universal Hall Pass', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('We Are Not Anonymous', 'Unearth', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Business Time', 'Flight of the Conchords', 2008, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Dirty King', 'The Cliks', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Made of Wax, Larry, What Are You Made Of?', 'A Day to Remember', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Midnight Ride', 'Midnight Riders', 2009, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Semi-Charmed Life ''09', 'Third Eye Blind', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bodies', 'Drowning Pool', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Collapsing', 'Demon Hunter', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Days Without', 'All That Remains', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('One Step Further', 'MxPx', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Being Here', 'The Stills', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dance With Me', 'Stewart', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Remedy', 'Seether', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Energy', 'The Apples in Stereo', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('First We Feast, Then We Felony', 'Circus Circus', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hot Sexy Girls', 'Joe Sibol', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Know What I Am', 'Band of Skulls', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Alive', 'Kid Beyond', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Past Lives', 'The Bronx', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Taking Apart a Gigantic Machine', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Too Hot to Handle', 'Carl Douglas', 2008, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Under Water I Drown', 'Edge', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Anything', 'Kristin Dare', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do Not Disturb (Tell Me How Bad)', 'Let''s Get It', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gravitate', 'megaphone', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Roll the Dice', 'Damone', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scavengers of the Damned', 'Aiden', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Upstream', 'Cory Wong', 2009, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Hook, Line, and Sinner', 'Texas in July', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Think That''s OK', 'Josh Freese', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Thousand Nights', 'Mile Marker Zero', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Not Your Enemy', 'megaphone', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Little Faster', 'There for Tomorrow', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Gasoline', 'The Bouncing Souls', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Synthesized', 'Symbion Project', 2003, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Trash Candy', 'Tijuana Sweetheart', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Big Square', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('When I Get Home, You''re So Dead', 'Mayday Parade', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Never Let You Go ''09', 'Third Eye Blind', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Perfect World', 'Moving Picture Show', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Step Up (I''m on It)', 'Maylene and the Sons of Disaster', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Eveready', 'Modern Skirts', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scream Ceremony', 'Order of the Crimson Wizard', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unstoppable', 'White Line Allstars', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burning Rome', 'Minnesota Sex Junkies', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful', 'Andy Kirk', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sound of the Redeemed', 'Jonathan Lee', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Young Bloods', 'The Bronx', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Home', 'Fear Without Reason', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Rearview Mirror', 'Zack Wilson', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sending Signals', 'Evergreen Terrace', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Where the Light Was Born (Thule Ultima a Sole Nomen Habens)', 'Bornholm', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Where We''re Goin', 'The Japanese Frog', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('1348', 'Umphrey''s McGee', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('All Eyes on Me', 'The Carsitters', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('All My Friends Are Crazy', '500 Miles to Memphis', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Doomsday Party', 'Sybreed', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Midnight Daydreams', 'No Crossing', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Forever in Your Hands', 'All That Remains', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gravity (Don''t Let Me Go)', 'Jon Black & the Winter Hearts', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wings of Infinity', 'C&O', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bow Down', 'Chrome Coma', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chalk Lines', 'Division Day', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Drag Me Away', 'Aminal', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Eden was a Garden', 'Roman Candle', 2009, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Let the Games Begin', 'Anarbor', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Motorcide', 'Man Parts', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Rude Awakening', 'Squeezebox', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Price', 'Dappled Cities', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Am Legion', 'bibleblack', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Last Mistake', 'RED9', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Girl at the Video Game Store', 'Parry Gripp', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Numb', 'Aittala', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('One Step Behind', 'A Hero Next Door', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('You Stay. I Go. No Following.', 'Look Mexico', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Close Your Eyes', 'Jonathan Lee', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Elisheva, I Love You', 'Junius', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blink', 'Father Octopus', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bringing Love to the Party', 'Steele & Britton feat. Taryn Murphy', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Caught', 'Steele & Holden feat. Darren Holden', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death Comes (The Wedding Night)', 'Inkubus Sukkubus', 2008, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Frontier Factory', 'Freen in Green', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Goodnight Technologist', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Henchmen Ride', 'Testament', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Indigo Friends', 'Reverend Horton Heat', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Jumper ''09', 'Third Eye Blind', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Take Control', 'The New Regime', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Are the Nightmare', 'Arsis', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('HTML Rulez D00d', 'The Devil Wears Prada', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('In Memory', 'Excruciating Thoughts', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('NDE', 'Blow Up Hollywood', 2004, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('American Dream', 'Silverstein', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Is the Only Thing', 'Andy Kirk', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dead to the World', 'The Fire Violets', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Delaware Are You? I Don''t Know Alaska.', 'Safari So Good', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Dogs Can Grow Beards All Over', 'The Devil Wears Prada', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Exploited & Exposed', 'Symbion Project', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Homeward Bound', 'Tumbledown', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Plans & Reveries', 'Black Gold', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Undone', 'All That Remains', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dethroned', 'Death Angel', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('End of This', 'Scratching the Itch', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Even Seconds', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heads or Tails? Real or Not', 'Emarosa', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Montana', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Paralyzer', 'Finger Eleven', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('People Like You', 'Forever from Now', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Shot at the Title', 'Your Horrible Smile', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Swine Houses', 'The Main Drag', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Funeral', 'Band of Horses', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chelsea', 'The Summer Set', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death Quota for Purification', 'The Myriad Burial', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Doomed', '8 Inch Betsy', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Radiator', 'Family Force 5', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Crying Machine (Live)', 'Steve Vai', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unfurling a Darkened Gospel', 'Job for a Cowboy', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Where Were You?', 'Every Avenue', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('You''ve Got Someone', 'Blue News', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Beauty Queen', 'The Fury', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dr. Doom', 'The Acacia Strain', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Inheritance', 'Single White Infidel', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Last Train to Awesometown', 'Parry Gripp', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Redemption', 'Andy Timmons', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Take It All', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Automatic Doors', 'A''tris', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chemical Infatuation', 'Like A Storm', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Feel Like That Anymore', 'Johnny Cooper', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hungarian Dance No. 5 (Brahms)', 'Paul Henry Smith & the Fauxharmonic Orchestra', 2010, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Light of Day', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Night on Bald Mountain (Mussorgsky)', 'Paul Henry Smith & the Fauxharmonic Orchestra', 2010, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Rock Your Socks Off', 'Midnight Ocelot', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Swallow the Razor', 'Bang Camaro', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wrong Side of the Sky', 'Rose of Jericho', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Everyone I Know is an Alcoholic', 'Robby Suavé', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Flight of the Bumblebee (Rimsky-Korsakov)', 'Paul Henry Smith & the Fauxharmonic Orchestra', 2009, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Knifeman', 'The Bronx', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('You''re Not Alone - Rock Mix', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('India', 'Circus Circus', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Great Plains', 'Scale the Summit', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Til I''m Gone', 'Kristin Dare', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Walls', 'All Time Low', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('We''re Not Getting Any Younger', 'Color Theory', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Bra Off Party On', 'Thunderdikk', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death Metal Guys', 'Reverend Horton Heat', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('It''s Not Paranoia If They''re Shooting Live Bullets', 'Sadaharu', 2003, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Now Demolition', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Paper Dolls', 'Ballyhoo!', 2009, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Tastes Like Kevin Bacon', 'iwrestledabearonce', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Valkyries', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Eency Weency Spider', 'CJ', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Santa Fe (RB2 Version)', 'Blackberry River Band', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Shape 3', 'Farther Snake', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sunday Suit', 'Connor Christian and Southern Gothic', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('By Yourself', 'The Knew', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Five More Minutes', 'Counterfeit Pennies', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Is There a Ghost', 'Band of Horses', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('You''re an Egg! (Evolution)', 'Windtunnel Syndrome', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Fat Kid', 'Nothing More', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Satellite (Live)', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Dance Floor', 'The Apples in Stereo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fight to Kill', 'Holy Grail', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Footprints', 'John Garrison', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Mr. Sun', 'CJ', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Oye Vaya', 'Earl Greyhound', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay Up With Me', 'After the Fall', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You All Everybody', 'Drive Shaft', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dharma Lady', 'Geronimo Jackson', 2010, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('How We Roll', 'Plushgun', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('The Way You Move', 'The Audition', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('We Are the One', 'Anti-Flag', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('American Hero', 'Ron Wasserman', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Disappear in You', 'Clandestine', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Freakshow', 'HourCast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hail Destroyer', 'Cancer Bats', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Live For Today', 'Sullivan DeMott', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shake', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Sorceress', 'Cancer Bats', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This F***ing Job', 'Drive-By Truckers', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('When We Fall', 'Gentlemen At Arms', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Blow at High Dough', 'The Tragically Hip', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dead Wrong', 'Cancer Bats', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Haunt My Mind', 'The New Regime', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Higher', 'Creed', 1999, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Riot Act', 'Exodus', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Smile (Live)', 'The Gufs', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Surprise', 'Verse Versus Chorus', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Walking Away', 'Made Avail', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Fake It', 'Seether', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Soldier from the Surface', 'Windtunnel Syndrome', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Tap Dancing In A Minefield', 'The New Regime', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Daughter', 'The Reverend H Chronicles', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Wanna Be An Alien''s Pet', 'Alien Downlink', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Friday the 13th', 'The Riptides', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Molten Death', 'Man Parts', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Tree Village', 'Dance Gavin Dance', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Young', 'Twintapes', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('America Underwater', 'LoveHateHero', 2009, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Anybody Else', 'Audible Mainframe', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Bang Camaro', 'Bang Camaro', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cheating, Lying, Stealing', 'Bang on a Can All-Stars / David Lang', 2002, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Circles', 'Something Opus', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Detroit City', 'Drivin'' N'' Cryin''', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fire Away', 'Kill the Alarm', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I See Georgia', 'Drivin'' N'' Cryin''', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Coming Home', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Ice Cold', 'Audible Mainframe', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Down', 'Drivin'' N'' Cryin''', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nightlife Commando', 'Bang Camaro', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('ShadowBang (Head)', 'Bang on a Can All-Stars / Evan Ziporyn', 2003, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Shop Vac', 'Jonathan Coulton', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Yo Shakespeare', 'Bang on a Can All-Stars / Michael Gordon', 1992, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('An Exercise in Futility', 'Single White Infidel', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Beethoven - Symphony No. 9 - Scherzo', 'Paul Henry Smith & the Fauxharmonic Orchestra', 2010, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Infected Nation', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rise Above This', 'Seether', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scared to Death', 'Cancer Bats', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Serial Killer', 'Damone', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Travelin'' Freak Show', 'Joe Bouchard', 2009, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wake Up', 'Me Talk Pretty', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dream About the Future', 'The Apples in Stereo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hitch Up (I''m So Stupid)', 'Jesus Candy', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hot Stuff', 'Scott Attrill', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Painted', 'Zoo Seven', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bled To Be Free (The Operation)', 'Rx Bandits', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bleed', 'Meshuggah', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bright Side of Life', 'Rebelution', 2009, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Bury You Slowly', 'Made Avail', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Cookie Monster', 'XTT', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Crash Years', 'The New Pornographers', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crooked Strings', 'Kiev', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Janie', 'The Raspberry Ants', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mandelbrot Set', 'Jonathan Coulton', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Six Is One', 'Free Electric State', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The World Is a Thorn', 'Demon Hunter', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Three Words', 'Todd Thibaud', 2005, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Turnpike Ghost', 'Steel Train', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('A Better Forever', 'SexTon', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Engine', 'Wargasm', 1995, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Lesser Man', 'SOiL', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ramp Truck', 'Freen in Green', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Run', 'Charmaine', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Me You See', 'Spiral Trance', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Believing', 'Bang on a Can All-Stars / Julia Wolfe', 2001, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Deliver Us', 'Andy Timmons', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nosophoros', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Touche, Miss Indenial', 'Jamestown Story', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Buster Voodoo', 'Rodrigo y Gabriela', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Divine', 'XTT', 2010, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Outta the Band', 'My First Earthquake', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);