-- Part 6
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Sometimes', 'Dreamgirl', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Future Blind', 'The Lighthouse and the Whaler', 2018, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Poison Pill', 'Silverstein', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Shapeshifter', 'The Bervet', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Baker Street', 'Gerry Rafferty', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Our Love Will Still Be There', 'The Troggs', 1966, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Goodbye Yellow Brick Road', 'Elton John', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Send Me On My Way', 'Rusted Root', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wherever You Will Go', 'The Calling', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Thank You', 'Dido', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('A Hard Day''s Night', 'The Beatles', 1964, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('And Your Bird Can Sing', 'The Beatles', 1966, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Back in the U.S.S.R.', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Birthday', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Boys', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Can''t Buy Me Love', 'The Beatles', 1964, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Come Together', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Day Tripper', 'The Beatles', 1965, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Dear Prudence', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Dig a Pony', 'The Beatles', 1970, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Do You Want to Know a Secret', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Don''t Let Me Down', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Drive My Car', 'The Beatles', 1965, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Eight Days a Week', 'The Beatles', 1964, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Get Back', 'The Beatles', 1970, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Getting Better', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Good Morning Good Morning', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Hello, Goodbye', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Helter Skelter', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Here Comes the Sun', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Hey Bulldog', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Am the Walrus', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Feel Fine', 'The Beatles', 1964, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Me Mine', 'The Beatles', 1970, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Saw Her Standing There', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Wanna Be Your Man', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Want to Hold Your Hand', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Want You (She''s So Heavy)', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('If I Needed Someone', 'The Beatles', 1965, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I''m Looking Through You', 'The Beatles', 1965, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I''ve Got a Feeling', 'The Beatles', 1970, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Lucy in the Sky with Diamonds', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Octopus''s Garden', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Paperback Writer', 'The Beatles', 1966, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Revolution', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Sgt. Pepper''s Lonely Hearts Club Band / With a Little Help from My Friends', 'The Beatles', 1967, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Something', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Taxman', 'The Beatles', 1966, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('The End', 'The Beatles', 1969, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Ticket to Ride', 'The Beatles', 1965, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Twist and Shout', 'The Beatles', 1963, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('While My Guitar Gently Weeps', 'The Beatles', 1968, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Within You Without You / Tomorrow Never Knows', 'The Beatles', 2006, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Yellow Submarine', 'The Beatles', 1966, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('All You Need Is Love', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Maxwell''s Silver Hammer', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Oh! Darling', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Because', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('You Never Give Me Your Money', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Sun King / Mean Mr. Mustard', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Polythene Pam / She Came in Through the Bathroom Window', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Golden Slumbers / Carry That Weight / The End', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Her Majesty', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Abbey Road Medley', 'The Beatles', 1969, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Fixing a Hole', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('She''s Leaving Home', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Being for the Benefit of Mr. Kite!', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Within You Without You', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('When I''m Sixty-Four', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Lovely Rita', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Sgt. Pepper''s Lonely Hearts Club Band (Reprise)', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('A Day in the Life', 'The Beatles', 1967, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Norwegian Wood (This Bird Has Flown)', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('You Won''t See Me', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Nowhere Man', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Think for Yourself', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('The Word', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Michelle', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('What Goes On', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Girl', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('In My Life', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Wait', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Run for Your Life', 'The Beatles', 1965, 'N/A', false, true, true, ARRAY['Rock Band DLC']),
('Lights Out', 'AudioDamn!', 2016, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Casual Party', 'Band Of Horses', 2016, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Church Bells', 'Carrie Underwood', 2016, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Birds', 'Coldplay', 2015, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Maps', 'Maroon 5', 2014, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('Quitter', 'The Starting Line', 2016, 'N/A', false, true, false, ARRAY['Rock Band DLC']),
('I Am Alive', 'Twin Atlantic', 2016, 'N/A', false, true, false, ARRAY['Rock Band DLC']);