-- Part 4
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('On the Backs of Angels', 'Dream Theater', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Ghost of Perdition', 'Opeth', 2005, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('In Waves', 'Trivium', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('We Built This City', 'Starship', 1985, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Seven Seas of Rhye', 'Queen', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stone Cold Crazy', 'Queen', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m in Love With My Car', 'Queen', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('You''re My Best Friend', 'Queen', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Long Away', 'Queen', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bicycle Race', 'Queen', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Stop Me Now', 'Queen', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Radio Ga Ga', 'Queen', 1984, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Show Must Go On', 'Queen', 1991, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fly By Night', 'Rush', 1975, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Caravan', 'Rush', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The Spirit of Radio (Live)', 'Rush', 1980, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Rebel Love Song', 'Black Veil Brides', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Warrior''s Call', 'Volbeat', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Long Hot Summer Night', 'The Jimi Hendrix Experience', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gypsy Eyes', 'The Jimi Hendrix Experience', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('All Along the Watchtower', 'The Jimi Hendrix Experience', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Voodoo Child (Slight Return) (Live)', 'Jimi Hendrix', 1969, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dolly Dagger', 'Jimi Hendrix', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freedom', 'Jimi Hendrix', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Angel', 'Jimi Hendrix', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Make Me Feel...', 'Cobra Starship (ft. Sabi)', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Stereo Hearts', 'Gym Class Heroes (ft. Adam Levine)', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('I Write Sins Not Tragedies', 'Panic! at the Disco', 2005, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Pressure', 'Paramore', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Panic', 'Sublime with Rome', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Billionaire', 'Travie McCoy (ft. Bruno Mars)', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('2112', 'Rush', 1976, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('2112: Overture, The Temples of Syrinx', 'Rush', 1976, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('2112: Discovery, Presentation', 'Rush', 1976, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('2112: Oracle: The Dream, Soliloquy, Grand Finale', 'Rush', 1976, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Private Eyes', 'Hall & Oates', 1981, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Can''t Go for That (No Can Do)', 'Hall & Oates', 1981, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Maneater', 'Hall & Oates', 1982, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Free Ride', 'The Edgar Winter Group', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freak on a Leash', 'Korn', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Falling Away From Me', 'Korn', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lodi', 'Creedence Clearwater Revival', 1969, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Have You Ever Seen the Rain?', 'Creedence Clearwater Revival', 1970, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Susie Q', 'Creedence Clearwater Revival', 1968, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Still Waiting', 'Sum 41', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Head Over Heels', 'Tears for Fears', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Everything Zen', 'Bush', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Comedown', 'Bush', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Machinehead', 'Bush', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Alone', 'Heart', 1987, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('To Be With You', 'Mr. Big', 1991, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Every Rose Has Its Thorn', 'Poison', 1988, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Never Gonna Give You Up', 'Rick Astley', 1987, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('A Tout le Monde', 'Megadeth', 1994, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Public Enemy No. 1', 'Megadeth', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Do You Believe in Love', 'Huey Lewis and The News', 1982, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Heart of Rock & Roll', 'Huey Lewis and The News', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Want a New Drug', 'Huey Lewis and The News', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Santa Monica', 'Everclear', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Anthem', 'Good Charlotte', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Curl of the Burl', 'Mastodon', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Good Life', 'Three Days Grace', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Hate Everything About You', 'Three Days Grace', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pain', 'Three Days Grace', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Down Under', 'Men at Work', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Overkill', 'Men at Work', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Smooth', 'Santana (ft. Rob Thomas)', 1999, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Second Chance', 'Shinedown', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Crow and the Butterfly', 'Shinedown', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bully', 'Shinedown', 2012, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Everybody''s Fool', 'Evanescence', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lithium', 'Evanescence', 2006, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('What You Want', 'Evanescence', 2011, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('South of Heaven', 'Slayer', 1988, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Seasons in the Abyss', 'Slayer', 1990, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Get the Party Started', 'P!nk', 2001, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Funhouse', 'P!nk', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Please Don''t Leave Me', 'P!nk', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sober', 'P!nk', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nobody''s Fool', 'Cinderella', 1986, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Know What You Got (Till It''s Gone)', 'Cinderella', 1988, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Shelter Me', 'Cinderella', 1990, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Two Tickets to Paradise', 'Eddie Money', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Only One', 'Yellowcard', 2003, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Drops of Jupiter', 'Train', 2001, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bombtrack', 'Rage Against the Machine', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sleep Now in the Fire', 'Rage Against the Machine', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ignorance', 'Paramore', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Brick by Boring Brick', 'Paramore', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Only Exception', 'Paramore', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Phantom of the Opera', 'Iron Maiden', 1980, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Prisoner', 'Iron Maiden', 1982, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flight of Icarus', 'Iron Maiden', 1983, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rime of the Ancient Mariner', 'Iron Maiden', 1984, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Infinite Dreams', 'Iron Maiden', 1988, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Seventh Son of a Seventh Son', 'Iron Maiden', 1988, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tears Don''t Fall', 'Bullet for My Valentine', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Scream Aim Fire', 'Bullet for My Valentine', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Your Betrayal', 'Bullet for My Valentine', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Teen Angst (What the World Needs Now)', 'Cracker', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Dog Days Are Over', 'Florence + the Machine', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Power and the Passion', 'Midnight Oil', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Drive', 'Incubus', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Adventure', 'Angels & Airwaves', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Fireflies', 'Owl City', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('In My Head', 'Queens of the Stone Age', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Before He Cheats', 'Carrie Underwood', 2005, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Cowboy Casanova', 'Carrie Underwood', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Good Girl', 'Carrie Underwood', 2012, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Gonzo', 'All-American Rejects', 2012, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Happy?', 'Mudvayne', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Satellite', 'Rise Against', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('It''s Not Over', 'Daughtry', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Surprise', 'Daughtry', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crawling Back to You', 'Daughtry', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Shack', 'The B-52''s', 1989, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Not Again', 'Staind', 2011, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('My Body', 'Young the Giant', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Helena Beat', 'Foster the People', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Stop (Color on the Walls)', 'Foster the People', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Under Cover of Darkness', 'The Strokes', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The End of Heartache', 'Killswitch Engage', 2004, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Arms of Sorrow', 'Killswitch Engage', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Starting Over', 'Killswitch Engage', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(I Just) Died in Your Arms', 'Cutting Crew', 1986, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Still of the Night', 'Whitesnake', 1987, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Crawling in the Dark', 'Hoobastank', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Want to Know What Love Is', 'Foreigner', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Waiting for a Girl Like You', 'Foreigner', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Amaranth', 'Nightwish', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tighten Up', 'The Black Keys', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Howlin'' for You', 'The Black Keys', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lonely Boy', 'The Black Keys', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('One Week', 'Barenaked Ladies', 1998, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('These Days', 'Foo Fighters', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Death on Two Legs (Dedicated to...)', 'Queen', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Breaking the Habit', 'Linkin Park', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Shadow of the Day', 'Linkin Park', 2007, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('New Divide', 'Linkin Park', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Burn It Down', 'Linkin Park', 2012, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bent', 'Matchbox Twenty', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('How Far We''ve Come', 'Matchbox Twenty', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('She''s So Mean', 'Matchbox Twenty', 2012, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Days Go By', 'The Offspring', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Why Can''t We Be Friends?', 'Smash Mouth', 1997, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Can’t Get Enough of You Baby', 'Smash Mouth', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Oh Love', 'Green Day', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Down', '311', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Disaster', '311', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Amber', '311', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Stroke', 'Billy Squier', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Everybody Wants You', 'Billy Squier', 1982, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come On Eileen', 'Save Ferris', 1997, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('All I Wanna Do', 'Sheryl Crow', 1993, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Animal I Have Become', 'Three Days Grace', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Make Me Smile', 'Chicago', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Feelin'' Stronger Every Day', 'Chicago', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('If You Leave Me Now', 'Chicago', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('What I Got', 'Sublime', 1996, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Wrong Way', 'Sublime', 1996, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Santeria', 'Sublime', 1996, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Ants Marching', 'Dave Matthews Band', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mercy', 'Dave Matthews Band', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('So Much to Say', 'Dave Matthews Band', 1996, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Alright', 'Kenny Loggins', 1980, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Footloose', 'Kenny Loggins', 1984, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Weight (Live)', 'The Band', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cold', 'Crossfade', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cry Thunder', 'DragonForce', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Melt With You', 'Modern English', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Closer', 'Nine Inch Nails', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Call Me Maybe', 'Carly Rae Jepsen', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Sex and Candy', 'Marcy Playground', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('She Talks to Angels', 'The Black Crowes', 1990, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Remedy', 'The Black Crowes', 1992, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sometimes Salvation', 'The Black Crowes', 1992, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Away', 'Toadies', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Tyler', 'Toadies', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('The Bitch Is Back', 'Elton John', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Let the Sun Go Down on Me', 'Elton John', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Still Standing', 'Elton John', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Helena', 'My Chemical Romance', 2004, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Sing', 'My Chemical Romance', 2010, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Party Hard', 'Andrew W.K.', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tonight Tonight', 'Hot Chelle Rae', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('We Are Young', 'fun. ft. Janelle Monáe', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Raise Your Glass', 'P!nk', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pumped Up Kicks', 'Foster the People', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Moves Like Jagger', 'Maroon 5 ft. Christina Aguilera', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''ve Done Everything for You', 'Rick Springfield', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Talk to Strangers', 'Rick Springfield', 1982, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stronger (What Doesn''t Kill You)', 'Kelly Clarkson', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Walk This Way', 'Aerosmith', 1975, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sweet Emotion', 'Aerosmith', 1975, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dream On (Live)', 'Aerosmith', 1973, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Legendary Child', 'Aerosmith', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lover Alot', 'Aerosmith', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Back in the Saddle', 'Aerosmith', 1976, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Wicker Man', 'Iron Maiden', 2000, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Once Bitten, Twice Shy', 'Great White', 1989, 'Glam', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('So Far Away', 'Avenged Sevenfold', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('More Than Words', 'Extreme', 1990, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Hurts', 'Nazareth', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Glory of Love', 'Peter Cetera', 1986, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Keep On Loving You', 'REO Speedwagon', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tainted Love', 'Soft Cell', 1981, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Shine', 'Collective Soul', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('A Little Less Sixteen Candles, A Little More Touch Me', 'Fall Out Boy', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Got You (Where I Want You)', 'The Flys', 1998, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Silent Lucidity', 'Queensrÿche', 1990, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('It''s Been Awhile', 'Staind', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('So Far Away', 'Staind', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Kids in the Street', 'The All-American Rejects', 2012, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Always', 'Blink-182', 2003, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Weird Science', 'Oingo Boingo', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Rosanna', 'Toto', 1982, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Diamond Eyes (Boom-Lay Boom-Lay Boom)', 'Shinedown', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Jungle Boogie', 'Kool and the Gang', 1973, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Shout', 'Tears for Fears', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Send the Pain Below', 'Chevelle', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Red', 'Chevelle', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Face to the Floor', 'Chevelle', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('American Pie', 'Don McLean', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('R U Mine?', 'Arctic Monkeys', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shepherd of Fire', 'Avenged Sevenfold', 2013, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Something from Nothing', 'Foo Fighters', 2014, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rize of the Fenix', 'Tenacious D', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Back to the Shack', 'Weezer', 2014, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Still Believe', 'Frank Turner', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blue (Da Ba Dee)', 'Eiffel 65', 1999, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Airbrushed', 'Anamanaguchi', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('28 Days', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Andromeda', 'Bluefusion', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Happy People', 'Big Kenny', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Fight For Greatness', 'Bloom', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Slaughterhouse, Obituaries and a Love Story', 'Arcadia', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('You Will Leave a Mark', 'A Silent Film', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Audience and Audio', 'Twin Atlantic', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Money', 'Madlife', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Deception - Concealing Fate Part Two', 'TesseracT', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Forest', 'Verax', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Spaghetti Cat (I Weep For You)', 'Parry Gripp', 2008, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Find Beauty', 'Rose of Jericho', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Forest for the Trees', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Lost Soul', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Payback (Come On)', 'BioShaft', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Thou Shall Not Fear', 'Lazarus A.D.', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Animal', 'Kink Ador', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Half Crazy', 'Jukebox the Ghost', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('(pin)Ballz', 'Insomniac Games', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chameleon Carneval', 'Andromeda', 2001, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Everyone', 'Madlife', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hair Trigger', 'The Acro-Brats', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Curse', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Depths of Memory', 'NightShade', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Veil of Illumination (Part 1)', 'Andromeda', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Veil of Illumination (Part 2)', 'Andromeda', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Zig Zag Talk', 'Steve Fister', 2007, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('A Grim Struggle', 'Nightrage', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Angela Surf City', 'The Walkmen', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beat Fly', 'Tiny Danza', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Dawn of the Condoms', 'Ultra Saturday', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Dodgin Bullets', 'Steve Fister', 2007, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Doll in the Dust', 'Kurodust', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Leave Me Be', 'Kylie D. Hart', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('River of Glass', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Satisfying Angst', 'The Blackout Argument', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Self Medicate', 'Felsen', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Window', 'Raven Quinn', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hangman', 'Drugstore Fanatics', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hey I', 'Blackberry Wednesday', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Katsushika', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('My Star', 'Andromeda', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Passing Bells', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Queen Bee', 'Tina Guo', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Seestrasse', 'Killbody Tuning', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay Alive', 'Rivethead', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Underground', 'Wargasm', 1995, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Willow of Tears', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Another Step', 'Andromeda', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Dreamchaser', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Eden', 'TesseracT', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Give It Up! Give It Up!', 'His Statue Falls', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Hate', 'Madlife', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Revenants', 'The Cold Goodnight', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Schizophrenia', 'Jukebox the Ghost', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Trying Hard', 'Loni Rose', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Alaska', 'Between the Buried and Me', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Arctica', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Be Right Here', 'Mind At Risk', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burning Hearts', 'Silverstein', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Country Song', 'Seether', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Go North', 'The Pauses', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Halftime', 'Freen in Green', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Machine Gun Kisses', 'Murder FM', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Magnolia', 'Texas in July', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mayhem', 'Mortice', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mercury Blooming', 'Askari Nari', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Riptide Resort', 'Freen in Green', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Sick, Sick, Sick', 'Bayside', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Too Little Too Late', 'A Skylit Drive', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bamberg', 'Killbody Tuning', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('California', 'Winds of Plague', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Crazy', 'Nonpoint', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Last Chance', 'Tetrafusion', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Marker of Change', 'Killbody Tuning', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Only Star', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pressure Cooker', 'Magnus ''SoulEye'' Pålsson', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Rain', 'Indestructible Noise Command', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Devil''s in the Details', 'Aesthetic Perfection', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('This Round''s On Me', 'Blackguard', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Turning Sheep Into Goats/Systematomatic', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('30 Lives', 'The Motion Sick', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Be Careful What You Wish For', 'Memphis May Fire', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Better Off This Way', 'A Day to Remember', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Blackbird', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Curse of the Werewolf', 'Timeless Miracle', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Death of an Era', 'No Bragging Rights', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Demons With Ryu', 'Emmure', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Deny', 'Betrayed by Sorrow', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Empire', 'Jukebox the Ghost', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fallen Into You', 'Kings Queens & Fairytales', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Firefight', 'Blackguard', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Miracle', 'Nonpoint', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Positive Force', 'Magnus ''SoulEye'' Pålsson', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Suffer', 'Stretford End', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Resolve of Cowards', 'Burning Twilight', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Torture', 'Rival Sons', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('City of Corruption', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Epic Symphony in A Flat Minor, Third Movement: Zero Hour', 'Van Friscia', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Familiar', 'CyLeW', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('How Far', 'Synthetic Elements', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('My Future Life', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('No Ghost', 'The Haunted', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ooops', 'Garden of Eden', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rocket Car', 'Robotmakers', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Slander', 'Dr. Acula', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stay Awake', 'Stretford End', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Battle of Lil'' Slugger (Remix)', 'dB Soundworks', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('A Blinding Light', 'Blackguard', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Adicto al Dolor (Lágrimas)', 'Don Tetto', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Against the Wall', 'Ill Niño', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Blood & Scars', 'Grynd Rodd Muse', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come Now Follow', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dead Again', 'Possible Oscar', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Expert Mode', 'LeetStreet Boys', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fallido Intento', 'Don Tetto', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Field of Serpents', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fists Fall', 'Otep', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Good Things', 'Hella Donna', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hurricane', 'The Cold Goodnight', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('New Solution', 'SHIROCK', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sampo', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stuck in a Rut', 'Hip Kitty', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Talisman', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Mettle of a Man', 'Where the Ocean Meets the Sky', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tonight We Ride', 'Reform the Resistance', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('What''s Left of Me', 'Blessthefall', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Zombies!! (Coming Out Tonight)', 'Ultra Saturday', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Betus Blues (Retro Remix)', 'dB Soundworks', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Diachylon', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Froggy''s Lament', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hyperspace', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Masters of Puppet Rock', 'Action Action', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Mousetrap', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Namaste', 'Veil of Maya', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pac-Man Fever', 'Buckner & Garcia', 1999, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Prototype Death Machine', 'Bonded by Blood', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rise and Shine', 'Destruction of a Rose', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Exit', 'I Am Cassettes', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bed Intruder Song (feat. Kelly Dodson)', 'Antoine Dodson & The Gregory Brothers', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Bland Street Bloom', 'SikTh', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('By the Grace of the Grill', 'Graveyard BBQ', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Foundation', 'An Unkindness', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ghostly Echoes', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Morte et Dabo', 'Asking Alexandria', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('New Ground', 'The Story Changes', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Pray for Plagues', 'Bring Me the Horizon', 2006, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Queendom', 'B.et.a and The Neon Panthers', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Slaves to Substance', 'Suicide Silence', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sweet#hart', 'Closure in Moscow', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('You Only Live Once', 'Suicide Silence', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ziltoidia Attaxx!!', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Better Life', 'Conditions', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Caves', 'Chiodos', 2010, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Circus Freak', 'Standing Shadows', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cool Concoction', 'Shylo Elliott', 2010, 'Fusion', false, true, true, ARRAY['Rock Band DLC']),
('Dawn of Spring', 'Christopher J.', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Envision', 'Severed', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fame Is Free', 'Child of Glass feat. Suela', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Farewell, Mona Lisa', 'The Dillinger Escape Plan', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Glow', 'Alien Ant Farm', 2003, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Grant Me Peace', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Over the Top', 'White Wizzard', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rebel On My Side', 'Casey James Prestwood', 2011, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Ship With No Sails', 'Neonfly', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Turn Around', 'Bumblefoot', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('3 In The Morning', 'Teflon Don feat. Antonio Cooke', 2010, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('A Circus', 'My Wooden LeG', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Bad Things', 'Gladhander', 2009, 'Grunge', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Betrayed', 'Musica Diablo', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Daydreamer', 'Mute Defeat', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Desecration Day', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Evelene', 'Synthetic Elements', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Für Elise (Beethoven)', 'Magnefora', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Goodbye Goldblatt', 'Love Crushed Velvet', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Inheritors', 'Serianna', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Low Life in the Fast Lane', 'Pump', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Megalodon', 'Mastodon', 2004, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Need Strange', 'Chad Smith''s Bombastic Meatbats', 2009, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Pendulum', 'After the Burial', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Piano Sonata No. 11 - Ronda Alla Turca (Mozart)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Preacher & Devil', 'Noah Engh The Kid Fantastic', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Seahorse Seahell', 'Lions!Tigers!Bears!', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sinner''s Vengeance', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Still Young', 'SHIROCK', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Difference Between Medicine and Poison is in the Dose', 'Circa Survive', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Nightrager', 'Bob Katsionis', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Stars', 'Jukebox the Ghost', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Sword', 'Blackguard', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Whiskey''s Got A Job To Do', 'Karla Davis', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('By Your Command', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Category I: Slave to the Empirical', 'Ethereal Collapse', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fragments', 'Serianna', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Paper (Feat. Single White Infidel)', 'Bluefusion', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Regret', 'Dan Rothery', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stabbing the Drama', 'Soilwork', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Fall of Psilanthropy', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Grinding Wheels of War', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Thief in the Night - Part I', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('These City Lights', 'Rose of Jericho', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bagatelle No. 25 - Für Elise (Beethoven)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Battle of Egos Part I', 'Winter Crescent', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heroes Don''t Cry', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Honeys Takin'' Money', 'Audio Ammunition', 2007, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('I', 'Before Nine', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('If I Was King', 'Dan Markland', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Now or Never', 'Stagehands', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('On and On', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Piano Sonata No. 14 - Moonlight Sonata (Beethoven)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Pirats ''Til We Die', 'Halfbrick Studios', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Very Busy People', 'The Limousines', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Walks Like A Ghost', 'Quartered', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('!I', '!I!', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('American Hero vs. Done', 'Robin Skouteris', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cluster #2', 'Askari Nari', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Dawn (Blood Saga I)/Through the Maelström', 'Morgawr', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Devil''s Boulevard', 'Eminence', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gymnopédie No. 1 (Satie)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Moonlight Ride', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('PON DE FIOR', 'SNMT', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Poor Yorick', 'Shakespeare in Hell', 2001, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Reviving a Dead Language', 'Askari Nari', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Shadow of a Man', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Cheval Glass', 'Emery', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Toast (Live)', 'Heywood Banks', 1998, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Wha-Chow Theme (Feat. ShadyVox)', 'Psyguy', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Act of War', 'Lich King', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ashes to Ashes / Leaving It All Behind', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Caraphernelia', 'Pierce the Veil', 2010, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Dance Battle Alpha', 'Active Knowledge', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Doppelgänger', 'Freezepop', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Dystopia', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gold Rush', 'Armor For The Broken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Life Will Fade Away', 'Synthetic Elements', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Make It Last', 'Devoutcast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nugget Man', 'Paul and Storm', 2007, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Stabbing to Purge Dissimulation', 'All Shall Perish', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sweet Rain', 'Weeping Buddhas', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Space for This', 'Cynic', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Your Troubles Will Cease and Fortune Will Smile Upon You', 'After the Burial', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flight of the Bumblebee (Rimsky-Korsakov - Piano Version)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Glamour Life', 'IDLEMINE', 2006, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Hyperdrive', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Madness', 'Myrath', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Magnolia', 'Terrorhorse', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Making Love (To a Foreign Woman While Reading Time Magazine)', 'Blue Water Dance', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('My Frailty', 'After the Burial', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rock Me Roxy', 'Haunted By Heroes', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scissors', 'Emery', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('War in Heaven', 'Amberian Dawn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Young Love', 'Oh Darling', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Anubis', 'Septicflesh', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bombshell From Hell', 'Scum of the Earth', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Conquer Me', 'Damone', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('England Rock Anthems', 'Richard Campbell', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Fading Sacrifice', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fuzzy Man (Fuzzy Nation)', 'Paul and Storm', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Genuine Penguin', 'Askari Nari', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Give', 'One Day', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hitman Blues', 'The Blue News', 2011, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Slit', 'Without Mercy', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('So Let Us Create', 'Jukebox the Ghost', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spineless', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Age of Betrayal', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Victor(ia)', 'Conflicted', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Wake Up Fall', 'All City Elite', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Estranger', 'Vangough', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Forbidden City', 'Tina Guo', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Funeral on Parade', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('He''s Our Savior', 'DJ Raptorz', 2010, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('OH-KAY!', 'Jutbox', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Space Unicorn', 'Parry Gripp', 2011, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Stellar Crash', 'Hedras Ramos', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('A Sickness You Like', 'Yesternight''s Decision', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Any Other Heart', 'Go Radio', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Courage', 'Alien Ant Farm', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dig Your Grave', 'Kamikaze', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Downhill', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('In Division', 'Underoath', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Into the Black Light', 'Ghost Brigade', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Just a Game', 'The Blue News', 2011, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Nemesis', 'Arch Enemy', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Reaching Down', 'Order of Voices', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('A Bridge That Will Burn', 'Moving Picture Show', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Family Affair', 'Verah Falls', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Children Surrender', 'Black Veil Brides', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Constellation', 'The Story Changes', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Diana Don''t Slow Down', 'Gary Dean Smith', 2011, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Echo', 'Dance for the Dying', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('End of My Rope', 'Spinning Chain', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fair Weather Friend', 'Gary Dean Smith', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Fire Death and Fear', 'Rotting Christ', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heaven''s Calling', 'Black Veil Brides', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mouth Without a Head', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Perfect Weapon', 'Black Veil Brides', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Remember', 'Jenium', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Solar Winds', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('4 Walls, 1 Window', 'Finespun', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Examination', 'I Am Abomination', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('If You Can''t Hang', 'Sleeping with Sirens', 2011, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Never... Again', 'All Shall Perish', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pain I Feel', 'Spinning Chain', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scarred', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Surface', 'Imperative Reaction', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Elevator', 'I Am Empire', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Entertainer (Joplin)', 'Thomas Walker', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('White Shoes', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cody', 'We Set The Sun', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Last Breath', 'Attack Attack!', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Run Away With Me', 'Daryle Stephen Ackerman', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wicked N'' Wild', 'IDLEMINE', 2006, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Winter Water Waves', 'Denullification', 2011, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('All Signs Point to Lauderdale', 'A Day to Remember', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Category II: Discovering the Absolute', 'Ethereal Collapse', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cry of an Eagle', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dark Escape', 'Shylo Elliott', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Indulgence', 'Tokyo Raid', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Internal Cannon', 'August Burns Red', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Movies', 'Alien Ant Farm', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Reaping Tide', 'Mile Marker Zero', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Say', 'The Asbestos', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Carrion Call', 'Misery Index', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Coelacanths', 'Coelacanths', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Crazy Idea', 'Goliath Down', 2011, 'Inspirational', false, true, true, ARRAY['Rock Band DLC']),
('Easy Days', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('For God or Country', 'Single White Infidel', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Grocery Party', 'Freen in Green', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('He Is Good', 'Denbigh Cherry', 2011, 'Inspirational', false, true, true, ARRAY['Rock Band DLC']),
('Heat Seeking Ghost of Sex', 'Dance Gavin Dance', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Looking (Foot in Your Mouth)', 'Analogue Revolution feat. The Chance Sisters', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('My God Is There Controlling', 'Denbigh Cherry', 2011, 'Inspirational', false, true, true, ARRAY['Rock Band DLC']),
('Of Dirt You Were Made...', 'Brad Gerke', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Paced Energy', 'Magnus ''SoulEye'' Pålsson', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The End of Progress', 'Mystakin', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('2nd Sucks', 'A Day to Remember', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blood Red Rose', 'The Boyscout feat. Amanda Somerville', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('CMDUC', 'Without Mercy', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Death of a Dream', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Galactic Love', 'New Nobility', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('If It Means a Lot to You', 'A Day to Remember', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Name''s Horatio, You Got Me, You Ain''t Got Nobody Else, So Deal With It, And Love It', 'Mega64', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Never Again', 'The Bloody Five', 2010, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Reality Down', 'Active Knowledge', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Selkies: The Endless Obsession', 'Between the Buried and Me', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Show Me What You''ve Got', 'Powerman 5000', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sisters', 'JOANovARC', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sweet Canadian Mullet', 'Glenn Case', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Monster Stroll', 'Jocko of Sha Na Na', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('-20% for Being a Loser', 'We Are Knuckle Dragger', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Battle', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Church of No Return', 'Christian Death', 1988, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Do the Donkey Kong', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Embrace the Curse', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flags', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Found Me the Bomb', 'Buckner & Garcia', 2011, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Goin'' Berzerk', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hold Me In Your Arms', 'The Trews', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lunatic', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Melted Picks & Broken Sticks', 'Savage Minotaur', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ode to a Centipede', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Defender', 'Buckner & Garcia', 1999, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Boy', 'Ra Ra Riot', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Can You Tell', 'Ra Ra Riot', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Faux King Christ', 'Atheist', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Frankenstein Teaser Trailer', 'Richard Campbell', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Haunting the Dead', 'Lockdown', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Heavy Weather - The Storm ov The Undead', 'Rainbowdragoneyes', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Inversion', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Let It Ride', 'Spinning Chain', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Life or Death', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Answer', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Cascade Effect', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Consequences', 'Mystakin', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The Fractal Reason', 'Active Knowledge', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Apology Rejected', 'These Hearts', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cross and Crows', 'The Asbestos', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('El Monstro', 'Dance for the Dying', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Forget', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Harmony of the Spheres', 'Jake Dreyer', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Strangers', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Way It Ends', 'Prototype', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Undercover', 'Anita Maj', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Traffic Jam', 'Lino Gonzalez', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Trenches', 'The Haunted', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('A Tadg30 Song', 'Askari Nari', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bigger than Kiss', 'Teenage Bottlerocket', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Break Free from Your Life', 'Design the Skyline', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Break Me', 'The Irresponsibles', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Can o'' Salt (Remix)', 'dB Soundworks', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Horizon', 'Thunder and Lightning', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('It''s Sno, Baby - Not Sugar', 'Snovonne', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Retaliation', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ocean Floor', 'The Bunny the Bear', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Over and Out', 'Cancer', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Preacher Man', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pretty Boy', 'The Irresponsibles', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Proto-Lupus', 'Wolfblur', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Starlight Speedway', 'Rocket Ship Resort', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Man''s Masterpiece', 'BioShaft', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Reapers Shall Gather / Arrival', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tired Climb', 'Kylesa', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Without Morals', 'Nevermore', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cheesy Pop Song', 'A Talking Fish', 2011, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Cold', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hysteria', 'Aiden', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('If We Only Saw Sepia', 'The Fenton Project', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Last Hope', 'A Call To Remain', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Little Sister', 'Ultra Saturday', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('March Into Hell / Blood on My Soul', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Martyr to Science', 'Deadlock', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mida''s Secret', 'Will Haven', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No More Excuses', 'Kill the Alarm', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ocaso Escarlata', 'Nod 206', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Potential for Anything', 'Magnus ''SoulEye'' Pålsson', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Rage and Pain', 'Francisco Meza', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Respiration Desperation / The Neutral Zone', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Grinder''s Tale', 'Wrong Side of Dawn', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Obsidian Conspiracy', 'Nevermore', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Victim', 'The Bitter Roots', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Pure Evil', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('All I Want Is You', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Category III: Architect', 'Ethereal Collapse', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dark Beat', 'The Black Beverly Heels', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death In General', 'Gigakoops', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Ever Change', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Go', 'Kari Kimmel', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Icon of Resolution', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('In Between', 'Silent House', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lethean Tears', 'Solution .45', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Love''s the Profit', 'Mike Kotulka', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mil Rosas', 'Niño Burbuja', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('N9', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Real Wild Child', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sad Wings', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tear It Up', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Epic, Part 3.7 (RBN Remix)', 'Bankai', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Underneath the Cenotaph', 'Watain', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('V is for Vampire', 'Powerman 5000', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bullet', 'Drugstore Fanatics', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Darkness', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hatas (Rock Band Mix)', 'LEL Brothas', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Nevermore', 'Morbid Angel', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Red Crayon', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Still Alive', 'Jonathan Coulton ft. Sara Quin', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Final Hour', 'Those Among Us', 2011, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('The Massacre (Rock Band Mix)', 'FantomenK', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('These Voices', 'Deception of a Ghost', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(I Want to Go to) Space', 'A Talking Fish', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Beer, Metal, Trolls and Vomit!', 'Nordheim', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Christina Marie Magenta', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Culling the Weak', 'Broken Equilibrium', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Diamond Eyes', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Eternity Below', 'Quartered', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Just a Lie', 'Pythia', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Planet Smasher', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The One Who Walks Alone', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('BRODYQUEST', 'Lemon Demon', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Clawmaster', 'Ghost Brigade', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Console War', 'DRUOX', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Elysian', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Entropy/Extropy', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Existo Vulgoré', 'Morbid Angel', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fairweather Stranger', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Inside', 'Cold Steel', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Keyhole in the Sky', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Mountains of Maths', 'Ultra Vomit', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mow', 'Miss Crazy', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Superjet', 'Raggedy Angry', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Hourglass Paroxysm - Part I', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Too Little Too Late', 'Pan.a.ce.a', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Touch the Mic', 'The Break Down', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('All In My Head', 'The Last Nova', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('BEER!!', 'Psychostick', 2003, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Eye Me Like a Child', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dos Impar', 'Channel', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gordon Freeman Saved My Life', 'Miracle of Sound', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gravitational Lensing', 'Solution .45', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heart Of A Child', 'A Plea for Purging', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heartless', 'Pythia', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Indiscriminate Murder is Counter-Productive', 'Machinae Supremacy', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Inside Looking Out (The Icon & the Ghost)', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lights, Camera and Action', 'The Asbestos', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('M.O.N.O.S', 'Los Noelia', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Melodicus Counterpointus', 'Coldera', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Night', 'Gigakoops', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Nightfall', 'Silent House', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pray for You', 'Jaron and the Long Road to Love', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Radio World', 'IDLEMINE', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shipwrecked', 'Alestorm', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Stache', 'Jonathan Coulton', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The System', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Twenty One', 'Oh My!', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Building the Towers', 'Halcyon Way', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flesh and Blood', 'Edge', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Generic Techno Song', 'Askari Nari', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Grace Kelly', 'The Motion Sick', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Half Cab', 'Quartered', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Play Around', 'SuperSeed', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Second to Sun', 'Atheist', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Super Villain', 'Powerman 5000', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Thug Love', 'Dance for the Dying', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Time Bomb', 'Powerman 5000', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Battle of Egos Intro', 'Winter Crescent', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Feathergun in the Garden of the Sun', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Für Immer Verloren', 'Anarchy Club', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Good Morning Tucson', 'Jonathan Coulton', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Baptised', 'Codex Alimentarius', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Do Your Thing', 'Powerman 5000', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Force Feedback', 'Machinae Supremacy', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Garble Arch', 'Blame Ringo', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Dirt', 'Josh Blackburn', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('In A Hurricane', 'Blame Ringo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Narcissus Metamorphosis Of', 'Christian Death', 2007, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Scissorlips', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to the Skalocaust', 'Sunny Side Up', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Wild Yellowness', 'Radidsh', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Calling Out', 'Engel', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Drink Beer, Destroy', 'Trucker Diablo', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Easter Island Radiation', 'Raggedy Angry', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Give', 'Mystic Syntax', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Je Collectionne des Canards (Vivants)', 'Ultra Vomit', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('King of Everything', 'Anarchy Club', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lonesome Cowboy', 'Richard Snow', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Machine', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Put Out the Fire', 'Look Left', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rise to Revise', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rocket Dragon', 'Machinae Supremacy', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Song for Meg', 'SIMPL3JACK', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Thief in the Night - Part II', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Weevil Bride', 'Rishloo', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Ashes', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Built to Grind', 'Anarchy Club', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Calling to Dance', 'EA', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Desconocido', 'Leche de Tigre', 2011, 'Latin', false, true, true, ARRAY['Rock Band DLC']),
('Ghost of Fallen Pluto (Instrumental)', 'Spassm', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Not Fade Away', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Omega Wave', 'Forbidden', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Over & Over', 'Valor & Vengeance', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Por Nada', 'Maríafer', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Gigantic Robot Kills', 'MC Lars feat. MC Bat Commander and Suburban Legends', 2009, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('What Do You Do When the Money Runs Out', 'The Duel', 2006, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Absolute', 'Gatling', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Corporate Control', 'Sunny Side Up', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Hope & Ruin', 'The Trews', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('In My Head', 'Swound!', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mystery Train', 'Jerry Naylor', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('XenoChrist', 'The Faceless', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Visceral', 'Gnostic', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Back Through Time', 'Alestorm', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Color Your World', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Forever in Lies', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I am S/H(im)e[r] as You am S/H(im)e[r] as You are Me and We am I and I are All Our Together', 'Giraffes? Giraffes!', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Gotchu Babe', 'Rachel Lynn Sebastian and DJ Jounce', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Kitty Fight Song', 'Dance for the Dying', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Liberation', 'Lucy Seven', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No War', 'Brutal Assault', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rise and Shine', 'Anarchy Club', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sense the Fire', 'Engel', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stairs on the Hill', 'Roman Klun', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Greys', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Jack', 'Rosemary''s Garden', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Panic Range', 'Claire St. Link', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Twitter Twatter', 'Mind The Gap', 2012, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Actually Do This Thing Where We Drop the First String', 'A Lie to Live By', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to the Future', 'Left Spine Down', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Brains Out', 'RIBS', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Creatures ov Deception (RB3 version)', 'Rainbowdragoneyes', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Force', 'Bluefusion', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Galileo', 'We Are The Storm', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('SEX', 'SNMT', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('The Final Act', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Plot to Bomb the Panhandle', 'A Day to Remember', 2007, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Animal Instinct', 'Sherryce ft. Beta Control', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Insidious', 'Nightrage', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nemeses', 'Jonathan Coulton ft. John Roderick', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Until I Feel Nothing', 'Carnifex', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Broken Bones', 'Aiden', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Gypsy Rave Massacre Party 2', 'Sweethammer', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Last Call', 'Sworn To Oath', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Shaking', 'Bikey ft. Dapper AJ', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('She''s Rad', 'Sunny Side Up', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Song for the Broken', 'Close Your Eyes', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Soul Candy', 'Danny and the Lost Souls', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('The Luck You Got', 'The High Strung', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Todo lo que Pienso', 'Joe Vikingo', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Get What You Pay For', 'Jason Charles Miller', 2011, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('A Bullet in the Head', 'Anarchy Club', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Greed', 'The Mercy House', 2012, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Hapless', 'Seven Day Sonnet', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Me and You', 'The Bitter Roots', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Our Time', 'The Buffalo Joe Band', 1998, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Toccata and Fugue in D Minor (Bach)', 'Magnefora', 2011, 'Classical', false, true, true, ARRAY['Rock Band DLC']),
('Valleys', 'Close Your Eyes', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('What''s Left of the Right Brain?', 'Single White Infidel', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Amazing Horse', 'Weebl''s Stuff', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Heroism', 'Mystakin', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('IndoctriNation', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Into Your Hands', 'Kandia', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Love Dragons', 'Charlie Drown', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No Holy Man', 'Eden''s Curse ft. James LaBrie', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Sleek Peak', 'Mada', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Younger Lungs', 'Less Than Jake', 2012, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('California', 'Heart Pharmacy', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Farewell to Good Days', 'Seven Day Sonnet', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gamers Unite', 'Dante''s Dream', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Keep the Lights On', 'Close Your Eyes', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ooh La La', 'Sherryce and DJ Jounce', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Riddle Me This', 'Anarchy Club', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Take Me Home', 'Raggedy Angry', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Apple Martini', 'Shelita Vaughns', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Children of Brodom', 'Oklahoma Caddy Shack', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Controller', 'Within the Ruins', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Interplanetary Cruise', 'Jeff Ball', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Jumping Ship', 'Counterparts', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Por Analogía', 'Pedro Castillo', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('TGTW', 'Boomchick', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Only Difference', 'Cohesive', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wabi-Sabi', 'Sky Pie', 2003, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Watching', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Wrapped in Deceitful Dreams', 'Nightrage', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Absolution', 'Dirge Within', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Adonaï', 'Eths', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('All the Hated', 'Sifting', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blood of the Resistance', 'Volumes of Revolution', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Coming Undone', 'Shatterglass', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crack My Head and Let the People Out', 'Look Left', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Goodbye, Mr. Personality', 'Less Than Jake', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Want to Hear About Your Crappy Boyfriend', 'Honest Bob and the Factory-to-Dealer Incentives', 2004, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Dancing!', 'Bikey ft. Alyce', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Never Trust the Hazel Eyed', 'Hopes Die Last', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Paging Ground Control', 'Small Room 9', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Reap (Radio Edit)', 'The Red Jumpsuit Apparatus', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Relationship Sneakers', 'Goin'' Places', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Death Plague', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Wish I Was Dead', 'Harbour Grace', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crabplosion', 'Skylliton', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('En Donde Duermen Los Sueños', 'Nod 206', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('For the Kids of the Multiculture', 'Sonic Boom Six', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gravis Venter', 'Eths', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Impulse', 'An Endless Sporadic', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Death in the Garden', 'Dance for the Dying', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Got 2 Me', 'Ten Year Vamp', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('L.E.V.A.N.T.A_te', 'Masseratti 2lts', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Nobody Gives a S*** About Us', 'Goin'' Places', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('To the Stars', 'Cohesive', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Top', 'Look Left', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Dudes and Guys and Things and Stuff', 'Straight Outta Junior High', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('So High', 'Lee-Leet', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('5 Segundos', 'Languidez', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fight The Rain', 'Scratching the Itch', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('La Inclinación de la Balanza', 'Niño Burbuja', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('On the Run', 'Emerald', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pearls; The Frailty of Matter', 'The Burial', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Reckless & Relentless', 'Asking Alexandria', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Reson-8-R (Pts. I & II)', 'Christopher J.', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Skeletonizer', 'Wolfcrusher', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Way That It Goes', 'Cohesive', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Another Purity Failing', 'Edenshade', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dear Insanity', 'Asking Alexandria', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sarah', 'Daryle Stephen Ackerman', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Skinny Seventeen', 'Jeremy Manjorin', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Infinite Descent', 'Spires', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This is the Album You''ve Been Waiting For', 'brentalfloss', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('At War With the Cherubs', 'SIMPL3JACK', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Hourglass Paroxysm - Part II', 'Chaotrope', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Circus Black', 'Amberian Dawn', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Drink the Bottle', 'John Daly Project', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('From the Blue/Point of No Return', 'An Endless Sporadic', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Romancing the Ordinary', 'Rose of Jericho', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('So Far Away / Delirium Of The Fallen', 'Nightrage', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Superficial', 'X-Y', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Ravenous', 'I, Omega', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Will', 'Die Hard Till Death', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('(I''m the One That''s) Cool', 'The Guild feat. Felicia Day', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Anything', 'An Endless Sporadic', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('AY', 'Sin Dirección', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chiasm', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Frontier Factory: Remanufactured', 'Freen in Green', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('I Like Trains', 'Lil Deuce Deuce', 2011, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('O-Ren', 'SIMPL3JACK', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Political Bum', 'Psychostick', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Say Sayonara (English version)', 'JOANovARC', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Say Sayonara (Japanese version)', 'JOANovARC', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wasted', 'Fail Emotions', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('A Death', 'An Unkindness', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Alone at Home', 'Jonathan Coulton', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Border', 'The Giraffes', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Discord (The Living Tombstone Remix)', 'Eurobeat Brony', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('In the Wake of Evolution', 'Kaipa', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Rebirth', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Whole Lotta Shakin'' Goin'' On', 'Jerry Naylor', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wolves', 'Brand New Analogues', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Words Cannot Express', 'An Unkindness', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Evolutionary Sleeper', 'Cynic', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Faster Than a Bullet', 'Zing Experience', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('L''alfabeto', 'Simone Bacchini', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Moments of Clarity', 'Children of Nova', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Radiant Light', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Subterfuge', 'Terrorizer', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tear My Heart In Two', 'Daryle Stephen Ackerman', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Episodes', 'Dante''s Dream', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lady Luck', 'Hillcrest', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Duel', 'Not Above Evil', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('These Days', 'Astra Kelly', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Walk of Shame', 'My Ruin', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Angeles', 'Merlot', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Everything I Hate About Myself', 'Death of the Cool', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Little Girl', 'Jerry Naylor', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('On Black Wings', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Say What You Want', 'Counterfeit Pennies', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Teardrops Fall Like Rain', 'Jerry Naylor', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('To the Stage', 'Asking Alexandria', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Blessed Night', 'Saint Vitus', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('From the Ground Up', 'Trial By Fire', 2012, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Our Finest Hour', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Wrong Side', 'Catsmelvin', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hoy', 'Vargas', 2011, 'Jazz', false, true, true, ARRAY['Rock Band DLC']),
('Version 2', 'Yogurt With Sprinkles', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('But Then I Fell in Love', 'Look Left', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Move Your Body', 'Eiffel 65', 1999, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Stop Staring', 'Leadership by Assault', 2012, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Restless Mind', 'Francisco Meza', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Dash', 'Bumblefoot', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Let''s Write a Song', 'Una Jensen', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Livin'' the Dream', 'Silent Theory', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mind In Motion', 'Art Benson', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ride', 'Fretless', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('That''ll Be the Day', 'Jerry Naylor', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Main Thing', 'Nathaniel Whitlock', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('The Triangular Race Through Space', 'An Endless Sporadic', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Deconsecrated', 'My Ruin', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fight!', 'Mada', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Gambit', 'Zef', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Giant Bombstep: Reloaded', 'The Hamster Alliance (ft. The Giant Bomb Crew)', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Higher', 'Tora', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Nube', 'Okills', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sticks & Bricks', 'A Day to Remember', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Supertronic Lazering', 'Active Knowledge', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('There is Nothing Left', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Things That Make You Scream', 'Memory of a Melody', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Under a Raging Moon', 'John Parr', 2011, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Would I Were', 'Husky in Denial', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Back to You', 'Mikel James', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cold Kiss', 'Amberian Dawn', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Like Never Before', 'Astra Kelly', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Phantasmal Cruise', 'Shylo Elliott', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Closer', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Doesn''t Count', 'A Life Divided', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Believe It', 'Flatfoot 56', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Majesty', 'Ava Inferi', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Phoenix Down', 'The Unguided', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Resolute', 'Soma Dark', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Things I''ll Just Pretend', 'Edenshade', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('77345_018', 'The Minotaur Project', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Acvodad', 'Tobey McTired', 2012, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Baby', 'Carousel Kings', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Chaos of Forms', 'Revocation', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Drained', 'Vangough', 2011, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Fragments', 'An Unkindness', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hate Turns Black', 'Nightrage', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Keep on Running from My Love', 'Danny and the Lost Souls', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Keepers of the Faith', 'Terror', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Legacy of Blood', 'Internal Corrosion', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('One By One', 'Buried in Black', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Re-Live', 'Strikken', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Redeemer', 'War of Ages', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Robots', 'Sweethammer', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Who Am I?', 'MANNA', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You, Me, & the Boatman', 'Quiet Company', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);