-- Part 5
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Godhead', 'Onslaught', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Can Swing My Sword (ft. Terabrite)', 'Toby Turner', 2012, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Rampage of Kronos', 'The Minotaur Project', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cross Over Attack', 'Emmure', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('How Do You Do It?', 'Quiet Company', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lonely', 'The Bunny the Bear', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Para Ti', 'Sin Dirección', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stop This (NOW!)', 'Tub Ring', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('All Bodies', 'Between the Buried and Me', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Carny Asada', 'SIMPL3JACK', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Distance', 'Drugstore Fanatics', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Turn Back Time (Rock Band Edition)', 'Escape The Day', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This War Will Never Start', 'Steve Pardo', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('EsCupido', 'Sincrónica', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Monday Night Football', 'John Parr', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Angels and Demons', 'Melissa Otero', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dilated Disappointment', 'Wretched', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Tell Me What to Dream', 'God Forbid', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Let the Blood Spill Between My Broken Teeth', 'Benighted', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Werewolf Grandma With Knives (Part Two: Don''t Die)', 'Giraffes? Giraffes!', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Absolution', 'One Year Later', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Kid''s Gonna Rock', 'The Stanleys', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ode to Stove', 'DRUOX', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sham Piety', 'Nightrage', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Shattered Satellites and Brutal Gods', 'The Minotaur Project', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Black Rose', 'Icon & the Black Roses', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Gold Teeth on a Bum', 'The Dillinger Escape Plan', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No Surrender', 'Taproot', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('St. Elmo''s Fire (Man in Motion)', 'John Parr', 1985, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tim Tebow''s Fire', 'John Parr', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Single Drop of Red (The Gentleman)', 'Anarchy Club', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Charnel''s Ball', 'Amberian Dawn', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Crusader', 'AFD Shift', 2007, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Lars Attacks!', 'MC Lars', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Mannequin', 'Dance for the Dying', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mary', 'The Lora G Band', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Naughty Naughty', 'John Parr', 1984, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('People of the Deer', 'The Trews', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Protoman', 'Emmure', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rehén', 'Enemigo', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock the Halls', 'Richard Campbell', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Christmas Song (Live)', 'Distant Autumn', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Battle of Egos Part II', 'Winter Crescent', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Circus', 'IDLEMINE', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dozing Green', 'Dir En Grey', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Jasmin W. Knows How to Mosh', 'His Statue Falls', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Leave It All Behind', 'Cult to Follow', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Superföhn Bananendate', 'We Butter the Bread with Butter', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The City', 'The Giraffes', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Singularity', 'Chaotrope', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Last', 'Dante', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Shapeshifter', 'One Year Later', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Splitting Time', 'Nuke Wrath Tech', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Duel', 'Rusty Cooley', 2003, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Window', 'Kenny Wesley', 2011, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Amylee', 'The Michael J. Epstein Memorial Library', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Break Away', 'Memory of a Melody', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hageshisa to, Kono Mune no Naka de Karamitsuita Shakunetsu no Yami', 'Dir En Grey', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Impossible Landscape', 'Children of Nova', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Silence of a Gun', 'Mob Machine', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Final Battle', 'Freen in Green', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Highly Explosive', 'My Ruin', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('In This Life of Pain', 'All Shall Perish', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Monument', 'ANKST', 2009, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('The Living End', 'Ava Inferi', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Two Thousand Eight Hundred', 'Sacred Mother Tongue', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Floating Feather (Blue Day & Age)', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Great Balls of Fire', 'Jerry Lee Lewis', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('KITTY! (ft. The Anime Cow)', 'Bluefusion', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Liberation', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Parasitic Twins', 'The Dillinger Escape Plan', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Smartass Rascals', 'The Smartass Rascals', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sober Up', 'Leadership by Assault', 2012, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Vultures', 'My Ruin', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('300 Thousand Miles', 'Jack Bundy', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('All the Fires Burning', 'Anarchy Club', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Be With Me', 'Goin'' Places', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Make the Sauce', 'Vegan Black Metal Chef', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ordinary Objects', 'Dance for the Dying', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Guys, You''re Not Dead Yet', 'BabelFish', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Level 1 - Winter City', 'Freen in Green', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Silent Night', 'War of Ages', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Standing Still', 'The Break Down', 2009, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Alarms', 'RIBS', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Killer', 'Panic the Memory', 2010, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Endless Sky', 'I See Stars', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('More', 'Down June', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('This is Not a Song, It''s a Sandwich!', 'Psychostick', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Timebomb', 'Astra Kelly', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Abre Tus Ojos', 'Lucybell', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bottle Rocket', 'Brian Kahanek', 2010, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Deception', 'Nightmare Lyre', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('NZT48', 'I See Stars', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Redirect', 'Your Memorial', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Trapped In Your Lies', 'Godhead', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('At the Cathedral', 'John Parr', 2012, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Synesthesia', 'Chaotrope', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Virus', 'Sonic Boom Six', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('10,000 Headless Horses', 'Our Last Enemy', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('American Terrorist', 'Deception of a Ghost', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Discord (EuroChaos Mix)', 'Eurobeat Brony ft. Odyssey', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Haben Haben Haben', 'Dampfmaschine', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Hordes of Zombies', 'Terrorizer', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rise Above', 'Van Friscia', 2013, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Integral Birth', 'Cynic', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('King of Those Who Know', 'Cynic', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Need', 'Edenshade', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Overdriven', 'Left Spine Down', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Passing the Ace', 'Chad Smith''s Bombastic Meatbats', 2010, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Return to Strength', 'Terror', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Revolution is Now', 'Halcyon Way', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Santa Fe (RB3 version)', 'Blackberry River Band', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Shizuku', 'Esprit D''Air', 2012, 'J-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Show Me a Sign', 'Azania', 2012, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Skeleton', 'Adora', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Duel', 'Van Friscia', 2013, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('You Can''t Swim With Concrete Shoes', 'Throw the Fight', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('¿De qué Sirve?', 'Okills', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ave Fénix', 'Lucybell', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Filth Friends Unite', 'I See Stars', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Madness is God', 'A Life Once Lost', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('One', 'Those Among Us', 2011, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Onyx', 'Ava Inferi', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Regeneration', 'Tyler Green', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Transformation Pt. 1', 'Fail Emotions', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Widower', 'The Dillinger Escape Plan', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('You''re Gonna Say Yeah!', 'Hushpuppies', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hell Yeah', 'Rhythm Bastard', 2013, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Laser Speed Force', 'Machinae Supremacy', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Neighbors Ate My Zombies!', 'Freen in Green', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Thrashbaath', 'Rainbowdragoneyes', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('It''s Better to Spend Money Like There''s No Tomorrow Than Spend Tonight Like There''s No Money', 'Quiet Company', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Light', 'The Lora G Band', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unleash Hell', 'Hopes Die Last', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The New Blood', 'Terror', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Vapor Radian', 'Jeff Ball', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hero', 'Machinae Supremacy', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Presence Everlasting', 'Nonexist', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The End of Prom Night', 'Snow White''s Poison Bite', 2011, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Fire At Will', 'Nonexist', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Journey', 'Grand Warp Focus', 2013, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Via Dela Rosa', 'Scum of the Earth', 2012, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Halcyon', 'Chaotrope', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Victory', 'Christian Muenzner', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Beyond the Night', 'Richard Campbell', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Humanoid', 'SIMPL3JACK', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Trixie', 'Jeff Burgess', 2012, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Go Home', 'Carousel Kings', 2012, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Edge Of Town', 'Distant Autumn', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Republic Of Gamers', 'Machinae Supremacy', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Spark Of Life', 'Richard Campbell', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The Modern Prometheus', 'Richard Campbell', 2012, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Free Fall', 'Rose Of Jericho', 2013, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wake Up', 'SOiL', 2013, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ready, Set, Stop', 'Vanattica', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Thirteen (ft. M_80!, Watershed & Wolfblur)', 'Bluefusion', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Caught Up in You', '.38 Special', 1982, 'Southern Rock', false, true, false, ARRAY['Rock Band 4']),
('What''s Up?', '4 Non Blondes', 1992, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Toys in the Attic', 'Aerosmith', 1975, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Arabella', 'Arctic Monkeys', 2013, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Hail to the King', 'Avenged Sevenfold', 2013, 'Metal', false, true, false, ARRAY['Rock Band 4']),
('Violent Shiver', 'Benjamin Booker', 2014, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Start a Band', 'Brad Paisley ft. Keith Urban', 2008, 'Country', false, true, false, ARRAY['Rock Band 4']),
('Mainstream Kid', 'Brandi Carlile', 2015, 'Blues', false, true, false, ARRAY['Rock Band 4']),
('Short Skirt/Long Jacket', 'Cake', 2001, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('V-Bomb', 'Dark Wheels', 2015, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Prayer', 'Disturbed', 2002, 'Nu-Metal', false, true, false, ARRAY['Rock Band 4']),
('Metropolis—Part I: The Miracle and the Sleeper', 'Dream Theater', 1992, 'Prog', false, true, false, ARRAY['Rock Band 4']),
('Knock Em Down', 'Duck & Cover', 2014, 'Punk', false, true, false, ARRAY['Rock Band 4']),
('Albert', 'Eddie Japan', 2015, 'Indie Rock', false, true, false, ARRAY['Rock Band 4']),
('Suspicious Minds', 'Elvis Presley', 1969, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Centuries', 'Fall Out Boy', 2015, 'Pop-Rock', false, true, false, ARRAY['Rock Band 4']),
('You Make Loving Fun', 'Fleetwood Mac', 1977, 'Classic Rock', false, true, false, ARRAY['Rock Band 4']),
('The Feast and the Famine', 'Foo Fighters', 2014, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Ain’t Messin ‘Round', 'Gary Clark, Jr.', 2012, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Follow You Down', 'Gin Blossoms', 1996, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Tongue Tied', 'Grouplove', 2011, 'Indie Rock', false, true, false, ARRAY['Rock Band 4']),
('I Miss the Misery', 'Halestorm', 2012, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Kick It Out', 'Heart', 1977, 'Classic Rock', false, true, false, ARRAY['Rock Band 4']),
('I Am Electric', 'Heaven''s Basement', 2013, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('I Bet My Life', 'Imagine Dragons', 2015, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Lazaretto', 'Jack White', 2014, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Recession', 'Jeff Allen ft. Noelle LeBlanc and Naoko Takamoto', 2015, 'Pop/Dance/Electronic', false, true, false, ARRAY['Rock Band 4']),
('Cold Clear Light', 'Johnny Blazes and the Pretty Boys', 2015, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 4']),
('Halls of Valhalla', 'Judas Priest', 2014, 'Metal', false, true, false, ARRAY['Rock Band 4']),
('Dream Genie', 'Lightning Bolt', 2015, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Little White Church', 'Little Big Town', 2010, 'Country', false, true, false, ARRAY['Rock Band 4']),
('All Over You', 'Live', 1994, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Turn it Around', 'Lucius', 2013, 'Indie Rock', false, true, false, ARRAY['Rock Band 4']),
('That Smell', 'Lynyrd Skynyrd', 1977, 'Southern Rock', false, true, false, ARRAY['Rock Band 4']),
('Uptown Funk', 'Mark Ronson ft. Bruno Mars', 2015, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 4']),
('The Wolf', 'Mumford & Sons', 2015, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Miracle Man', 'Ozzy Osbourne', 1988, 'Metal', false, true, false, ARRAY['Rock Band 4']),
('Still Into You', 'Paramore', 2013, 'Pop-Rock', false, true, false, ARRAY['Rock Band 4']),
('My God Is the Sun', 'Queens of the Stone Age', 2013, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('The One I Love', 'R.E.M.', 1987, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('A Passage to Bangkok', 'Rush', 1976, 'Prog', false, true, false, ARRAY['Rock Band 4']),
('Light the Fuse', 'Slydigs', 2015, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Dead Black (Heart of Ice)', 'Soul Remnants', 2013, 'Metal', false, true, false, ARRAY['Rock Band 4']),
('Superunknown', 'Soundgarden', 1994, 'Grunge', false, true, false, ARRAY['Rock Band 4']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Little Miss Can''t Be Wrong', 'Spin Doctors', 1991, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('Birth in Reverse', 'St. Vincent', 2014, 'Indie Rock', false, true, false, ARRAY['Rock Band 4']),
('Spiders', 'System of a Down', 1998, 'Nu-Metal', false, true, false, ARRAY['Rock Band 4']),
('Fever', 'The Black Keys', 2014, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Milwaukee', 'The Both', 2014, 'Pop-Rock', false, true, false, ARRAY['Rock Band 4']),
('Friday I''m In Love', 'The Cure', 1992, 'New Wave', false, true, false, ARRAY['Rock Band 4']),
('Somebody Told Me', 'The Killers', 2004, 'Alternative', false, true, false, ARRAY['Rock Band 4']),
('The Impression That I Get', 'The Mighty Mighty Bosstones', 1997, 'Reggae/Ska', false, true, false, ARRAY['Rock Band 4']),
('Your Love', 'The Outfield', 1985, 'Pop-Rock', false, true, false, ARRAY['Rock Band 4']),
('Light Up the Night', 'The Protomen', 2009, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Free Falling', 'The Warning', 2015, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Pistol Whipped', 'Tijuana Sweetheart', 2012, 'Punk', false, true, false, ARRAY['Rock Band 4']),
('Cedarwood Road', 'U2', 2014, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('I Will Follow', 'U2', 1980, 'Rock', false, true, false, ARRAY['Rock Band 4']),
('Brown Eyed Girl', 'Van Morrison', 1967, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 4']),
('At Night in Dreams', 'White Denim', 2013, 'Indie Rock', false, true, false, ARRAY['Rock Band 4']),
('My Own Eyes', 'Weird Al Yankovic', 2014, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Divide', 'All That Remains', 2014, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('What If I Was Nothing', 'All That Remains', 2012, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gimme Chocolate!!', 'BABYMETAL', 2014, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Run for Cover', 'Blitz Kids', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Throne', 'Bring Me the Horizon', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mona Lisa', 'Dead Sara', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Reflex', 'Duran Duran', 1983, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('September', 'Earth, Wind & Fire', 1978, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('All the Rage Back Home', 'Interpol', 2014, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Move Over', 'Janis Joplin', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jane', 'Jefferson Starship', 1979, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rebellion (ft. Daron Malakian)', 'Linkin Park', 2014, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Mephistopheles of Los Angeles', 'Marilyn Manson', 2015, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('High Road', 'Mastodon', 2014, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('One Big Holiday', 'My Morning Jacket', 2003, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Would You Still Be There', 'Of Mice & Men', 2014, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sugar, You', 'Oh Honey', 2015, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cowboys from Hell (Live from Monsters in Moscow Festival)', 'Pantera', 1991, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('King for a Day (ft. Kellin Quinn)', 'Pierce the Veil', 2012, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Summertime Boy', 'Seasick Steve', 2015, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Backwoods Company', 'The Wild Feathers', 2013, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Wanna Fight', 'Alabama Shakes', 2015, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Failure', 'Breaking Benjamin', 2015, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Trainwreck 1979', 'Death from Above 1979', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Follow Me Down', 'The Pretty Reckless', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cryin''', 'Aerosmith', 1993, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dude (Looks Like a Lady)', 'Aerosmith', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Eat the Rich', 'Aerosmith', 1993, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love in an Elevator', 'Aerosmith', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rats in the Cellar', 'Aerosmith', 1976, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Seasons of Wither', 'Aerosmith', 1974, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Always Something There to Remind Me', 'Naked Eyes', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('People Are People', 'Depeche Mode', 1984, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('What You Need', 'INXS', 1985, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bad Case of Loving You (Doctor, Doctor)', 'Robert Palmer', 1979, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Long Cool Woman in a Black Dress', 'The Hollies', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lust for Life', 'Iggy Pop', 1977, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Like a Stone', 'Audioslave', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Awake', 'Godsmack', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lying from You', 'Linkin Park', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bad Catholics', 'The Barbazons', 2015, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sing', 'Ed Sheeran', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Young Blood', 'Saint Raymond', 2015, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Riptide', 'Vance Joy', 2013, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shut Up and Dance', 'Walk the Moon', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('And The Cradle Will Rock...', 'Van Halen', 1980, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dance the Night Away', 'Van Halen', 1979, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hot for Teacher', 'Van Halen', 1984, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Runnin'' with the Devil', 'Van Halen', 1979, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unchained', 'Van Halen', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dreams', 'Beck', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Electric Love', 'BØRNS', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Cocoon', 'Catfish and the Bottlemen', 2015, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('First', 'Cold War Kids', 2015, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Renegades', 'X Ambassadors', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Coma Machine', 'Between the Buried and Me', 2015, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Heir Apparent', 'Opeth', 2008, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Nevermore', 'Symphony X', 2015, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Ex''s and Oh''s', 'Elle King', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Can''t Feel My Face', 'The Weeknd', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Irresistible', 'Fall Out Boy', 2015, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Different Colors', 'Walk the Moon', 2015, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stitches', 'Shawn Mendes', 2015, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sunday Bloody Sunday', 'U2', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pride (In the Name of Love)', 'U2', 1984, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Where the Streets Have No Name', 'U2', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Desire', 'U2', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('One', 'U2', 1991, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Vertigo', 'U2', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('California (There Is No End to Love)', 'U2', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Miracle (Of Joey Ramone)', 'U2', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Adventure of a Lifetime', 'Coldplay', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Drag Me Down', 'One Direction', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Thank God for Girls', 'Weezer', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('What Do You Mean?', 'Justin Bieber', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('On My Mind', 'Ellie Goulding', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Leave the Night On', 'Sam Hunt', 2014, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Immortalized', 'Disturbed', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Vengeful One', 'Disturbed', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Warrior', 'Disturbed', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('My Wave', 'Soundgarden', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Wicked Garden', 'Stone Temple Pilots', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hunger Strike', 'Temple of the Dog', 1991, 'Grunge', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Get Lucky', 'Daft Punk ft. Pharrell Williams', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Heartbeat Song', 'Kelly Clarkson', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hey Ya!', 'Outkast', 2003, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Locked Out of Heaven', 'Bruno Mars', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Treasure', 'Bruno Mars', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dancing with Myself', 'Generation X', 1981, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Love Stinks', 'The J. Geils Band', 1980, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Hate Myself for Loving You', 'Joan Jett & the Blackhearts', 1988, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Speed Fighter', 'Masaya Matsuura', 2014, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Still the One', 'Orleans', 1976, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Got Your Six', 'Five Finger Death Punch', 2015, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Thunder & Lightning', 'Motörhead', 2015, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Figure It Out', 'Royal Blood', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chicken Fried', 'Zac Brown Band', 2008, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Homegrown', 'Zac Brown Band', 2015, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('The Wind', 'Zac Brown Band', 2012, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Best Song Ever', 'One Direction', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Never Enough', 'One Direction', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Story of My Life', 'One Direction', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('What Makes You Beautiful', 'One Direction', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Zombie', 'The Cranberries', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ode to My Family', 'The Cranberries', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Dreams', 'The Cranberries', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('She Looks So Perfect', '5 Seconds of Summer', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Songs Know What You Did in the Dark (Light Em Up)', 'Fall Out Boy', 2013, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Everybody Talks', 'Neon Trees', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('That''s My Kind of Night', 'Luke Bryan', 2013, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('House Party', 'Sam Hunt', 2014, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Blown Away', 'Carrie Underwood', 2012, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Cake by the Ocean', 'DNCE', 2015, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stressed Out', 'Twenty One Pilots', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Hills', 'The Weeknd', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Sorry', 'Justin Bieber', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Boyfriend', 'Justin Bieber', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Love Yourself', 'Justin Bieber', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Redneck', 'Lamb of God', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dope Nose', 'Weezer', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Do Me Like That', 'Tom Petty and the Heartbreakers', 1979, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Learning to Fly', 'Tom Petty and the Heartbreakers', 1991, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Breakfast at Tiffany''s', 'Deep Blue Something', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Take Me to Church', 'Hozier', 2014, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Jealousy', 'Gin Blossoms', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Found Out About You', 'Gin Blossoms', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hook', 'Blues Traveler', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rude', 'Magic!', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Iris', 'Goo Goo Dolls', 1998, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Radioactive', 'Imagine Dragons', 2012, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Never Too Late', 'Three Days Grace', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Africa', 'Toto', 1982, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('All These Things That I''ve Done', 'The Killers', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Lips of an Angel', 'Hinder', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Where Is My Mind?', 'Pixies', 1988, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rock This Town', 'Brian Setzer', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jumper', 'Third Eye Blind', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Uptown Girl', 'Billy Joel', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hemorrhage (In My Hands)', 'Fuel', 2000, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pompeii', 'Bastille', 2013, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Gotta Feeling', 'The Black Eyed Peas', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Blurred Lines', 'Robin Thicke ft. Pharrell', 2013, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Mr. Jones', 'Counting Crows', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Heaven Is a Place on Earth', 'Belinda Carlisle', 1987, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('If You Could Only See', 'Tonic', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Everything You Want', 'Vertical Horizon', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I''m Yours', 'Jason Mraz', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Starships', 'Nicki Minaj', 2012, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('What About Love', 'Heart', 1985, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wrong Side of Heaven', 'Five Finger Death Punch', 2013, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lifestyles of the Rich and Famous', 'Good Charlotte', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Dirt Road Anthem', 'Jason Aldean', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('All for You', 'Sister Hazel', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Dystopia', 'Megadeth', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Road to Nowhere', 'Ozzy Osbourne', 1991, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Devil in I', 'Slipknot', 2014, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('HandClap', 'Fitz and the Tantrums', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Sound of Silence', 'Disturbed', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flagpole Sitta', 'Harvey Danger', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Honey, I''m Good.', 'Andy Grammer', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Treat You Better', 'Shawn Mendes', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Happy Song', 'Bring Me the Horizon', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Safe and Sound', 'Capital Cities', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Save Tonight', 'Eagle-Eye Cherry', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Happy', 'Pharrell Williams', 2014, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Sweater Weather', 'The Neighbourhood', 2013, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Little Talks', 'Of Monsters and Men', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Closing Time', 'Semisonic', 1998, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Chandelier', 'Sia', 2014, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Feel Invincible', 'Skillet', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('King of the World', 'Weezer', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('One More Night', 'Maroon 5', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('3AM', 'Matchbox Twenty', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Closer', 'The Chainsmokers ft. Halsey', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Cheap Thrills', 'Sia ft. Sean Paul', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hold My Hand', 'Hootie & the Blowfish', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Only Wanna Be with You', 'Hootie & the Blowfish', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Let Her Cry', 'Hootie & the Blowfish', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Born Again Tomorrow', 'Bon Jovi', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lovesong', 'The Cure', 1989, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Time After Time', 'Cyndi Lauper', 1983, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('She Drives Me Crazy', 'Fine Young Cannibals', 1989, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Complicated', 'Avril Lavigne', 2002, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('My Happy Ending', 'Avril Lavigne', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('What the Hell', 'Avril Lavigne', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('24K Magic', 'Bruno Mars', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hymn for the Weekend', 'Coldplay', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Still Breathing', 'Green Day', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Starboy', 'The Weeknd ft. Daft Punk', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Waste a Moment', 'Kings of Leon', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heathens', 'Twenty One Pilots', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ride', 'Twenty One Pilots', 2015, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Shadow', 'Bearstronaut', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bethany', 'Goddamn Draculas', 2015, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Black Streak', 'Nemes', 2014, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Recognize', 'Newfane', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Never Let ''Em Hold Ya Back!', 'Parlour Bells', 2016, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('True Confessional', 'Party Bois', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Mean Girls', 'Petty Morals', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hour of Rats', 'The Red Chord', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pain Killer', 'Ruby Rose Fox', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Closer, Closer', 'The Warning Shots', 2016, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Constant Disaster', 'When Particles Collide', 2014, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Black Corridor', 'Worshipper', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Royals', 'Lorde', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('All About That Bass', 'Meghan Trainor', 2014, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Greatest', 'Sia ft. Kendrick Lamar', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Angel', 'Aerosmith', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crazy', 'Aerosmith', 1993, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Want to Miss a Thing', 'Aerosmith', 1998, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Janie''s Got a Gun', 'Aerosmith', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Livin'' on the Edge', 'Aerosmith', 1993, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rag Doll', 'Aerosmith', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wake Me Up', 'Avicii', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Celebration', 'Kool & the Gang', 1980, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Party Rock Anthem', 'LMFAO ft. Lauren Bennett & GoonRock', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Stage', 'Avenged Sevenfold', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Trust', 'Megadeth', 1997, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dead Memories', 'Slipknot', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Some Nights', 'fun.', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cheerleader (Felix Jaehn Remix)', 'OMI', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hold the Line', 'Toto', 1978, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('S.O.M.P.', 'Skratch''N Snyf', 1990, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Applause', 'Lady Gaga', 2013, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('A-YO', 'Lady Gaga', 2016, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Edge of Glory', 'Lady Gaga', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Will Survive', 'Cake', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Want to Want Me', 'Jason Derulo', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Don''t You (Forget About Me)', 'Simple Minds', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Black Betty', 'Ram Jam', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Outside', 'Staind', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Can''t Hold Us', 'Macklemore & Ryan Lewis ft. Ray Dalton', 2012, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Danger Zone', 'Kenny Loggins', 1986, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sink', 'Animal Flag', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('These Hands', 'Bent Knee', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Place for Me', 'Black Beach', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('History Repeats', 'Creaturos', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('RudeBoys', 'Dutch ReBelle', 2016, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Hurry Up (& Wait for You)', 'Julie Rhodes', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Casablanca', 'Littlefoot', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cross That Line', 'Michael Christmas', 2016, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Skydiver', 'Ruby Rose Fox', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Good', 'STL GLD', 2016, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Alone Time', 'Tigerman WOAH', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Use Somebody', 'Kings of Leon', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Will Wait', 'Mumford & Sons', 2012, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Counting Stars', 'OneRepublic', 2013, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Promise Everything', 'Basement', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Shape of You', 'Ed Sheeran', 2017, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Make My Dreams', 'Hall & Oates', 1980, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Glass House', 'Kaleo', 2013, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bizarre Love Triangle', 'New Order', 1986, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Champagne Supernova', 'Oasis', 1995, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heaven Knows', 'The Pretty Reckless', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Is How We Do It', 'Montell Jordan', 1995, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Kids', 'MGMT', 2007, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Mother Mother', 'Tracy Bonham', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Shout', 'The Isley Brothers', 1959, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Bored to Death', 'Blink-182', 2016, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('You & Me', 'The Hunna', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pull Me Under', 'Dream Theater', 1992, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Circles', 'Pierce the Veil', 2016, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Killing Is Just a Means', 'Permaband', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wrecking Machine', 'Permaband', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ain''t It Fun', 'Paramore', 2013, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freewill (Vault Edition)', 'Rush', 1980, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Cirice', 'Ghost', 2015, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('In-A-Gadda-Da-Vida', 'Iron Butterfly', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('She', 'Legitimate Front', 2012, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Gold on the Ceiling', 'The Black Keys', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hold On', 'Wilson Phillips', 1990, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Alive', 'The Temper Trap', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('True Confessions', 'Blondfire', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rebel Heart', 'The Shelters', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sweater Weather', 'Parks', 2012, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('To My Romeo', 'Spirit Kid', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Black Seas', 'Arctic Horror', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(You''re) Breakin'' Up', 'The Black Cheers', 2015, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Stupid Girl', 'Garbage', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Every Morning', 'Sugar Ray', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Postpone', 'Catfish and the Bottlemen', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stranglehold', 'Ted Nugent', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Ice Ice Baby', 'Vanilla Ice', 1990, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('I Wanna Dance with Somebody (Who Loves Me)', 'Whitney Houston', 1987, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('God Damn', 'Avenged Sevenfold', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Super Freak', 'Rick James', 1981, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Float', 'Switchfoot', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Burnin'' for You', 'Blue Öyster Cult', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('There''s Nothing Holdin'' Me Back', 'Shawn Mendes', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Down in a Hole', 'Alice in Chains', 1992, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Johnny B. Goode', 'Chuck Berry', 1959, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Play That Funky Music', 'Wild Cherry', 1976, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Super Beat Sports Big Baos Battle', 'Steve Pardo', 2017, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Blister in the Sun', 'Violent Femmes', 1983, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Sign', 'Ace of Base', 1993, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Karma Police', 'Radiohead', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Save a Horse (Ride a Cowboy)', 'Big & Rich', 2004, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Twilight of the Thunder God', 'Amon Amarth', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Run', 'Foo Fighters', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Song #3', 'Stone Sour', 2017, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Way You Used to Do', 'Queens of the Stone Age', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Attention', 'Charlie Puth', 2018, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sorry Not Sorry', 'Demi Lovato', 2017, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Thunder', 'Imagine Dragons', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Feel It Still', 'Portugal. The Man', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Come On Eileen', 'Dexys Midnight Runners', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Hooked on a Feeling', 'Blue Swede', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Enjoy the Silence', 'Depeche Mode', 1990, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Torn', 'Natalie Imbruglia', 1997, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Open Water', 'Assuming We Survive', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shy', 'HUNNY', 2017, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bloodhands (Oh My Fever)', 'In the Valley Below', 2017, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Who''s Your Lover', 'Nightmare Air', 2017, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Radio', 'No Small Children', 2017, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Remember You', 'Skid Row', 1989, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Burnin'' It Down', 'Jason Aldean', 2014, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Body Like a Back Road', 'Sam Hunt', 2017, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('That Don''t Impress Me Much', 'Shania Twain', 1997, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Takin'' Care of Business', 'Bachman–Turner Overdrive', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Sky Full of Stars', 'Coldplay', 2014, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Live in the Moment', 'Portugal. The Man', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Absolutely (Story of a Girl)', 'Nine Days', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Brick House', 'Commodores', 1977, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Slide', 'Goo Goo Dolls', 1998, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Unwell', 'Matchbox Twenty', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Want to Be', 'Gavin DeGraw', 2003, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Broken', 'Seether ft. Amy Lee', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Believer', 'Imagine Dragons', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('All You Wanted', 'Michelle Branch', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Unwritten', 'Natasha Bedingfield', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bad Company', 'Bad Company', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Roll to Me', 'Del Amitri', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Is She Really Going Out with Him?', 'Joe Jackson', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cumbersome', 'Seven Mary Three', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Stolen Dance', 'Milky Chance', 2013, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Want You', 'Savage Garden', 1997, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Run-Around', 'Blues Traveler', 1994, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Steal My Sunshine', 'Len', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Torn in Two', 'Breaking Benjamin', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Heart from Your Hate', 'Trivium', 2017, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Karma Chameleon', 'Culture Club', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Pictures of Matchstick Men', 'Status Quo', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Are Family', 'Sister Sledge', 1979, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Right Here, Right Now', 'Jesus Jones', 1991, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Forget About Tomorrow', 'The Bergamot', 2016, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Hear the Dead', 'Dolly Spartans', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Body Like That', 'The Eiffels', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Vinyl', 'Fly by Midnight', 2018, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Shame', 'Jocelyn & Chris Arndt', 2016, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Survive', 'The Warning', 2017, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Reminiscing', 'Little River Band', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Brandy (You''re a Fine Girl)', 'Looking Glass', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Baby Come Back', 'Player', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rescue Me', '30 Seconds to Mars', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Kamikaze', 'Walk the Moon', 2017, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Give Yourself a Try', 'The 1975', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Youngblood', '5 Seconds of Summer', 2018, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Will Be the Day', 'Jeff Williams ft. Casey Lee Williams', 2013, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('broken', 'lovelytheband', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sober Up', 'AJR ft. Rivers Cuomo', 2017, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Escape (The Piña Colada Song)', 'Rupert Holmes', 1979, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Red Red Wine', 'UB40', 1983, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Pictures of Girls', 'Wallows', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Simplify', 'Young the Giant', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Unheavenly Creatures', 'Coheed and Cambria', 2018, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('When the Curtain Falls', 'Greta Van Fleet', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Graffiti', 'Chvrches', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Uncomfortable', 'Halestorm', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Back to Me', 'Of Mice & Men', 2018, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Three Lives', 'Octavision', 2016, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('My Demons', 'Starset', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Time to Say Goodbye', 'Jeff Williams ft. Casey Lee Williams', 2014, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Thinking Emoji', 'Barely March', 2018, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Love That Hurts', 'PREACHERVAN', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Let''s Just Dance', 'Ships Have Sailed', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Save Yourself', 'tiLLie', 2017, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Natural', 'Imagine Dragons', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Girls Like You', 'Maroon 5', 2017, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Magic Man', 'Heart', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lose It', 'Kane Brown', 2018, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Hotel Key', 'Old Dominion', 2017, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('99', 'Barns Courtney', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Music Is Worth Living For', 'Andrew W.K.', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Angel of Death', 'Slayer', 1986, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Starlight', 'BABYMETAL', 2018, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('When Legends Rise', 'Godsmack', 2018, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Shame', 'Elle King', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Body Talks', 'The Struts', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Triumph', 'Jeff Williams ft. Casey Lee Williams', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Push', 'Matchbox Twenty', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Reason', 'Hoobastank', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wagon Wheel', 'Darius Rucker', 2013, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Bitch', 'Meredith Brooks', 1997, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Drown', 'Bring Me the Horizon', 2015, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('MANTRA', 'Bring Me the Horizon', 2019, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Paradise', 'Coldplay', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Uma Thurman', 'Fall Out Boy', 2014, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Superposition', 'Young the Giant', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('When the Seasons Change', 'Five Finger Death Punch', 2018, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('S.O.S.', 'The Glorious Sons', 2017, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do Your Worst', 'Rival Sons', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Gonna Be (500 Miles)', 'The Proclaimers', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('La Bamba', 'Los Lobos', 1987, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do Not Disturb', 'Halestorm', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Harmony Hall', 'Vampire Weekend', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Longshot', 'Catfish and the Bottlemen', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Over My Head', 'Judah & the Lion', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Salvation', 'The Strumbellas', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Tourniquet', 'Breaking Benjamin', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('When Am I Gonna Lose You', 'Local Natives', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sucker', 'Jonas Brothers', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('High Hopes', 'Panic! at the Disco', 2018, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Change', 'The Revivalists', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('100 Bad Days', 'AJR', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Alligator', 'Of Monsters and Men', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blame It on My Youth', 'Blink-182', 2019, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Gloria', 'The Lumineers', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hurt', 'Oliver Tree', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Missed Connection', 'The Head and the Heart', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Old Town Road (Remix)', 'Lil Nas X ft. Billy Ray Cyrus', 2019, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('21', 'H.E.R.', 2019, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('sugar honey ice & tea', 'Bring Me the Horizon', 2019, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('When I''m Gone', 'Dirty Honey', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Highway to Oblivion', 'DragonForce', 2019, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This City Made Us', 'The Protomen', 2015, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Two Shots', 'Duck & Cover', 2019, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Let Her Go', 'Newfane', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Time for Crime', 'ORION', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Fall Apart', 'Shocked Laura', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Blue on Black', 'Five Finger Death Punch', 2018, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Trouble', 'Five Finger Death Punch', 2017, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Might Be Right', 'White Reaper', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Feed My Frankenstein', 'Alice Cooper', 1991, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unsainted', 'Slipknot', 2019, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('CHAMPION', 'Bishop Briggs', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Good Things Fall Apart', 'Illenium & Jon Bellion', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Back Foot', 'Dinosaur Pile-Up', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Welcome Home', 'HELLYEAH', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Taste of Regret', 'Of Mice & Men', 2019, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Prom Queen', 'Beach Bunny', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Panic Attack', 'The Glorious Sons', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('16', 'Highly Suspect', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Crush', 'Dave Matthews Band', 1998, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blind Leading the Blind', 'Mumford & Sons', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('One Kind of Solomon', 'The New Pornographers', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('bad guy', 'Billie Eilish', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Orphans', 'Coldplay', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Take What You Want', 'Post Malone ft. Ozzy Osbourne & Travis Scott', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Father of All...', 'Green Day', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The End of the Game', 'Weezer', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Just Wanna Shine', 'Fitz and the Tantrums', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('All the Way (Stay)', 'Jimmy Eat World', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Circles', 'Post Malone', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Addicted', 'Simple Plan', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to My Life', 'Simple Plan', 2004, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Where I Belong', 'Simple Plan & State Champs feat. We the Kings', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('No More Mr. Nice Guy', 'Alice Cooper', 1973, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Inside Out', 'Five Finger Death Punch', 2020, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Novocaine', 'The Unlikely Candidates', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Best', 'AWOLNATION', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Colors', 'Black Pumas', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Some Kind of Disaster', 'All Time Low', 2020, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Start Now', 'Dua Lipa', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Simmer', 'Hayley Williams', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('One Man Band', 'Old Dominion', 2019, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Juice', 'Lizzo', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Bad Decisions', 'The Strokes', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Born to Be Wild', 'Steppenwolf', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rolling 7s', 'Dirty Honey', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Glycerine', 'Bush', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('With Arms Wide Open', 'Creed', 1999, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Far Away', 'Breaking Benjamin ft. Scooter Ward of COLD', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Level of Concern', 'Twenty One Pilots', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Falling', 'Trevor Daniel', 2020, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Think We''re Alone Now', 'Billie Joe Armstrong', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Van Horn', 'Saint Motel', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Popular Monster', 'Falling In Reverse', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('10,000 Hours', 'Dan + Shay & Justin Bieber', 2019, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Used To Like', 'Neon Trees', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bang!', 'AJR', 2020, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Adore You', 'Harry Styles', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Wars', 'Of Monsters and Men', 2019, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Killing Me Slowly', 'Bad Wolves', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shiver', 'Coldplay', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Speed of Sound', 'Coldplay', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Champion of the World', 'Coldplay', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Something Just Like This', 'The Chainsmokers & Coldplay', 2017, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Cradles', 'Sub Urban', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Blinding Lights', 'The Weeknd', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('History of Violence', 'Theory of a Deadman', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Antisocialist', 'Asking Alexandria', 2020, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Monsters', 'All Time Low ft. Blackbear', 2020, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('I Hope', 'Gabby Barrett', 2020, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Angels & Demons', 'Jxdn', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Some1Else', 'Blame It On Whitman', 2020, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Run With You', 'Radio Compass', 2020, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Masquerader', 'Ravi Shavi', 2020, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stevie Sees', 'Toad and the Stooligans', 2020, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Teenage Dirtbag (2020)', 'Wheatus', 2020, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Little Bit Off', 'Five Finger Death Punch', 2020, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Devil Went Down to Georgia', 'Nickelback', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('CITY OF ANGELS', '24kGoldn', 2019, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Caution', 'The Killers', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Alive With The Glory Of Love', 'Say Anything', 2004, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Cute Without The ''E'' (Cut From the Team)', 'Taking Back Sunday', 2002, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Shot in the Dark', 'AC/DC', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death by Rock and Roll', 'The Pretty Reckless', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come & Go', 'Juice WRLD & Marshmello', 2020, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Rollin'' (Air Raid Vehicle)', 'Limp Bizkit', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rebel Rebel', 'David Bowie', 1974, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Way, Soon', 'Greta Van Fleet', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stacy''s Mom', 'Fountains of Wayne', 2003, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Prisoner', 'Dance Gavin Dance', 2020, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come and Get Your Love', 'Redbone', 1974, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Golden', 'Harry Styles', 2019, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Higher', 'Shawn Mendes', 2020, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Anthem Part Two', 'Blink-182', 2001, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Hanging by a Moment', 'Lifehouse', 2000, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('bloody valentine', 'Machine Gun Kelly', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('All Downhill from Here', 'New Found Glory', 2004, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Greatest of All Time', 'New Found Glory', 2020, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('My Friends Over You', 'New Found Glory', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Visitor', 'Of Monsters and Men', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('ily (i love you baby)', 'Surf Mesa ft. Emilee', 2019, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Take Me Home, Country Roads', 'John Denver', 1971, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Let My Love Open the Door', 'Pete Townshend', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('The Bad Touch', 'Bloodhound Gang', 1999, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Fatal Illusion', 'Megadeth', 2016, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Help I''m Alive', 'Metric', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Superman', 'Goldfinger', 1997, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Way Less Sad', 'AJR', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Ex''s Best Friend', 'Machine Gun Kelly & blackbear', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Dear Maria, Count Me In', 'All Time Low', 2007, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Mindreader', 'A Day to Remember', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Paranoia', 'A Day to Remember', 2016, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Resentment', 'A Day to Remember', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Therefore I Am', 'Billie Eilish', 2020, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Running With The Wild Things', 'Against The Current', 2016, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Self Destructor', 'Chevelle', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Someone to You', 'BANNERS', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Who Do You Love?', 'George Thorogood & the Destroyers', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wild Thing', 'The Troggs', 1966, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heat Waves', 'Glass Animals', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('And So It Went', 'The Pretty Reckless ft. Tom Morello', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Follow You', 'Imagine Dragons', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Astronaut in the Ocean', 'Masked Wolf', 2019, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Astronaut in the Ocean', 'Our Last Night', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rich Girl', 'Hall & Oates', 1976, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('All My Favorite Songs', 'Weezer', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Comfort Eagle', 'Cake', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rats', 'Ghost', 2018, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sell Out', 'Reel Big Fish', 1996, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Far Too Near', 'AFI', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shake Me Up', 'HOUNDS', 2017, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Devil On My Shoulder', 'Kelsy Karter', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Kids Of Summer', 'Mayday Parade', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tailspin', 'Calling All Captains', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Bird and the Worm', 'The Used', 2007, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('take my breath away // noose', 'Capstan', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Are Between', 'Modest Mouse', 2021, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Let the Bad Times Roll', 'The Offspring', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('You''re Gonna Go Far, Kid', 'The Offspring', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Hurricane', 'I Prevail', 2019, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nowhere Generation', 'Rise Against', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Here''s to the Night', 'Eve 6', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('estella//', 'KennyHoopla ft. Travis Barker', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Drunk (And I Don''t Wanna Go Home)', 'Elle King & Miranda Lambert', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Native Tongue', 'My Kid Brother', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('good 4 u', 'Olivia Rodrigo', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freaks', 'Surf Curse', 2013, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Animals', 'Architects', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heat Above', 'Greta Van Fleet', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Girl Scout Cookies', 'Mom Jeans.', 2016, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Like No Surprise', 'Oldsoul', 2020, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Title Track', 'Origami Angel', 2019, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Cosmic Thrill Seeking Forever', 'Prince Daddy & The Hyena', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Wanna Dance with Somebody (Who Loves Me)', 'Fall Out Boy', 2018, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blue Monday', 'Orgy', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Africa', 'Weezer', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Time Warp', 'Little Nell, Patricia Quinn & Richard O''Brien', 1975, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Flavor of the Weak', 'American Hi-Fi', 2001, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Euphoria', 'Angels & Airwaves', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('MONTERO (Call Me by Your Name)', 'Lil Nas X', 2021, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('A-O-K', 'Tai Verdes', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shimmer', 'Fuel', 1998, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pathkeeper', 'Interloper', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Physical', 'Olivia Newton-John', 1981, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Paralyzed', 'Sueco', 2021, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Peg', 'Steely Dan', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Grand Canyon', 'The Wind and The Wave', 2016, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chelsea Dagger', 'The Fratellis', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Call', 'Ego Kill Talent', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Can''t Drive 55', 'Sammy Hagar', 1984, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hazy Shade of Winter', 'The Bangles', 1987, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Missing Piece', 'Vance Joy', 2021, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cold Heart (PNAU Remix)', 'Elton John - Dua Lipa', 2021, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('brutal', 'Olivia Rodrigo', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Face Down', 'The Red Jumpsuit Apparatus', 2006, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('A Decade Under the Influence', 'Taking Back Sunday', 2004, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('¡Olé!', 'The Bouncing Souls', 1999, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Fall Apart', 'Light the Torch', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('DiE4u', 'Bring Me the Horizon', 2021, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Only Love Can Save Me Now', 'The Pretty Reckless ft. Matt Cameron & Kim Thayil', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sk8er Boi', 'Avril Lavigne', 2002, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Memory', 'Sugarcult', 2004, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ain''t No King', 'The Almost', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Secret Garden', 'Spiritbox', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Light My Love', 'Greta Van Fleet', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay (I Missed You)', 'Lisa Loeb', 1994, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Clockwork Expectation', 'Fractal Universe', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Earth Is A Black Hole', 'Teenage Wrist', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Show Me the Way (Live)', 'Peter Frampton', 1976, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dreaming', 'Blondie', 1979, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('abcdefu', 'GAYLE', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay High', 'Brittany Howard', 2019, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Respect', 'Aretha Franklin', 1967, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Jolene', 'Dolly Parton', 1974, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Waking Up In Vegas', 'Katy Perry', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Man! I Feel Like a Woman!', 'Shania Twain', 1997, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Love It When You Hate Me', 'Avril Lavigne ft. Blackbear', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dead Inside', 'Nita Strauss ft. David Draiman of Disturbed', 2021, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Chaise Longue', 'Wet Leg', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Devil''s Radio', 'The Velveteers', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tonight', 'Magnolia Park ft. Lil Lotus', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Matilda', 'PUP', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Gepetto', 'Belly', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Connection', 'Elastica', 1995, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Mouth Shut', 'Lit', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bury Me (Tonight!)', 'Save Face', 2021, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Broken', 'Alfie Templeman', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('It''s Been a Little Heavy Lately', 'Joesef', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Won''t Give It Up', 'Beartooth', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Pretty Mouth', 'girlfriends', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Ready for Combat', 'Icon for Hire', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Down', 'St. Vincent', 2021, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Making a Fire', 'Foo Fighters', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('You Should Be Dancing', 'Dee Gees', 2021, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Devils Haircut', 'Beck', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Saw Lightning', 'Beck', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sexx Laws', 'Beck', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('California Dreamin''', 'Dirty Honey', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Seether', 'Veruca Salt', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Cat''s in the Cradle', 'Harry Chapin', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Distance', 'Mammoth WVH', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Liars Club', 'Coheed and Cambria', 2022, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Fight for Your Right', 'Beastie Boys', 1986, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Bring tha Noize', 'Public Enemy ft. Anthrax', 1991, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('I Think I''m OKAY', 'Machine Gun Kelly, YUNGBLUD & Travis Barker', 2019, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Funeral', 'YUNGBLUD', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Really Like You', 'Carly Rae Jepsen', 2015, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('she''s all i wanna be', 'Tate McRae', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wild Child', 'The Black Keys', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Black Summer', 'Red Hot Chili Peppers', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('when we were young', 'Architects', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Just Pretend', 'Bad Omens', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Anything Was Better', 'The Interrupters', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Let Go', 'Potty Mouth', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Brand New', 'Bob Moses', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Hills', 'The Faim', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Like You', 'Bloods & Laura Jane Grace', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Take Me Away', 'Fefe Dobson', 2003, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('City of the Dead', 'Hollywood Undead', 2022, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Foundations of Decay', 'My Chemical Romance', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Starlight', 'Muse', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Won''t Stand Down', 'Muse', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Mother We Share', 'CHVRCHES', 2013, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('What You Know', 'Two Door Cinema Club', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Iris', 'New Found Glory', 2007, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Man Who Sold the World (Live)', 'Nirvana', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Mercy Me', 'Alkaline Trio', 2005, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Runaway', 'Starcrawler', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Headsweat', 'The Foxies', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Oldest Daughter', 'The Wonder Years', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Blood for the Blood God', 'Ben Quad', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('End of the World', 'Gulfer', 2021, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Where the Heart Is', 'Sweet Pill', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Bombs Away', 'Blastergun', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('DIE OUT HERE', 'DE''WAYNE ft. POORSTACY', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Life Was Easier When I Only Cared About Me', 'Bad Suns', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('F.C.P.R.E.M.I.X.', 'The Fall of Troy', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Canned Heat', 'Jamiroquai', 1999, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Hard Times', 'Paramore', 2017, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Rollercoaster', 'Bleachers', 2014, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Soak Up the Sun', 'Sheryl Crow', 2002, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Pallbearer Walks Alone', 'The Dark Element', 2019, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Can''t Wait', 'Ceramic Animal', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Ain''t Worried', 'OneRepublic', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Fence Me In', 'Amyl and the Sniffers', 2021, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Kiss Me Deadly', 'Lita Ford', 1988, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Bonnie', 'Cuffed Up', 2021, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crash Into Me', 'Dave Matthews Band', 1996, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Radio Reject', 'Magnolia Park', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Pass the Nirvana', 'Pierce the Veil', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Classless Act', 'Classless Act ft. Vince Neil of Mötley Crüe', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Groove Is in the Heart', 'Deee-Lite', 1990, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Numb', 'Marshmello and Khalid', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Loved You a Little', 'The Maine, Taking Back Sunday, and Charlotte Sands', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('No Apologies', 'Papa Roach', 2022, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Going Home to a Party', 'JW Francis', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Reelin'' In the Years', 'Steely Dan', 1972, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Given Up', 'Linkin Park', 2007, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Circles', 'Varials', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dangerous', 'Set It Off', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Smile', 'Wolf Alice', 2021, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sacrifice', 'The Devil Wears Prada', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Crosses', 'Sleeping With Sirens ft. Spencer Chamberlain of Underoath', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Better Together', 'Jack Johnson', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Super Freaky Girl', 'Nicki Minaj', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Goodbye, Good Luck', 'BEGINNERS', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Worst Day', 'ILLENIUM & Max', 2022, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Bad Idea', 'GUNNAR', 2023, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Little Bit Better', 'Ni/Co', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Here & Now', 'Letters to Cleo', 1993, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I''ll Be There for You (Theme from Friends)', 'The Rembrandts', 1995, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('High Society', 'My Kid Brother', 2022, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Take on Me', 'Reel Big Fish', 1998, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Out', 'The Blue Stones', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love From the Other Side', 'Fall Out Boy', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Is Why', 'Paramore', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('L.E.S.', 'The Revel', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Gang''s All Here', 'Skid Row', 2022, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('More the Victim', 'Linkin Park', 2023, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Down to the Devil', 'Naked Gypsy Queens', 2022, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Until I Found You', 'Stephen Sanchez', 2021, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mountain Sound', 'Of Monsters and Men', 2011, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('PANIC', 'YONAKA', 2023, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Dial Tone', 'Catch Your Breath', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Peace That Starts the War', 'Wolves At The Gate', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mary on a Cross', 'Ghost', 2019, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ultraviolet', 'Spell', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Back to Better', 'The Bouncing Souls', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('lovespell', 'covet', 2023, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Oh!', 'The Linda Lindas', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Nobody', 'Avenged Sevenfold', 2023, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Voices In My Head', 'Falling In Reverse', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Goo Goo Muck', 'The Cramps', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rescued', 'Foo Fighters', 2023, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Cannonball', 'AWOLNATION', 2018, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Girls Make Me Wanna Die', 'The Aces', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Settling', 'Ripe', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crossfire', 'Stevie Ray Vaughan and Double Trouble', 1989, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('All That She Wants', 'Ace of Base', 1993, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('White Trash Millionaire', 'Mom Jeans.', 2022, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Born in the Heat', 'CIVIC', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Be Normal', 'Militarie Gun', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Mind Rider', 'Hail the Sun', 2023, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Through the Noise', 'Nita Strauss ft. Lzzy Hale', 2023, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Big Rig', 'Pigs Pigs Pigs Pigs Pigs Pigs Pigs', 2023, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heartbreaker 2.0', 'Dirty Honey', 2023, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bad Things', 'I Prevail', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Homesick', 'HUNNY', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Locked & Loaded', 'The Brevet', 2018, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Believe', 'The Bravery', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Delete Myself', 'Fake Names', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Makeshift Vehicles', 'Body Thief', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Medicine', 'Tiny Moving Parts', 2019, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Rain Down', 'Solence', 2023, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Alexis Munroe', 2023, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heartbreak Of The Century', 'Neck Deep', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Fall', 'flipturn', 2022, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('IDWBS', 'Friday Pilots Club', 2022, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Summoning', 'Sleep Token', 2023, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Masters Of Morbidity', '200 Stab Wounds', 2022, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('You''re The Best', 'Joe Bean Esposito', 1984, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love U Madly', 'Violet Saturn', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pack of Smokes', 'Blame It On Whitman', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Black Earth, WI', 'Ratboys', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('She''s Got Sorcery', 'I Fight Dragons', 2021, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Call Me Crazy', 'ARXX ft. Pillow Queens', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Season 5 (Break My Fall)', 'TOWNS', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Is Not A Weapon', 'Welshly Arms', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Little Wild', 'Anna Graceman & Ryan Corn', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('All I Really Wanna Do', 'Devon Gilfillian', 2023, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Miles And Miles', 'The Heavy Heavy', 2020, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Welcome Home', 'Heaven''s Basement', 2013, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sickness', 'Grey Daze', 2020, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Addison Rae', 'Magnolia Park', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Six Feet Under', 'Charlotte Sands', 2023, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Riptide', 'Beartooth', 2022, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Brassic', 'Grade 2', 2023, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('It''s Alright', 'Cecilia Castleman', 2022, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bath Country', 'Wednesday', 2023, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']);