-- Part 3
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Beautiful Machine', 'Rose of Jericho', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Real Love', 'RED9', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Throughout', 'Done Lying Down', 1995, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Tomorrow She''s Mine', 'Rod Kim', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Why Bother?', 'Scratching the Itch', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Big Deal', 'HourCast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Black Cloud', 'Scott Gehrett', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Burst Into Fears', 'SexTon', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hard to See', 'Five Finger Death Punch', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Told You Once', 'The Apples in Stereo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Death By Cancer', 'Seppuku With a Straw', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Flicker', 'Widespread Panic', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('In My Head, Out My Head', 'Primary', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Liberated by Blasphemy', 'Adam Evil', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nom Nom Nom Nom Nom Nom Nom', 'Parry Gripp', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Seven', 'Sunny Day Real Estate', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Simple Man', 'Highlord', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('So Easy', 'Blue News', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Ultimate Showdown (RBN Mix)', 'Lemon Demon', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tora Tora Tora', 'Pretty & Nice', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('War Against the Radio', 'Audio Ammunition', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wytches 2010', 'Inkubus Sukkubus', 2010, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Piranha', 'Pretty & Nice', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('So Awesome', 'The Shazam', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Why', 'C. J. Ramone', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Lights Out', 'Hyro da Hero', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('The Anthem of the Angry Brides', 'Norma Jean', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ain''t Life Grand (Live)', 'Widespread Panic', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Attraction', 'HourCast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Filthy Dog', 'Aittala', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Happy Little Tune', 'DeBaser', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Leaderless and Self Enlisted', 'Norma Jean', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pedal Down', 'Assembly of Dust', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Right Now Romeo', 'Mason Douglas feat. Blue Morning', 2004, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Deathbed Atheist', 'Norma Jean', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Do It to Me', 'C. J. Ramone', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Love Song', 'No Justice', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Take Me Away', 'Rose of Jericho', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Final Episode (Let''s Change the Channel)', 'Asking Alexandria', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Until the Night', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Embrace Your Rage', 'Kramus', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jigsaw Man', 'Wargasm', 1995, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Come Along', 'XTT', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Here and Gone', 'Sullivan DeMott', 2009, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Elevator', 'The Apples in Stereo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Collapse (Stalker)', 'Brett Merrill & Brendan Carell', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Blinded', 'Down Factor', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Charmed', 'OWL', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Curse You All Men! (Live)', 'Emperor', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Desperate Days', 'Jenium', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Doublecrossed', 'Valient Thorr', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hell or Hollywood', 'HourCast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Inno a Satana (Live)', 'Emperor', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No Mercy', 'Tijuana Sweetheart', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('No One''s Gonna Love You', 'Band of Horses', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rollercoaster', 'Sleater-Kinney', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Surf Spy', 'The Everybody', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('To the Otherside', 'A t o m', 2009, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Blood Red Rock', 'Bang Camaro', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Plague to End All Plagues', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Electro-Heaven', 'Robby Suavé', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Incubus', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('No One In the World', 'The Apples in Stereo', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fighting Back the Bullies', 'XTT', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sabretooth', 'Stars of Boulevard', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Every Day Is Sunday', 'The Slackers', 2008, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Just Hang On', '2nd Thought', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Disaster', 'The Gufs', 2006, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Chiron Beta Prime', 'Jonathan Coulton', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Done', 'The Giraffes', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Guitar Sound', 'Ronald Jenkees', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Guitars SUCK', 'Bumblefoot', 2001, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Muéstrame un Poco', 'Buffalo Mad', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shallow Waters', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Strut', 'The Elms', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Betty and Me', 'Jonathan Coulton', 2004, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Anna Maria (All We Need)', 'We the Kings', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Believe', 'MJ Kroll', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lately', 'Day of Fire', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rain Falls Down', 'We the Kings', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Spin', 'We the Kings', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('What You Do to Me', 'We the Kings', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wrong Side of the Tracks', 'Hugh Cornwell', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Genocide', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Hope You''re Happy', 'Loren Dircks', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Magician', 'Lightwires', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Summer Love', 'We the Kings', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Building a Robot', 'Robotmakers', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Entertain', 'Sleater-Kinney', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('(Do You Wanna Date My) Avatar', 'The Guild feat. Felicia Day', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('A Prophecy', 'Asking Alexandria', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Crazy X', 'Charlie Drown', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hey There Mr. Brooks', 'Asking Alexandria', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Satisfied', 'Social Code', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Great Salt Lake', 'Band of Horses', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Satomi (feat. Justine Skyers)', 'The Bungles', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jumpers', 'Sleater-Kinney', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shoot the Zombies', 'Songs To Wear Pants To', 2007, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('The Last Sound', 'Grammatrain', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Heavy Plastic', 'Alien Downlink', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('On the Airwaves', 'The Shazam', 2000, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rabbits', 'Kingsize', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Like the Moon', 'Rathergood.com', 2003, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Belladonna & Aconite 2010', 'Inkubus Sukkubus', 2010, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('In Circles', 'Sunny Day Real Estate', 1994, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Broke Down on the Brazos', 'Gov''t Mule', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Echo (My Only Regret)', 'SexTon', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Forgotten Tragedy', 'Cold Steel', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('O Come, O Come Emmanuel', 'Christmas at the Devil''s House', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Swim', 'Surfer Blood', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Pose', 'Red Jacket Mine', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('(Random Song)', 'Bluefusion', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Floating Vibes', 'Surfer Blood', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mr. Spock', 'Nerf Herder', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Ending Is Death', 'Boney Mean', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Damn Good Man', 'Moses Tucker', 2009, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Devoid of Thought', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fence Jumper', 'The Fire Violets', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Flesh Pull', 'Mystic Syntax', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hell''s Sweet Hands', 'Ashland Court', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Kokko - Eagle of Fire', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Song About an Angel', 'Sunny Day Real Estate', 1994, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Uncivilized', 'Texas in July', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('You Ain''t No Family', 'iwrestledabearonce', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Your Petty Pretty Things', 'The Get Up Kids', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Howling at Summer', 'You Me and Iowa', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Cut Off My Arms', 'J.A.C.K.', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I MAED A GAM3 W1TH Z0MB1ES 1N IT !!!1', 'James Silva', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spring', 'Your Heart', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('XIV', 'Chaotrope', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Honest Man', 'The Gracious Few', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Living in a Whirlwind', 'Warbringer', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Money Honey', 'State of Shock', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pawns', 'Dead by Wednesday', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Time No More', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Violent Center', 'OWL', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burn Her Out', 'Shokkher', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Buy You a House', 'Noah Engh The Kid Fantastic', 2010, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Cherry Red', 'Sideburn', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Disco Rocket', 'Scott Attrill', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Lionheart', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Return to Blood Beach', 'The Riptides', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Time-bomb', 'Buttercup', 1997, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to My World', 'Nerf Herder', 2002, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('White Table', 'Delta Spirit', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Evil Inside Me', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Head Up High', 'Firewind', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pale Sister of Light', 'Free Spirit', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Revolution', 'Bang Camaro', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Determined (Vows of Vengeance)', 'Kataklysm', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Girls Love Techno', 'Scott Attrill', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Beautiful Girl', 'Sophie B. Hawkins', 2004, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bridges and Overpasses', 'Modern Skirts', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Down Below', 'Kramus', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fool', 'Brownies', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''ve Got a Feeling', 'Blackberry River Band', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('iPhone', 'Rhune Kincaid', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Picture Perfect', 'The Fury', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ring Capacity', 'Kirby Krackle', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Skate or Die', 'Teenage Bottlerocket', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Gun Show', 'In This Moment', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Pizza Morgana Song', 'Hilit Rosental and Corbomite Games', 2009, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('United', 'The Knew', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Latest Heartbreak', '22-20s', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Modern Mathematics', 'Terrorhorse', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to Our Town', 'Stagehands', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('World on Fire', 'Firewind', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Your Hands (Together)', 'The New Pornographers', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Appetite', 'The Gracious Few', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Mike Orlando', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dial M for Murder', 'The Riptides', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Difference', 'Rivethead', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dirty Hair Party', 'Pink Flag', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Erratic Eruption', 'Freen in Green', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Hello Fascination', 'Breathe Carolina', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Want You to See', 'Justin Joseph Edwards', 2010, 'Jazz', false, true, true, ARRAY['Rock Band DLC']),
('Radioland', 'Audible Mainframe', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Stick Tight', 'Terror', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The One You Want', 'The Get Up Kids', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Army of the Damned', 'Pythia', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Couldn''t Explain Why', 'Citizen Cope', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''m Amazed', 'My Morning Jacket', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Smash the Control Machine', 'Otep', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Americadio', 'Slim Cessna''s Auto Club', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Chasing the Light', 'Nautiluz', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cup of Coffee', 'The Novocaines', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Epic Symphony in A Flat Minor, First Movement: Marching Out', 'Van Friscia', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Ready for Anything', 'SexTon', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Steppin'' Lightly', 'Gov''t Mule', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Threads', 'Barefoot Truth', 2010, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Holy Ground', 'New Rising Son', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Kiss Kiss Bang Bang', 'Ultra Saturday', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Roman Candle', 'Pink Flag', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Shiver', 'Amy Courts', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('999,999 Girls!', 'Kiss the Girl', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Discharge', 'Intricate Unit', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Elevator', 'Kingsize', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Flightless Bird, American Mouth', 'Iron & Wine', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Giant Magnets', 'Desoto Jones', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hanuman', 'Rodrigo y Gabriela', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Indulgence', 'Self-Titled', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Light', 'Shylo Elliott', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Saint Simon', 'The Shins', 2003, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('BBQ Nation', 'Graveyard BBQ', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bittersweet Melancholy', 'Shylo Elliott', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Dying Wish of a Living Man', 'Yesternight''s Decision', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Headed for the Ditch', 'Andy Timmons', 2006, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Laceration', 'Mile Marker Zero', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Midnight Eyes', 'Rose of Jericho', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mrs. Right', 'Last Day Off', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Thank You, Pain.', 'The Agonist', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Buttersnips', 'Periphery', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dirt', 'Rain Dogs', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Electricity is in My Soul', 'Steam Powered Giraffe', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Far Wanderings', 'Shylo Elliott', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('High Class Trailer Trash', 'Shelly Rastin feat. Randy Bachman', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('How We Operate', 'Gomez', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Now or Never', 'Confide', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Saga', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Warmachine', 'The Sex Generals', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Arcaedion', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Chilly Water (Live)', 'Widespread Panic', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Forgot Love', 'Public Radio', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Girlfriend', 'Shy Nobleman', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Johnny Ace 2010', 'Dash Rip Rock', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rain', 'New Rising Son', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Right to the Apex', 'Single White Infidel', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Signed With Love', 'Rose of Jericho', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Surprise Valley (Live)', 'Widespread Panic', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Deceiver', 'I Am Abomination', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Permanent Rain', 'The Dangerous Summer', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Bang Bang Bang', 'The Virginmarys', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Daisy', 'Fang Island', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Old Lady Trouble', 'Steve Fister', 2009, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('Rotten Cat Halloween Rat', 'Boney Mean', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Second & Sebring', 'Of Mice & Men', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Spill', 'Nushu', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Standing in Your Stuff', 'Zigaboo Modeliste', 2000, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Wake Up', 'Suicide Silence', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Antman', 'The Red Chord', 2005, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Frostbite Cavern', 'Wolfblur', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hand Me Down', 'Visqueen', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nihilanth', 'Gatling', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Snowmaiden', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Touch', 'Stan Bush', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('White Knuckles', 'OK Go', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('All I Want', 'Cosmic Tribe', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Drum Exercises for the Sufficiently Masochistic', 'Shylo Elliott', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Thought I Knew You', 'Those Among Us', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Miss America', 'Kingsize', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Philip K. Ridiculous', 'Hugh Cornwell', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Refugee', 'Scotty Don''t', 2008, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Soulless', 'Fake Problems', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Way You Move', 'Since October', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bullet with a Name', 'Nonpoint', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Ceraunophobia', 'Chaotrope', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dark Horse', 'Converge', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gabrielle', 'Ween', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Ghost I Own', '(Damn) This Desert Air', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('P.W.M.O.', 'Shylo Elliott', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Countdown', 'Cliff Lin', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Waiting One', 'All That Remains', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Worst Case Ontario', 'The Roman Line', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Curtain Call', 'Nations Afire', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fate of the Maiden', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hold On', 'All That Remains', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Industrialized', 'Bluefusion', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Let Us Slay', 'GWAR', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ride the Stache', 'Graveyard BBQ', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Runaway', 'Lyrics for Monday', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Tantrums of a Giant', 'Madlife', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Think Bad Thoughts', 'Kay Hanley', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Vacation', 'Mike Belotti & Theo Christensen', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Veils', 'Ludicra', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Baptized by Fire', 'Chaotrope', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Berzerker', 'After the Burial', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Jack and the Harlots', 'The Asbestos', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Obfuscation', 'Between the Buried and Me', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Robots May Break Your Heart', 'Riverboat Gamblers', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Allegiance', 'Blackguard', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Best I Never Had', 'The Downtown Fiction', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Just Wanna Run', 'The Downtown Fiction', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Let It Change', 'Mystic Syntax', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Smokahontas', 'Attack Attack!', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stevie', 'Songs To Wear Pants To', 2010, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Better Sleep', 'Fatter Than Albert', 2008, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('For We Are Many', 'All That Remains', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Linear A', 'Free Electric State', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Living Saints', 'Polar Bear Club', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Oceans Between Us', 'The Downtown Fiction', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('On Parole', 'Sister Sin', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spira Mirabilis', 'Kodomo', 2008, 'Urban', false, true, true, ARRAY['Rock Band DLC']),
('Two Minute Warning', 'Hitman Blues Band', 2003, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('A Christmas Rock Medley', 'Richard Campbell', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Apocalypse for Breakfast', 'Coelacanths', 2011, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Beyond Grey', 'Silent Descent', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Epitome of Misery', 'Broken Equilibrium', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fox Hunt', 'Larkspur', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('I Still Feel Her, Part III', 'Jonny Craig', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Icon', 'A t o m', 2010, 'New Wave', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Lay Kenneth Lay', 'Felsen', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Life Design', 'The Parlotones', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Numb & Intoxicated', 'Kataklysm', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Phantom Limb', 'The Shins', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shut Up', 'The Early Strike', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Herlathing', 'Morgawr', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lemon Meringue Tie', 'Dance Gavin Dance', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('One More Time', 'Big Kenny', 2009, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Alpha Strike', 'Shylo Elliott', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Angels We Have Heard on High', 'Cate Sparks', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do You', 'Portugal. The Man', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Endzeit', 'Heaven Shall Burn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flag in the Ground', 'Sonata Arctica', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Have Faith in Me', 'A Day to Remember', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Lipstick Cigarette', 'The Last Good Year', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lollytown', 'Mike Phirman', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Me Elevas', 'Judy Buendía y Los Impostores', 2008, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Model Ships', 'Rosaline', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('November', 'Broken Equilibrium', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Run Rabbit Run', 'Hellfire Society', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Saw Down (He Knows)', 'D Money Pros', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('So Fine', 'The Break Down', 2009, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Strobe Lights', 'Kill Hannah', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Truth', 'Kittie', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Alive and Kicking', 'Nonpoint', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Drive', 'Michael John Ahern', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Fashion Kills', 'Sabrosa Purr', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Going Under', 'Evanescence', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('She''s a Runaway', 'Partially Poetic', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unbound Soul', 'Dan Johansen', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Vuvuzela Anthem', 'Strayplay', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('10 Signs You Should Leave', 'Emmure', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('[&] Delinquents', 'Woe, Is Me', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Catalyst', 'Raven Quinn', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Creatures ov Deception (RB2 Version)', 'Rainbowdragoneyes', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Do Yourself a Favor', 'Comeback Kid', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Donuts, Go Nuts!', 'Matt ''Chainsaw'' Chaney', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Escaping', 'Driven By Entropy', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fallen', 'Rain Dogs', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Firewall', 'Fear of Water', 2009, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hallway', 'Bojibian', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey Baby, Here''s That Song You Wanted', 'Blessthefall', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jam', 'Philip Franco', 2010, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Rescue Spreaders', 'Garage A Trois', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stereo Stereo', 'I Am King Tony', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Swallow My Children', 'BS (A. Whiteman)', 2010, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('The Body', 'Close Your Eyes', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The History of Execution (featuring Bluefusion)', 'Single White Infidel', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Hounds of Anubis', 'The Word Alive', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('(Lone Wolf) Soccer Mom', 'Blanks.', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Another Round', 'Dirty Filthy Mugs', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Cimmerian Shamballa', 'Wretched', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Esto ya lo Toqué Mañana', 'Octavio Suñé', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Eternal Divine Angel Death', 'Daas Bosh', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gone Tomorrow', 'Arkaea', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Iceblind', 'Freen in Green', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Lodger', 'Blanks.', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lost', 'John Garrison', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('No Pertenezco', 'Incordiales', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('OaOaO', 'The Taj Motel Trio', 2007, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Party Like a Rock Star', 'Big Engine', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pouncer', 'Blanks.', 2006, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Power Patriot', 'Garage A Trois', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Princess (Reprise)', 'Lee DeWyze', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Relentless Chaos', 'Miss May I', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Splosion Man Theme Song', 'Raging Meats', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay Awake', 'Faithful Darkness', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Stop', 'FeelAbouT', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Brave / Agony Applause', 'Deadlock', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Clothes That Makes the Man', 'Graveyard BBQ', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Omen', 'Heaven Shall Burn', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Serpentine Offering', 'Dimmu Borgir', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Vault 101', 'Kirby Krackle', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('What Morning Brings', 'She Bears', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Epic Symphony in A Flat Minor, Second Movement: Blitz', 'Van Friscia', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Feast or Famine', 'Within the Ruins', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Heart of Lilith 2010', 'Inkubus Sukkubus', 2010, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Humanity''s Last Hope...', 'Massive Slavery', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Cold Taste of Nickel Plated Steel', 'All Hallow''s Evil', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Twister', 'Scott Attrill', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Dawn of a Million Souls (Rock Band Mix)', 'Ayreon', 2000, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Fractured (Everything I Said Was True)', 'Taproot', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Queen of the May 2010', 'Inkubus Sukkubus', 2010, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Special Effects', 'Freezepop', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('The Fire and the Fury', 'Firewind', 2003, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('2 Invade (Stadium Mix)', 'Scott Attrill', 2009, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('24-7', 'The Pursuits', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('All I Want', 'A Day to Remember', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Clockwork', 'HourCast', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('It''s Complicated', 'A Day to Remember', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Lindisfarne', 'Morgawr', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Reaper', 'Chaotrope', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Healing', 'Ivoryline', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Til All Are One', 'Stan Bush', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Years in the Darkness', 'Arkaea', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Battlesoul', 'Battlesoul', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Control', 'BulletProof Messenger', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nocturnal Wasteland', 'Freen in Green', 2010, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Real', 'Bumblefoot', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stay Here Forever', 'The Material', 2011, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('The Pale Rider', 'The Riptides', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Action/Adventure', 'Memphis May Fire', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Angel', 'Hellfire Society', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Forever the Martyr', 'Dirge Within', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('In Case You Forgot', 'Deception of a Ghost', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('La Fórmula', 'Sintonía Retro', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('N.A.T.G.O.D.', 'Dååth', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Something Face', 'Sun Domingo', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Transmission Lost', 'Terra Terra Terra', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('White Knuckles - The Big Robot Remix', 'OK Go', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('A Slight Amplification', 'Turrigenous', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('All I Need', 'Monte Casino', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('At the Edge of the World', 'Kataklysm', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Beauty is Deceiving', 'Grieve for Tomorrow', 2010, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Brand New Toy', 'Blackberry River Band', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Caíamos', 'Octavio Suñé', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Call Me', 'The Riptides', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Call to the Warrior', 'Affiance', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Creamskull Boogie', 'Graveyard BBQ', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Enemy', 'First Blood', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Falling Apart', 'BSM', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hundred Wrathful Deities', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('It''s Gonna Be a Long Night', 'Ween', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jamie All Over', 'Mayday Parade', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Just Refrain', 'Orange Avenue', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Livin'' Right', 'DoubleShot', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lullaby', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Marianas Trench', 'August Burns Red', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Morning Star', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nightfall', 'Nachtmystium', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rompecabezas', 'Judy Buendía y Los Impostores', 2008, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Sexual Man Chocolate', 'Attack Attack!', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sunrise', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Fall of Aphonia', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('The King is Dead', 'Victory in Numbers', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Podium', 'We Are The Illusion', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Those in Glass Houses', 'Of Mice & Men', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('We Are Kings', 'Crush Luther', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Collide', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Abrogator', 'Six-Stringed Flamberge', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Autumns of Optimism', 'Mystakin', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Cheyne Stokes', 'Chelsea Grin', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Coat Rack', 'Ride Your Bike', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cursing Akhenaten', 'After the Burial', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Decadence', 'Raven Quinn', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dog Like Vultures', 'Haste the Day', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dominate and Overload', 'Fracture', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lexington (Joey Pea-Pot With a Monkey Face)', 'Chiodos', 2007, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('New Revolution', 'The Waking Hours', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Second Sight Blackout', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Shorty On The Floor', 'Horporate', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('The Last Gasp', 'Impaled', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Resonance', 'Decrepit Birth', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Undead Heart', 'Vampires Everywhere!', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Whites in Their Eyes', 'Fiction Reform', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('5678', 'Fake Problems', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Abraxas of Filth', 'Cephalic Carnage', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('An Eluardian Instance', 'of Montreal', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Black and Sunny Day', 'Glitzy Glow', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blasphemous', 'Mystic Syntax', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('California', 'Nova', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Closer to the Sun', 'Slightly Stoopid', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Come On In', 'The Pinstripes', 2009, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Goin'' Home', 'KickBend', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hand Me Down', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hanging By a Thread', 'Jeff Orr', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hotel Saigon', 'Bright Midnight', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Icarus Lives', 'Periphery', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('If I''m James Dean, You''re Audrey Hepburn', 'Sleeping with Sirens', 2010, 'Emo', false, true, true, ARRAY['Rock Band DLC']),
('Killers of the Worst Type', 'Bright Midnight', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Learn to Live', 'Architects', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lift', 'Poets of the Fall', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lost Boys', 'MyChildren MyBride', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Metamorphosis', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('My Parasite', 'Evile', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('New Addiction', 'Dark From Day One', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('On the Wall', 'Molehill', 2007, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('One-Night-Stand Man', 'Daryle Stephen Ackerman', 2006, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Samiam', 'Mafia Track Suit', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Sons of Seven Stars', 'Amberian Dawn', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Step on the Throat', 'C&O', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Order', 'Children of Nova', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Arm Yourself', 'BulletProof Messenger', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Aspiration', 'After the Burial', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Butcher''s Mouth', 'Emery', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Coolguy Deluxe!', 'Kid Liberty', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Holiday', 'The Night Life', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('My Wings Are My Eyes', 'Amberian Dawn', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Ode to Logan', 'No Bragging Rights', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Pandemonium', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The December Experience', 'Lnk. Ken Kardashian', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('ZTO', 'Devin Townsend', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('All or Nothing', 'Cauldron', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Around the World', 'Robby Suavé', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bang', 'Rockapella', 2010, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('Barricades', 'Lucid Grey', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bend', 'New West', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Betrayed', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Big Bad World One', 'Jonathan Coulton', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bitten by the Rattlesnake', 'Admiral of Black', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Bizarro Genius Baby', 'MC Frontalot', 2007, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Bullet on a String', 'Rotary Downs', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cluster #2 (RB2 Version)', 'Jacob Chaney', 2010, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Couch Sitting Rattlesnake', 'Stuedabakerbrown', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fighting Spirit', 'Bluefusion', 2009, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Firehouse Bar', 'Kylie D. Hart', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('For the Strange', 'Bright Midnight', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hassle: The Dorkening', 'MC Frontalot', 2005, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Hate to Say', 'Common Anomaly', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('I Gotta Ride 2010', 'Sam Morrison Band', 2010, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('King of Frauds', 'With Life in Mind', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Last Suppit', 'Lettuce', 2008, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Light Up The Eyes', 'These Three Poisons', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Live to Rock', 'Sideburn', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mind Diary', 'Cloudscape', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Plátanos Con Sangre', 'Zakk Tremblay', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Promised Land', 'Rotary Downs', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pylo the Pylon', 'Alternative Deficit Disorder', 2009, 'Novelty', false, true, true, ARRAY['Rock Band DLC']),
('Radios Tweaking', 'Felsen', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Secondary Gain', 'Abraham Nixon', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Steven Wells (He Was the Greatest)', 'Akira the Don', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Strong Tower', 'Kutless', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Too Much', 'Soulive', 2009, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Triceratops', 'Big Light', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Two Utensils In One', 'Felsen', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Volver a Nacer', 'Arena', 2010, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('You Don''t Know', 'The Moth Complex', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('A Fresh Start', 'Mystakin', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Abigail', 'Motionless in White', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Crinoline', 'CyLeW', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('District of Misery', 'Oceano', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('For You', 'Maplerun', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lamnidae', 'This or the Apocalypse', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Painprovider', 'Cosmic Ballroom', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rational Animal/Layered Line', 'Kiev', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Refraction', 'Ricky Graham', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Seed of Discord', 'Hellfire Society', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Skid Rock', 'A Wilhelm Scream', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Supernova', 'High Voltage', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tea and Taxes', 'Jenium', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Voodoo Treasure', 'Majestic', 2000, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('We Are But Instruments', 'Where the Ocean Meets the Sky', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Your Treachery Will Die with You', 'Dying Fetus', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Lights Out', 'Minutes Like Ours', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Live for Today', 'Enemy Remains', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Burn', 'Captor', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Come Outside', 'Anybody Who''s Anybody', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Disco Ball', 'Those Among Us', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Passion of My Life', 'Perfect Hero', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Septilogy', 'Chaotrope', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Shed the Blood', 'Nightrage', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Spyglass', 'Lost in the Crawlspace', 2009, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Collapse of Men', 'With Life in Mind', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Afflicted', 'The Fetals', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Becoming Blue', 'Moving Atlas', 2010, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Close to Home', 'Jenium', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Collision of Fate', 'Nightrage', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Cool As the Other Side of the Pillow', 'The Cold Goodnight', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Creative Warrior', 'DoubleShot', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Damnation', 'Warpath', 2008, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Dark Lord', 'Fallen Angel', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Enemy', 'Stop the World', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Everyone''s the Same', 'The B.O.L.T.', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fight', 'Midnight Sun', 2001, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fly on the Wall', 'Minnesota Sex Junkies', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freeze Frame', 'Super Gravity', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hate Myself', 'Minnesota Sex Junkies', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Here Comes Tomorrow', 'C&O', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hey You', 'Gabriel and the Apocalypse', 2009, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Homeless', 'The B.O.L.T.', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Can''t Explain It', 'Analogue Revolution feat. Bryan Steele', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Cannibal', 'Calous', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Want It Back', 'Minnesota Sex Junkies', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Insanity of the Atoms', 'Hedras Ramos', 2011, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Leap of Faith', 'Analogue Revolution feat. Wendy Drown', 2009, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Life is a Roller Coaster', 'Evan Olson', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Like This', 'Minnesota Sex Junkies', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lose It All', 'BulletProof Messenger', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Warning', 'Severed', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nothing Ever Comes', 'The B.O.L.T.', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Opening in G', 'Kiev', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Other Personality', 'Hip Kitty', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Peace of Mind', 'The Break Down', 2009, 'Other', false, true, true, ARRAY['Rock Band DLC']),
('R U Ready For This', 'Analogue Revolution feat. Bryan Steele', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Railway Station', 'The Lightfighters', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Girl Next Door', 'Something Opus', 2009, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Ones Who Get It', 'Action Action', 2010, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Stranger', 'Bright Midnight', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Ultimate Power', 'Severed', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('This Fantasy', 'BulletProof Messenger', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Trailer Park Scum', 'Stereoside', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Wearing a Martyr''s Crown', 'Nightrage', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('What Is Light? Where Is Laughter?', 'Twin Atlantic', 2009, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('What''s a Man to Do?', 'DoubleShot', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('You Don''t Know Me', 'God in a Machine', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Footloose And Facy Free', 'Bill Bruford''s Earthworks', 1999, 'Jazz', false, true, true, ARRAY['Rock Band DLC']),
('Atomic', 'Blondie', 1979, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('A Fruit Fly In The Beehive', 'Gang Of Four', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Bean', 'Robby Suavé', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Revengers', 'Ron Wasserman', 2010, 'Rock', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Tunnels Of Vision', 'Sear Bliss', 2009, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Bohemian Like You', 'The Dandy Warhols', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rehab', 'Amy Winehouse', 2006, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 3']),
('One Armed Scissor', 'At the Drive-In', 2000, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Rock Lobster', 'The B-52''s', 1979, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Good Vibrations (Live)', 'The Beach Boys', 1968, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('In a Big Country', 'Big Country', 1983, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Heart of Glass', 'Blondie', 1978, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Get Up, Stand Up', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, false, ARRAY['Rock Band 3']),
('False Alarm', 'The Bronx', 2003, 'Punk', false, true, false, ARRAY['Rock Band 3']),
('25 or 6 to 4', 'Chicago', 1970, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Just Like Heaven', 'The Cure', 1987, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Space Oddity', 'David Bowie', 1969, 'Glam', false, true, false, ARRAY['Rock Band 3']),
('Foolin''', 'Def Leppard', 1983, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Whip It', 'Devo', 1980, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Rainbow in the Dark', 'Dio', 1983, 'Metal', false, true, false, ARRAY['Rock Band 3']),
('Walk of Life', 'Dire Straits', 1985, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Break on Through (To the Other Side)', 'The Doors', 1967, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('King George', 'Dover', 2001, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('The Killing Moon', 'Echo & The Bunnymen', 1984, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Saturday Night''s Alright for Fighting', 'Elton John', 1973, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Midlife Crisis', 'Faith No More', 1992, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Hey Man, Nice Shot', 'Filter', 1995, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Yoshimi Battles the Pink Robots Pt. 1', 'The Flaming Lips', 2002, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Cold as Ice', 'Foreigner', 1977, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Radar Love', 'Golden Earring', 1973, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Killing Loneliness', 'HIM', 2005, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('The Power of Love', 'Huey Lewis and the News', 1985, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Viva la Resistance', 'Hypernova', 2010, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Oh My God', 'Ida Maria', 2008, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Need You Tonight', 'INXS', 1987, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Centerfold', 'The J. Geils Band', 1981, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('I Got You (I Feel Good)', 'James Brown', 1974, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 3']),
('Been Caught Stealing', 'Jane''s Addiction', 1990, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Crosstown Traffic', 'The Jimi Hendrix Experience', 1968, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Imagine', 'John Lennon', 1971, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Me Enamora', 'Juanes', 2007, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Oye Mi Amor', 'Maná', 1992, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('The Beautiful People', 'Marilyn Manson', 1996, 'Metal', false, true, false, ARRAY['Rock Band 3']),
('Combat Baby', 'Metric', 2003, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Outer Space', 'The Muffs', 1997, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Sister Christian', 'Night Ranger', 1983, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Crazy Train', 'Ozzy Osbourne', 1980, 'Metal', false, true, false, ARRAY['Rock Band 3']),
('Misery Business', 'Paramore', 2007, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Llama', 'Phish', 1992, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Lasso', 'Phoenix', 2009, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Don''t Stand So Close to Me', 'The Police', 1980, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Antibodies', 'Poni Hoax', 2008, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('Something Bigger, Something Brighter', 'Pretty Girls Make Graves', 2003, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Jerry Was a Race Car Driver', 'Primus', 1991, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Du Hast', 'Rammstein', 1997, 'Metal', false, true, false, ARRAY['Rock Band 3']),
('Last Dance', 'The Raveonettes', 2009, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Portions for Foxes', 'Rilo Kiley', 2004, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Don''t Bury Me... I''m Still Not Dead', 'Riverboat Gamblers', 2006, 'Punk', false, true, false, ARRAY['Rock Band 3']),
('The Look', 'Roxette', 1988, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Walking on the Sun', 'Smash Mouth', 1997, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('Stop Me If You Think You''ve Heard This One Before', 'The Smiths', 1987, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Living in America', 'The Sounds', 2002, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('In the Meantime', 'Spacehog', 1995, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('Fly Like an Eagle', 'Steve Miller Band', 1976, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Plush', 'Stone Temple Pilots', 1992, 'Alternative', false, true, false, ARRAY['Rock Band 3']),
('This Bastard''s Life', 'Swingin'' Utters', 1998, 'Punk', false, true, false, ARRAY['Rock Band 3']),
('20th Century Boy', 'T. Rex', 1973, 'Glam', false, true, false, ARRAY['Rock Band 3']),
('Everybody Wants to Rule the World', 'Tears for Fears', 1985, 'New Wave', false, true, false, ARRAY['Rock Band 3']),
('The Con', 'Tegan and Sara', 2007, 'Indie Rock', false, true, false, ARRAY['Rock Band 3']),
('Dead End Friends', 'Them Crooked Vultures', 2009, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Humanoid', 'Tokio Hotel', 2009, 'Pop-Rock', false, true, false, ARRAY['Rock Band 3']),
('I Need to Know', 'Tom Petty and the Heartbreakers', 1978, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Get Free', 'The Vines', 2002, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Low Rider', 'WAR', 1975, 'R&B/Soul/Funk', false, true, false, ARRAY['Rock Band 3']),
('Werewolves of London', 'Warren Zevon', 1978, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('The Hardest Button to Button', 'The White Stripes', 2003, 'Rock', false, true, false, ARRAY['Rock Band 3']),
('Here I Go Again', 'Whitesnake', 1987, 'Glam', false, true, false, ARRAY['Rock Band 3']),
('I Can See for Miles', 'The Who', 1967, 'Classic Rock', false, true, false, ARRAY['Rock Band 3']),
('Roundabout', 'Yes', 1971, 'Prog', false, true, false, ARRAY['Rock Band 3']),
('Light My Fire', 'The Doors', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Riders on the Storm', 'The Doors', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Touch Me', 'The Doors', 1969, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hello, I Love You', 'The Doors', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('L.A. Woman', 'The Doors', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Her Madly', 'The Doors', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Me Two Times', 'The Doors', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Peace Frog', 'The Doors', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('People Are Strange', 'The Doors', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Roadhouse Blues', 'The Doors', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Soul Kitchen', 'The Doors', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Crystal Ship', 'The Doors', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Subdivisions', 'Rush', 1982, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Bad Medicine', 'Bon Jovi', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blaze of Glory', 'Bon Jovi', 1990, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Have a Nice Day', 'Bon Jovi', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('I''ll Be There for You', 'Bon Jovi', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('It''s My Life', 'Bon Jovi', 2000, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Lay Your Hands On Me', 'Bon Jovi', 1988, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Runaway', 'Bon Jovi', 1984, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Weren''t Born to Follow', 'Bon Jovi', 2009, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Who Says You Can''t Go Home', 'Bon Jovi', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blue Monday', 'New Order', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Burning Down the House', 'Talking Heads', 1983, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('My Own Summer (Shove It)', 'Deftones', 1997, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Jive Talkin''', 'Bee Gees', 1975, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Night Fever', 'Bee Gees', 1977, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Stayin'' Alive', 'Bee Gees', 1977, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Nights on Broadway', 'Bee Gees', 1975, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Tragedy', 'Bee Gees', 1979, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('You Should Be Dancing', 'Bee Gees', 1976, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('The Thrill is Gone', 'B.B. King', 1969, 'Blues', false, true, true, ARRAY['Rock Band DLC']),
('A Whiter Shade of Pale', 'Procol Harum', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Crippled Inside', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Jealous Guy', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('It''s So Hard', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Wanna Be a Soldier Mama', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gimme Some Truth', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Oh My Love', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('How Do You Sleep?', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('How?', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Oh Yoko!', 'John Lennon', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Can''t Get Enough', 'Bad Company', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Saturday Night Special', 'Lynyrd Skynyrd', 1975, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sweet Home Alabama (Live)', 'Lynyrd Skynyrd', 1976, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tuesday''s Gone', 'Lynyrd Skynyrd', 1973, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('What''s Your Name?', 'Lynyrd Skynyrd', 1977, 'Southern Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hammer to Fall', 'Queen', 1984, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Keep Yourself Alive', 'Queen', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Now I''m Here', 'Queen', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Play the Game', 'Queen', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tenement Funster', 'Queen', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Want To Break Free (RB3 Version)', 'Queen', 1984, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Somebody to Love (RB3 Version)', 'Queen', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Big Shot', 'Billy Joel', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Captain Jack', 'Billy Joel', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('It''s Still Rock and Roll to Me', 'Billy Joel', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Movin'' Out (Anthony''s Song)', 'Billy Joel', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Only the Good Die Young', 'Billy Joel', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Piano Man', 'Billy Joel', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pressure', 'Billy Joel', 1982, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Say Goodbye to Hollywood', 'Billy Joel', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Entertainer', 'Billy Joel', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Stranger', 'Billy Joel', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Didn''t Start the Fire', 'Billy Joel', 1989, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('You May Be Right', 'Billy Joel', 1980, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Happy Xmas (War Is Over)', 'John & Yoko, The Plastic Ono Band', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Peut-Être une Angine', 'Anaïs', 2008, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dis-Moi', 'BB Brunes', 2007, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Verdamp Lang Her', 'BAP', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nur ein Wort', 'Wir sind Helden', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fantasma', 'Linea 77', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Proibito', 'Litfiba', 1990, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Starting to Appreciate', 'Tutankamon', 2010, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dame Aire', 'Skizoo', 2007, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Jerk It Out', 'Caesars', 2005, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Maybe I''m Amazed', 'Paul McCartney', 1970, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Band on the Run', 'Paul McCartney & Wings', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Helen Wheels', 'Paul McCartney & Wings', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Let Me Roll It', 'Paul McCartney & Wings', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Open My Eyes', 'Inhabited', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cities in Dust', 'Siouxsie and The Banshees', 1986, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Cry, Cry, Cry', 'Johnny Cash', 1955, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Don''t Take Your Guns to Town', 'Johnny Cash', 1958, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Five Feet High and Rising', 'Johnny Cash', 1959, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Folsom Prison Blues', 'Johnny Cash', 1955, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('I Got Stripes', 'Johnny Cash', 1959, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('I Walk the Line', 'Johnny Cash', 1956, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Tennessee Flat Top Box', 'Johnny Cash', 1961, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('The Ballad of Ira Hayes', 'Johnny Cash', 1964, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Crawling', 'Linkin Park', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('In the End', 'Linkin Park', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Numb', 'Linkin Park', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Somewhere I Belong', 'Linkin Park', 2003, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Waiting for the End', 'Linkin Park', 2010, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('What I''ve Done', 'Linkin Park', 2007, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Made of Scars', 'Stone Sour', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Say You''ll Haunt Me', 'Stone Sour', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Through Glass', 'Stone Sour', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Blue Jean', 'David Bowie', 1984, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Fame', 'David Bowie', 1975, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Modern Love', 'David Bowie', 1983, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Young Americans', 'David Bowie', 1975, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('London Calling', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Brand New Cadillac', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Jimmy Jazz', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Hateful', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Rudie Can''t Fail', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Spanish Bombs', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Right Profile', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Lost in the Supermarket', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Clampdown', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Guns of Brixton', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Wrong ''Em Boyo', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Death or Glory', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Koka Kola', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Card Cheat', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Lover''s Rock', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Four Horsemen', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('I''m Not Down', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Revolution Rock', 'The Clash', 1979, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Bend Down Low', 'Bob Marley and the Wailers', 1974, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Burnin'' and Lootin''', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Coming in from the Cold', 'Bob Marley and the Wailers', 1980, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Kaya', 'Bob Marley and the Wailers', 1978, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Lively Up Yourself', 'Bob Marley and the Wailers', 1974, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('No More Trouble', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Small Axe', 'Bob Marley and the Wailers', 1973, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Them Belly Full (But We Hungry)', 'Bob Marley and the Wailers', 1974, 'Reggae/Ska', false, true, true, ARRAY['Rock Band DLC']),
('Obsession', 'Animotion', 1984, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Airplanes', 'B.o.B (featuring Hayley Williams)', 2010, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Total Eclipse of the Heart', 'Bonnie Tyler', 1983, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Don''t You Want Me', 'The Human League', 1981, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Need You Now', 'Lady Antebellum', 2010, 'Country', false, true, true, ARRAY['Rock Band DLC']),
('Paradise by the Dashboard Light', 'Meat Loaf', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stop Draggin'' My Heart Around', 'Stevie Nicks', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Fire and Ice', 'Pat Benatar', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love is a Battlefield', 'Pat Benatar', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shadows of the Night', 'Pat Benatar', 1982, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('We Belong', 'Pat Benatar', 1984, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Invincible', 'Pat Benatar', 1985, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Promises in the Dark', 'Pat Benatar', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Terrible Lie', 'Nine Inch Nails', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Head Like a Hole', 'Nine Inch Nails', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sanctified', 'Nine Inch Nails', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('The Only Time', 'Nine Inch Nails', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Never Let Me Down Again', 'Depeche Mode', 1987, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Personal Jesus', 'Depeche Mode', 1990, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Policy of Truth', 'Depeche Mode', 1990, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('I Will Possess Your Heart', 'Death Cab for Cutie', 2008, 'Indie Rock', false, true, true, ARRAY['Rock Band DLC']),
('Shooting the Moon', 'OK Go', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Every Breath You Take', 'The Police', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('So Lonely', 'The Police', 1978, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spill the Wine', 'War', 1970, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('I Go to Extremes', 'Billy Joel', 1989, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Miami 2017 (Seen the Lights Go Out on Broadway)', 'Billy Joel', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('My Life', 'Billy Joel', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Prelude/Angry Young Man', 'Billy Joel', 1976, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Scenes from an Italian Restaurant', 'Billy Joel', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('She''s Always a Woman', 'Billy Joel', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Somebody to Love', 'Jefferson Airplane', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Spinning Wheel', 'Blood, Sweat & Tears', 1968, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Operation Ground and Pound', 'DragonForce', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('The Loco-Motion', 'Grand Funk Railroad', 1974, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('We''re an American Band', 'Grand Funk Railroad', 1973, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Freeze-Frame', 'J. Geils Band', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Love Will Tear Us Apart', 'Joy Division', 1980, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Dreams', 'Fleetwood Mac', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Gold Dust Woman', 'Fleetwood Mac', 1977, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Landslide', 'Fleetwood Mac', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rhiannon', 'Fleetwood Mac', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Edge of Seventeen (Just Like the White Winged Dove)', 'Stevie Nicks', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stand Back', 'Stevie Nicks', 1983, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Breaking', 'Anberlin', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Blood and Thunder', 'Mastodon', 2004, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Fire', 'Ohio Players', 1974, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Love Rollercoaster', 'Ohio Players', 1975, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Must Have Done Something Right', 'Relient K', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('867-5309/Jenny', 'Tommy Tutone', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blue Bayou', 'Roy Orbison', 1963, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dream Baby (How Long Must I Dream)', 'Roy Orbison', 1962, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Only the Lonely (Know the Way I Feel)', 'Roy Orbison', 1960, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock and Roll All Nite (Live)', 'Kiss', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Strutter (Live)', 'Kiss', 1975, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Do You Really Want to Hurt Me', 'Culture Club', 1982, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('From Out of Nowhere', 'Faith No More', 1989, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Working for the Weekend', 'Loverboy', 1981, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Stash', 'Phish', 1992, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Tweezer', 'Phish', 1992, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Big Bang Baby', 'Stone Temple Pilots', 1996, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Long Road to Ruin', 'Foo Fighters', 2007, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rope', 'Foo Fighters', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Stacked Actors', 'Foo Fighters', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Walk', 'Foo Fighters', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Hard Rock Hallelujah', 'Lordi', 2006, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('King of Rock', 'Run-DMC', 1985, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('5 Minutes Alone', 'Pantera', 1994, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Walk', 'Pantera', 1992, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mouth for War', 'Pantera', 1992, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I''m Broken', 'Pantera', 1994, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Do You Feel Like We Do (Live)', 'Peter Frampton', 1976, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Born This Way', 'Lady Gaga', 2011, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('LoveGame', 'Lady Gaga', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Paparazzi', 'Lady Gaga', 2008, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Hot Blooded', 'Foreigner', 1978, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Urgent', 'Foreigner', 1981, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Mr. Crowley', 'Ozzy Osbourne', 1980, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Over the Mountain', 'Ozzy Osbourne', 1981, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Mama, I''m Coming Home', 'Ozzy Osbourne', 1991, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Steal Away (The Night)', 'Ozzy Osbourne', 1980, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Flying High Again', 'Ozzy Osbourne', 1981, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Diary of a Madman', 'Ozzy Osbourne', 1981, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('I Don''t Know', 'Ozzy Osbourne', 1980, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Grenade', 'Bruno Mars', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Just the Way You Are', 'Bruno Mars', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Marry You', 'Bruno Mars', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Audience of One', 'Rise Against', 2008, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Help Is on the Way', 'Rise Against', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Good Left Undone', 'Rise Against', 2006, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Take On Me', 'a-ha', 1985, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Unholy Confessions', 'Avenged Sevenfold', 2003, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Welcome to the Family', 'Avenged Sevenfold', 2010, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Tubthumping', 'Chumbawamba', 1997, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('I Alone', 'Live', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Lightning Crashes', 'Live', 1994, 'Alternative', false, true, true, ARRAY['Rock Band DLC']);
INSERT INTO rhythm_game_songs (title, artist, year, genre, is_guitar_hero, is_rock_band, is_dlc, games) VALUES
('Misery', 'Maroon 5', 2010, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Won''t Go Home Without You', 'Maroon 5', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Blurry', 'Puddle of Mudd', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Control', 'Puddle of Mudd', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('She Hates Me', 'Puddle of Mudd', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Here Without You', '3 Doors Down', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('When I''m Gone', '3 Doors Down', 2002, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('When You''re Young', '3 Doors Down', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Nothin'' but a Good Time', 'Poison', 1988, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Unskinny Bop', 'Poison', 1990, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('For What It''s Worth', 'Buffalo Springfield', 1967, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Man on the Moon', 'R.E.M.', 1992, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Aerials', 'System of a Down', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Hypnotize', 'System of a Down', 2005, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('A Little Respect', 'Erasure', 1988, 'New Wave', false, true, true, ARRAY['Rock Band DLC']),
('Relax (Come Fighting)', 'Frankie Goes to Hollywood', 1984, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Boom', 'P.O.D.', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Youth of the Nation', 'P.O.D.', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Blow Up the Outside World', 'Soundgarden', 1996, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Burden in My Hand', 'Soundgarden', 1996, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Fell on Black Days', 'Soundgarden', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Outshined', 'Soundgarden', 1991, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Rusty Cage', 'Soundgarden', 1991, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('The Day I Tried to Live', 'Soundgarden', 1994, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Heart of the Sunrise', 'Yes', 1971, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('I''ve Seen All Good People', 'Yes', 1971, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Owner of a Lonely Heart', 'Yes', 1983, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('South Side of the Sky', 'Yes', 1971, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Starship Trooper', 'Yes', 1971, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Make Some Noise', 'Beastie Boys', 2011, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('No Sleep till Brooklyn', 'Beastie Boys', 1986, 'Hip-Hop/Rap', false, true, true, ARRAY['Rock Band DLC']),
('Super Bad, Pts. 1 & 2', 'James Brown', 1970, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Tell Me Something Good', 'Rufus (featuring Chaka Khan)', 1974, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Animal (Live)', 'Def Leppard', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Bringin'' On the Heartbreak', 'Def Leppard', 1981, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Photograph', 'Def Leppard', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Pour Some Sugar on Me (Live)', 'Def Leppard', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Rock of Ages', 'Def Leppard', 1983, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Undefeated', 'Def Leppard', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dance, Dance', 'Fall Out Boy', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Sugar, We''re Goin Down', 'Fall Out Boy', 2005, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Thnks fr th Mmrs', 'Fall Out Boy', 2007, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Child in Time', 'Deep Purple', 1970, 'Prog', false, true, true, ARRAY['Rock Band DLC']),
('Adolescents', 'Incubus', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Pardon Me', 'Incubus', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Wish You Were Here', 'Incubus', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('By the Way', 'Red Hot Chili Peppers', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Californication', 'Red Hot Chili Peppers', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Look Around', 'Red Hot Chili Peppers', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Monarchy of Roses', 'Red Hot Chili Peppers', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Otherside', 'Red Hot Chili Peppers', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Parallel Universe', 'Red Hot Chili Peppers', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Scar Tissue', 'Red Hot Chili Peppers', 1999, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Adventures of Rain Dance Maggie', 'Red Hot Chili Peppers', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Want You to Want Me (Live)', 'Cheap Trick', 1979, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Surrender (Live)', 'Cheap Trick', 1979, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Dream Police', 'Cheap Trick', 1979, 'Pop-Rock', false, true, true, ARRAY['Rock Band DLC']),
('Unbelievable', 'EMF', 1991, 'Pop/Dance/Electronic', false, true, true, ARRAY['Rock Band DLC']),
('Me and Bobby McGee', 'Janis Joplin & the Full Tilt Boogie Band', 1971, 'Classic Rock', false, true, true, ARRAY['Rock Band DLC']),
('Hash Pipe', 'Weezer', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Island in the Sun', 'Weezer', 2001, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Perfect Situation', 'Weezer', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Rape Me', 'Nirvana', 1993, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('All Apologies', 'Nirvana', 1993, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('You Know You''re Right', 'Nirvana', 2002, 'Grunge', false, true, true, ARRAY['Rock Band DLC']),
('Wait and Bleed', 'Slipknot', 1999, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Left Behind', 'Slipknot', 2001, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Pulse of the Maggots', 'Slipknot', 2004, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Snuff', 'Slipknot', 2008, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Gold Cobra', 'Limp Bizkit', 2011, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Nookie', 'Limp Bizkit', 1999, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('My Way', 'Limp Bizkit', 2000, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Re-Arranged', 'Limp Bizkit', 1999, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Rock the Casbah', 'The Clash', 1982, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('The Party Song', 'Blink-182', 1999, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Stay Together for the Kids', 'Blink-182', 2001, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Up All Night', 'Blink-182', 2011, 'Punk', false, true, true, ARRAY['Rock Band DLC']),
('Yellow', 'Coldplay', 2000, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('The Scientist', 'Coldplay', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Clocks', 'Coldplay', 2002, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Fix You', 'Coldplay', 2005, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Viva la Vida', 'Coldplay', 2008, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('Every Teardrop Is a Waterfall', 'Coldplay', 2011, 'Alternative', false, true, true, ARRAY['Rock Band DLC']),
('I Believe in a Thing Called Love', 'The Darkness', 2003, 'Glam', false, true, true, ARRAY['Rock Band DLC']),
('Living Dead Girl', 'Rob Zombie', 1998, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Super-Charger Heaven', 'White Zombie', 1995, 'Metal', false, true, true, ARRAY['Rock Band DLC']),
('Sooner or Later', 'Breaking Benjamin', 2004, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Breath', 'Breaking Benjamin', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Until the End', 'Breaking Benjamin', 2006, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Forever', 'Papa Roach', 2006, 'Nu-Metal', false, true, true, ARRAY['Rock Band DLC']),
('Superstition', 'Stevie Wonder', 1972, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Higher Ground', 'Stevie Wonder', 1973, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Living for the City', 'Stevie Wonder', 1973, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('Sir Duke', 'Stevie Wonder', 1976, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('I Wish', 'Stevie Wonder', 1976, 'R&B/Soul/Funk', false, true, true, ARRAY['Rock Band DLC']),
('How You Remind Me', 'Nickelback', 2001, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Someday', 'Nickelback', 2003, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('Animals', 'Nickelback', 2005, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('If Today Was Your Last Day', 'Nickelback', 2008, 'Rock', false, true, true, ARRAY['Rock Band DLC']),
('This Means War', 'Nickelback', 2011, 'Rock', false, true, true, ARRAY['Rock Band DLC']);