/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

declare let self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Firebase Cloud Messaging setup
// Import Firebase scripts
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.7.1/firebase-messaging-compat.js');

// Firebase config will be injected at build time via define
declare const __FIREBASE_CONFIG__: {
  apiKey: string;
  authDomain: string;
  projectId: string;
  messagingSenderId: string;
  appId: string;
};

const firebaseConfig = __FIREBASE_CONFIG__;

// Only initialize Firebase if config is present
if (firebaseConfig.apiKey && firebaseConfig.projectId) {
  // @ts-expect-error - firebase is loaded via importScripts
  firebase.initializeApp(firebaseConfig);
  // @ts-expect-error - firebase is loaded via importScripts
  const messaging = firebase.messaging();

  // Handle background messages
  messaging.onBackgroundMessage((payload: { notification?: { title?: string; body?: string }; data?: Record<string, string> }) => {
    console.log('[SW] Background message received:', payload);

    const notificationTitle = payload.notification?.title || 'New Notification';
    const notificationOptions = {
      body: payload.notification?.body || '',
      icon: '/favicon.png',
      badge: '/favicon.png',
      data: payload.data || {},
      tag: payload.data?.tag || 'default',
      renotify: true,
    } as NotificationOptions;

    self.registration.showNotification(notificationTitle, notificationOptions);
  });
}

// Handle notification click
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event);
  event.notification.close();

  const urlToOpen = (event.notification.data?.url as string) || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          if (event.notification.data?.url) {
            (client as WindowClient).navigate(urlToOpen);
          }
          return;
        }
      }
      // Otherwise open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
