-- API Cost Tracking for OpenRouter calls
-- Generated by ManageMe

-- Track individual API calls with cost data
CREATE TABLE IF NOT EXISTS api_calls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID REFERENCES family_groups(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  function_name TEXT NOT NULL,  -- 'openrouter-compare', 'openrouter-round-story', 'ai-assistant'
  mode TEXT,                    -- 'story', 'theme', 'validate_song', 'comparison', etc.
  model TEXT,                   -- 'anthropic/claude-3.5-sonnet', etc.
  provider TEXT,                -- 'Anthropic', 'OpenAI', etc.
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  total_tokens INTEGER,
  estimated_cost_usd NUMERIC(10, 6),
  success BOOLEAN DEFAULT true,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_api_calls_group_created ON api_calls(group_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_calls_user_created ON api_calls(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_calls_function ON api_calls(function_name, created_at DESC);

-- Daily aggregates for reporting
CREATE TABLE IF NOT EXISTS api_cost_aggregates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id UUID REFERENCES family_groups(id) ON DELETE CASCADE,
  function_name TEXT NOT NULL,
  aggregate_date DATE NOT NULL,
  total_calls INTEGER DEFAULT 0,
  total_tokens INTEGER DEFAULT 0,
  total_cost_usd NUMERIC(10, 6) DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(group_id, function_name, aggregate_date)
);

CREATE INDEX IF NOT EXISTS idx_api_cost_aggregates_group_date ON api_cost_aggregates(group_id, aggregate_date DESC);

-- Enable RLS
ALTER TABLE api_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_cost_aggregates ENABLE ROW LEVEL SECURITY;

-- RLS policies - group members can view their group's API costs
CREATE POLICY "Group members can view api_calls"
  ON api_calls FOR SELECT
  USING (
    group_id IN (
      SELECT group_id FROM group_members WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Group members can view api_cost_aggregates"
  ON api_cost_aggregates FOR SELECT
  USING (
    group_id IN (
      SELECT group_id FROM group_members WHERE user_id = auth.uid()
    )
  );

-- Service role can insert (edge functions use service role)
CREATE POLICY "Service role can insert api_calls"
  ON api_calls FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can insert api_cost_aggregates"
  ON api_cost_aggregates FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Service role can update api_cost_aggregates"
  ON api_cost_aggregates FOR UPDATE
  USING (true);

-- Comment for documentation
COMMENT ON TABLE api_calls IS 'Tracks individual OpenRouter API calls with token usage and estimated costs';
COMMENT ON TABLE api_cost_aggregates IS 'Daily aggregated API costs per group and function';
